#!/bin/bash

#
# Apex Embedded Systems
# Summit board driver module unload script
#

#
# Make sure we are root
#
if [[ $EUID -ne 0 ]]; then
	echo "NOTICE: this script must be run as root" 1>&2
	exit 1
fi


SUMMIT_DIR="/media/sf_vb_shares/aes_drv"
export SUMMIT_DIR

#
# remove the module
#
cd $SUMMIT_DIR/drv_summit
rmmod mod_summit
