#!/bin/bash




#
# Apex Embedded Systems
# Summit board driver module load script
#

#
# Make sure we are root
#
if [[ $EUID -ne 0 ]]; then
	echo "NOTICE: this script must be run as root" 1>&2
	exit 1
fi

#SUMMIT_DIR="/media/sf_vb_shares/aes_drv"
#export SUMMIT_DIR

#
#find the root group
#
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

#
# remove the module if it is already loaded
#
#TEMPORARY:  cd $SUMMIT_DIR/drv_summit
#.#/summit_unload

#
# install the module
#
#TEMPORARY:  cd $SUMMIT_DIR/drv_summit
insmod mod_test.ko offset=0x300,0x310 bytes=0x10,0x10 acronym="stx104","tracer"
#allows parameters to be sent via text file.
#insmod mod_summit.ko "$(< aul_hw.txt)"
chgrp $group /dev/auldrv
chmod 666 /dev/auldrv
#chgrp $group /dev/stx104
#chmod 666 /dev/stx104
