Demo STX104 Simple: /home/mike/aes_eclipse/aul_tree/demo_shared/demo_stx104_shared.h File Reference
demo_stx104_shared.h File Reference
#include <time.h>
#include <inttypes.h>
#include "../aul/aul_public.h"
#include "../demo_shared/config.h"
Data Structures
struct demo_stx104_data
Macros
#define DEMO_STX104_SHARED_STATUS 21
#define DEMO_STX104_SHARED_NAME "demo_stx104"
#define DEMO_STX104_SHARED_H_REV "$Date: 2014-05-21 12:00:03 -0500 (Wed, 21 May 2014) $"
#define DEMO_STX104_DEBUG _DEBUG
#define DEMO_STX104_FIFO_LOG_FILE_NAME "fifo"
#define DEMO_STX104_FIFO_LOG_BUFFER_SIZE 256
#define DEMO_STX104_DATA_FILE_NAME "aiout"
#define DEMO_STX104_SHARED_STATUS_EC_DEFINITIONS(_) _(DEMO_STX104_SHARED_STATUS, EC_DEMO_STX104_FILE_OPEN_ERROR, 1, "file open error")
Enumerations
enum demo_status { DEMO_STX104_SHARED_STATUS_EC_DEFINITIONS }
Functions
int Demo_STX104_Menu_Frame_Max_Set (struct menu_command_params *p)
int Demo_STX104_Menu_Trigger_Start (struct menu_command_params *p)
int Demo_STX104_Menu_Trigger_Stop (struct menu_command_params *p)
int Demo_STX104_Menu_Revisions (struct menu_command_params *p)
char Demo_STX104_Data_Timer_Tick_State (void)
int Demo_STX104_Data_Timer_Tick (struct menu_data_params *mdp)
int Demo_STX104_Data_DI (struct menu_data_params *mdp)
int Demo_STX104_Data_Config_AI (struct menu_data_params *mdp)
int Demo_STX104_Data_Trig (struct menu_data_params *mdp)
int STX104_Data_Frames (struct menu_data_params *mdp)
int Demo_STX104_Main_Loop_Timing_Calculations (unsigned int time_msec, struct demo_stx104_data *ds)
void Demo_STX104_Files_Close (struct demo_stx104_data *ds)
int Demo_STX104_Files_Open (const char *data_file_name, const char *fifo_log_file_name, struct demo_stx104_data *ds)
void Demo_STX104_Terminate (char *prefix, struct demo_stx104_data *ds)
Shuts down the STX104 interface. First it turns off interrupts (if used) and then it turns off the triggering (optional...will not affect shutting things down). Second, it closes the board descriptor and then frees the driver.
int Demo_STX104_Initialize (char *prefix, int argc, char *argv[], struct demo_stx104_data *info)
Brings up the STX104 interface. First it connects to the driver and then it opens the board returning the board descriptor.
Variables
const char demo_data_file_name []
const char demo_data_file_name_csv []
const char demo_fifo_log_file_name []
const char demo_fifo_log_file_name_csv []
Macro Definition Documentation
#define DEMO_STX104_DATA_FILE_NAME "aiout"
Definition at line 56 of file demo_stx104_shared.h.
#define DEMO_STX104_DEBUG _DEBUG
Definition at line 50 of file demo_stx104_shared.h.
#define DEMO_STX104_FIFO_LOG_BUFFER_SIZE 256
Definition at line 54 of file demo_stx104_shared.h.
#define DEMO_STX104_FIFO_LOG_FILE_NAME "fifo"
Definition at line 53 of file demo_stx104_shared.h.
#define DEMO_STX104_SHARED_H_REV "$Date: 2014-05-21 12:00:03 -0500 (Wed, 21 May 2014) $"
Definition at line 47 of file demo_stx104_shared.h.
#define DEMO_STX104_SHARED_NAME "demo_stx104"
Definition at line 7 of file demo_stx104_shared.h.
#define DEMO_STX104_SHARED_STATUS 21
Definition at line 6 of file demo_stx104_shared.h.
#define DEMO_STX104_SHARED_STATUS_EC_DEFINITIONS (_) _(DEMO_STX104_SHARED_STATUS, EC_DEMO_STX104_FILE_OPEN_ERROR, 1, "file open error")
Definition at line 64 of file demo_stx104_shared.h.
Enumeration Type Documentation
enum demo_status
Enumerator
DEMO_STX104_SHARED_STATUS_EC_DEFINITIONS
ERROR_CODE_EXTRACTOR.
Definition at line 68 of file demo_stx104_shared.h.
 {
         DEMO_STX104_SHARED_STATUS_EC_DEFINITIONS( ERROR_CODE_EXTRACTOR )
         EC_DEMO_STX104_END_OF_LIST
 };
Function Documentation
int Demo_STX104_Data_Config_AI (struct menu_data_params * mdp)
Definition at line 384 of file demo_stx104_shared.c.
References demo_stx104_data::board, menu_data_params::info, and Menu_Data_Append().
 {
         struct demo_stx104_data * ds;
         stx104_ai_cfg_type                              ai_cfg;
         STX104_GEN_JMP_TYPE                     jumpers;
         ds = (struct demo_stx104_data *) mdp->info;
         /* get the jumper values UNI/BIP, SE/DIF */
         STX104_Gen_Jumpers_Get( ds->board, &jumpers );
         if ( jumpers.J9_ai_unipolar ) Menu_Data_Append( mdp, "UNI" );
         else                          Menu_Data_Append( mdp, "BIP" );
         Menu_Data_Append( mdp, " " );
         if ( jumpers.J8_ai_differential ) Menu_Data_Append( mdp, "DIF" );
         else                              Menu_Data_Append( mdp, "SE " );
         Menu_Data_Append( mdp, " " );
         /* get the current ADC value */
         STX104_AI_CFG_Get( ds->board, &ai_cfg );
         switch( ai_cfg.gain )
         {
                 case ACFG_GAIN_10V:             Menu_Data_Append( mdp, "  10V " ); break;
                 case ACFG_GAIN_5V:              Menu_Data_Append( mdp, "   5V " ); break;
                 case ACFG_GAIN_2_5V:    Menu_Data_Append( mdp, "2.5 V " ); break;
                 case ACFG_GAIN_1_25V:   Menu_Data_Append( mdp, "1.25V " ); break;
         }
         return SUCCESS;
 }
int Demo_STX104_Data_DI (struct menu_data_params * mdp)
Definition at line 362 of file demo_stx104_shared.c.
References demo_stx104_data::board, menu_data_params::info, Menu_Data_Append(), and menu_data_params::width_max.
 {
         struct demo_stx104_data * ds;
         BOOL value;
         int  channel;
         int  channel_count;
         ds = (struct demo_stx104_data *) mdp->info;
         channel_count = ((int) STX104_DI3) - ((int) STX104_DI0) + 1;
         /* if width too small to fit then just quit */
         if ( channel_count > mdp->width_max ) return 0;
         for ( channel  = ((int) STX104_DI3); channel >= ((int) STX104_DI0); channel-- )
         {
                 STX104_DI_Get( ds->board, (STX104_DI_ENUM) channel, &value );
                 if ( value )  Menu_Data_Append( mdp, "1" );
                 else          Menu_Data_Append( mdp, "0" );
         }
         return SUCCESS;
 }
int Demo_STX104_Data_Timer_Tick (struct menu_data_params * mdp)
Definition at line 354 of file demo_stx104_shared.c.
References menu_data_params::column, Demo_STX104_Data_Timer_Tick_State(), and menu_data_params::out_str.
 {
         /* shows that the software is running */
         mdp->out_str[mdp->column] = Demo_STX104_Data_Timer_Tick_State();
         mdp->column++;
         return SUCCESS;
 }
char Demo_STX104_Data_Timer_Tick_State (void)
Definition at line 347 of file demo_stx104_shared.c.
References timer_index, and TIMER_INDEX_MAX.
Referenced by Demo_STX104_Data_Timer_Tick().
 {
         if ( timer_index == TIMER_INDEX_MAX ) timer_index = 0;
         else                                  timer_index++;
         return timer_tick[timer_index];
 }
int Demo_STX104_Data_Trig (struct menu_data_params * mdp)
Definition at line 417 of file demo_stx104_shared.c.
References demo_stx104_data::board, menu_data_params::info, and Menu_Data_Append().
 {
         int     error_code;
         BOOL    trigger_enabled;
         struct demo_stx104_data * ds;
         ds                      = (struct demo_stx104_data *) mdp->info;
         error_code      = STX104_Trg_Active_Get( ds->board, &trigger_enabled );
         if ( trigger_enabled ) Menu_Data_Append( mdp, "1" );
         else                   Menu_Data_Append( mdp, "0" );
         return SUCCESS;
 }
void Demo_STX104_Files_Close (struct demo_stx104_data * ds)
Definition at line 482 of file demo_stx104_shared.c.
References demo_stx104_data::data_output_file, and demo_stx104_data::fifo_log_file.
 {
         if ( NULL != ds->data_output_file )
         {
                 fclose( ds->data_output_file );
                 ds->data_output_file = NULL;
         }
         if ( NULL != ds->fifo_log_file )
         {
                 fclose( ds->fifo_log_file );
                 ds->fifo_log_file = NULL;
         }
 }
int Demo_STX104_Files_Open (const char * data_file_name, const char * fifo_log_file_name, struct demo_stx104_data * ds)
Definition at line 503 of file demo_stx104_shared.c.
References demo_stx104_data::data_output_file, demo_data_file_name, demo_fifo_log_file_name, demo_stx104_data::fifo_log_buffer_index, demo_stx104_data::fifo_log_file, and demo_stx104_data::out_file.
 {
         if ( NULL == ds ) return -1; /* error codes? */
         if ( NULL == data_file_name ) data_file_name = demo_data_file_name;
 #if defined( _WIN32 )
         error_code = fopen_s( &(ds->data_output_file), data_file_name, "wb" );
 #else
         ds->data_output_file = fopen( data_file_name, "wb" );
 #endif
         if ( NULL == ds->data_output_file )
         {
                 fprintf( ds->out_file, "Cannot open '%s' file.\n", data_file_name );
                 return -EC_DEMO_STX104_FILE_OPEN_ERROR;
         }
         if ( NULL == fifo_log_file_name ) fifo_log_file_name = demo_fifo_log_file_name;
 #if defined( _WIN32 )
         error_code = fopen_s( &(ds->fifo_log_file), fifo_log_file_name, "wb" );
 #else
         ds->fifo_log_file = fopen( fifo_log_file_name, "wb" );
 #endif
         if ( NULL == ds->fifo_log_file )
         {
                 fprintf( ds->out_file, "Cannot open '%s' file.\n", fifo_log_file_name );
                 return -EC_DEMO_STX104_FILE_OPEN_ERROR;
         }
         ds->fifo_log_buffer_index = 0;
         return SUCCESS;
 }
int Demo_STX104_Initialize (char * prefix, int argc, char * argv[], demo_stx104_data * info)
Brings up the STX104 interface. First it connects to the driver and then it opens the board returning the board descriptor.
Note: The error_codes "error_code" can be used during debug to see what the functions are returning.
Definition at line 547 of file demo_stx104_shared.c.
References AUL_Device_Open(), AUL_Driver_Revision(), AUL_Initialization(), AUL_Library_Revision(), demo_stx104_data::board, demo_stx104_data::out_file, demo_stx104_data::revision_driver, demo_stx104_data::revision_firmware, and demo_stx104_data::revision_library.
Referenced by main().
 {
         int                     error_code;
         int                             board;
 #if defined( DEMO_STX104_DEBUG )
         FILE *                  out_file;
 #endif
         (void) argc;  /* not used currently */
         (void) argv;
 #if defined( DEMO_STX104_DEBUG )
         out_file = info->out_file; /* short hand */
         fprintf( out_file, "%sInitialization begin:\n", prefix );
 #endif
         /**** connect to driver ****/
 #ifdef _WIN32
         error_code = AUL_Initialization( "aul_hwdef.txt" );
 #else
         error_code = AUL_Initialization( NULL );
 #endif
         if ( error_code ) return error_code;
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%s  -> driver initialize success\n", prefix );
 #endif
         error_code = AUL_Library_Revision( &(info->revision_library) );
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%s  -> library revision = %u\n", prefix, info->revision_library );
 #endif
         error_code = AUL_Driver_Revision( &(info->revision_driver) );
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%s  -> driver revision = %u\n", prefix, info->revision_driver );
 #endif
         error_code = AUL_Device_Open( "stx104", &board );
         if ( error_code ) return error_code;
         info->board = board;
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%s  -> stx104 device open successfully\n", prefix );
 #endif
         error_code = STX104_Gen_Revision_Get( board, &(info->revision_firmware) );
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%s  -> stx104_firmware_revision = %04X\n",
                                                                                                 prefix, info->revision_firmware );
 #endif
    return SUCCESS;
 }
int Demo_STX104_Main_Loop_Timing_Calculations (unsigned int time_msec, struct demo_stx104_data * ds)
Definition at line 468 of file demo_stx104_shared.c.
References demo_stx104_data::main_loop_time_sec, demo_stx104_data::main_loop_time_spec, and demo_stx104_data::main_loop_time_usec.
Referenced by main().
 {
         double scratch;
         long int time_sec;
         ds->main_loop_time_sec  = ( (double) time_msec ) * 1.0e-3;  /* msec to sec      */
         ds->main_loop_time_usec = time_msec * 1000;                             /* msec to usec */
         time_sec = (long int) ds->main_loop_time_sec;
         ds->main_loop_time_spec.tv_sec = time_sec;
         scratch = ds->main_loop_time_sec - ( (double) time_sec );
         scratch = scratch * 1.0e9;  /* sec to nsec */
         ds->main_loop_time_spec.tv_nsec = (long) scratch;
         return SUCCESS;
 }
int Demo_STX104_Menu_Frame_Max_Set (struct menu_command_params * p)
Definition at line 284 of file demo_stx104_shared.c.
References menu_command_params::in_file, menu_command_params::info, Menu_Ask_Uint32(), menu_command_params::out_file, and demo_stx104_data::software_frame_count_max.
 {
         struct demo_stx104_data * ds;  /* data set */
         uint32_t        value;
         ds = (struct demo_stx104_data *) p->info;
         value = Menu_Ask_Uint32( p->in_file, p->out_file, "\n\nFrame count (0=manual start/stop)>" );
         if ( value > ( UINT32_MAX / 2 ) ) ds->software_frame_count_max = ( UINT32_MAX / 2 );
         else                                                      ds->software_frame_count_max = value;
         fprintf( p->out_file, "\n" );
         return SUCCESS;
 }
int Demo_STX104_Menu_Revisions (struct menu_command_params * p)
Definition at line 314 of file demo_stx104_shared.c.
References AUL_Driver_Is_Debug_Active(), menu_command_params::info, menu_command_params::out_file, demo_stx104_data::revision_driver, demo_stx104_data::revision_firmware, and demo_stx104_data::revision_library.
 {
         int driver_compiled_with_debug_flag = 0;
         struct demo_stx104_data * ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         /* revision information pulled from stx104_simple global data structure */
         fprintf( p->out_file, " Library Revision:            %lu\n", ds->revision_library       );
         fprintf( p->out_file, " Driver Revision:             %lu",   ds->revision_driver        );
         AUL_Driver_Is_Debug_Active( &driver_compiled_with_debug_flag );
         if ( driver_compiled_with_debug_flag ) fprintf( p->out_file, ", *** WARNING DEBUG ACTIVE ***\n" );
         else                                   fprintf( p->out_file, "\n" );
         fprintf( p->out_file, " Hardware Firmware Revision:  %04X", ds->revision_firmware       );
         return SUCCESS;
 }
int Demo_STX104_Menu_Trigger_Start (struct menu_command_params * p)
Definition at line 297 of file demo_stx104_shared.c.
References menu_command_params::board, and menu_command_params::info.
 {
         struct demo_stx104_data * ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         STX104_Trg_Software_Start( p->board );
         return SUCCESS;
 }
int Demo_STX104_Menu_Trigger_Stop (struct menu_command_params * p)
Definition at line 305 of file demo_stx104_shared.c.
References menu_command_params::board, and menu_command_params::info.
 {
         struct demo_stx104_data * ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         STX104_Trg_Software_Stop( p->board );
         return SUCCESS;
 }
void Demo_STX104_Terminate (char * prefix, demo_stx104_data * ds)
Shuts down the STX104 interface. First it turns off interrupts (if used) and then it turns off the triggering (optional...will not affect shutting things down). Second, it closes the board descriptor and then frees the driver.
Note: The error_codes "error_code" can be used during debug to see what the functions are returning.
Definition at line 608 of file demo_stx104_shared.c.
References AUL_Device_Close(), AUL_Termination(), demo_stx104_data::board, demo_stx104_data::cfg, demo_stx104_data::data_output_file, demo_stx104_data::fifo_log_file, demo_stx104_data::in_file, demo_stx104_data::out_file, and STX104_Config_Termination().
Referenced by main().
 {
         int                     error_code; /* used primarily with debugger */
         int             board;
         FILE *                  out_file;
 #ifndef DEMO_STX104_DEBUG
         (void) prefix;
 #endif
         out_file = ds->out_file; /* short hand */
         board    = ds->board;   /* short hand */
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%sTermination begin:\n", prefix );
 #endif
         /* set board to inactive state */
         error_code = STX104_Config_Termination( board, prefix, out_file, &(ds->cfg) );
         /* close the device */
         error_code = AUL_Device_Close( board );
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%s  -> AUL_Device_Closed\n", prefix );
 #endif
         /* close or free the driver */
         error_code = AUL_Termination();
 #if defined( DEMO_STX104_DEBUG )
         fprintf( out_file, "%s  -> AUL_Termination\n", prefix );
 #endif
         /* close any remaining open files */
         if ( NULL != ds->fifo_log_file )
         {
                 fclose( ds->fifo_log_file );            ds->fifo_log_file = NULL;
         }
         if ( NULL != ds->data_output_file )
         {
                 fclose( ds->data_output_file );         ds->data_output_file = NULL;
         }
         if ( NULL != ds->out_file )
         {
                 fclose( ds->out_file );         ds->out_file = NULL;
         }
         if ( NULL != ds->in_file )
         {
                 fclose( ds->in_file );          ds->in_file = NULL;
         }
 }
int STX104_Data_Frames (struct menu_data_params * mdp)
Definition at line 430 of file demo_stx104_shared.c.
References demo_stx104_data::fifo_full_error, menu_data_params::info, demo_stx104_data::interrupt_blocking, Menu_Data_Append(), demo_stx104_data::software_frame_count, and STX104_FRAME_STR_SIZE.
 {
 #define STX104_FRAME_STR_SIZE  16
         struct demo_stx104_data * ds;
         /*int                                     frames;*/
         char                                      tmp_str[STX104_FRAME_STR_SIZE];
         ds = (struct demo_stx104_data *) mdp->info;
 #if(0)
 #if defined( STX104_SIMPLE_USE_INTERRUPTS )
         while ( ds->interrupt_blocking ) {}; /* wait for interrupt to complete.*/
 #endif
 #endif
         if ( ds->fifo_full_error )
         {
                 String_Copy( tmp_str, "FIFO_FULL", STX104_FRAME_STR_SIZE );
         }
         else
         {
                 snprintf( tmp_str, STX104_FRAME_STR_SIZE, "%8d", ds->software_frame_count );
         }
         Menu_Data_Append( mdp, tmp_str );
         return SUCCESS;
 #undef STX104_FRAME_STR_SIZE
 }
Variable Documentation
const char demo_data_file_name[]
Definition at line 496 of file demo_stx104_shared.c.
Referenced by Demo_STX104_Files_Open().
const char demo_data_file_name_csv[]
Definition at line 497 of file demo_stx104_shared.c.
const char demo_fifo_log_file_name[]
Definition at line 498 of file demo_stx104_shared.c.
Referenced by Demo_STX104_Files_Open().
const char demo_fifo_log_file_name_csv[]
Definition at line 499 of file demo_stx104_shared.c.