Demo STX104 Simple: /home/mike/aes_eclipse/aul_tree/demo_shared/menu.h File Reference
menu.h File Reference
#include "../shared/status_macros.h"
Data Structures
struct menu_command_params
Data type used to pass information to/from menu command functions. It is provided more for convenience and reduction in parameters passed to/from a menu related function.
struct menu_command
Data structure used to create the menu structure or list that is presented to the user. For each of the menu items there maybe be key-stroke character(s) and an associated function call made to perform the specific operation.
struct menu_data_params
struct menu_data
Data structure used to create the single output line of data. Each item will write out as: "<prefix><data>". The prefix begins at column_start.
Macros
#define DEMO_MENU 22
#define DEMO_MENU_NAME "demo_menu"
#define NULL_CHARACTER 0x00
#define MENU_DISPLAY_LINE_LENGTH 80
#define DEMO_MENU_EC_DEFINITIONS(_)
Typedefs
typedef int(* MENU_COMMAND_FNC_TYPE) (struct menu_command_params *p)
typedef int(* MENU_DATA_FNC_TYPE) (struct menu_data_params *mdp)
typedef int(* menu_loop_function_type) (void *private_data)
typedef int(* menu_stop_request_function_type) (void *private_data)
Enumerations
enum menu_status { EC_DEMO_MENU_END_OF_LIST }
Functions
uint16_t Menu_Ask_For_Value (FILE *in_file, FILE *out_file, const char *question)
void Menu_Display_Clear_Line (FILE *out_file)
Clear the line on the output up to the output line length.
int Menu_AI_First_Channel_Set (struct menu_command_params *p)
Set the analog input (AI) configuration first channel by data passed from menu. It assumes that the device has been opened successfully.
int Menu_AI_Last_Channel_Set (struct menu_command_params *p)
Set the analog input (AI) configuration last channel by data passed from menu. It assumes that the device has been opened successfully.
int Menu_AI_Channel_Set (struct menu_command_params *p)
Set the analog input (AI) configuration first and last channel by data passed from menu. It assumes that the device has been opened successfully.
int Menu_AI_Gain_Set (struct menu_command_params *p)
Set the analog input (AI) configuration gain. It assumes that the device has been opened successfully.
int Menu_AO_Value_Set (struct menu_command_params *p)
int Menu_DO_All_Set (struct menu_command_params *p)
int Menu_DO_Value_Set (struct menu_command_params *p)
int Menu_Quit (struct menu_command_params *p)
int Menu_Report_File (struct menu_command_params *p)
int Menu_Report_Console (struct menu_command_params *p)
int Menu_Redraw (struct menu_command_params *p)
BOOL Menu_Get_Character (int *menu_character)
uint32_t Menu_Ask_Uint32 (FILE *in_file, FILE *out_file, const char *question)
Ask for an unsigned 32-bit value.
uint16_t Menu_Ask_Uint16 (FILE *in_file, FILE *out_file, const char *question)
Ask for an unsigned 16-bit value.
int Menu_Periodic_Run (double time_sec, menu_loop_function_type loop_function, menu_stop_request_function_type stop_request_function, void *private_data)
The librt.a library to support High Resolution POSIX Timers (HRT) is added to the linker. The following functions are a part of this library: timer_create(), timer_settime(), timer_delete().
int Menu_Command (struct menu_command menu_list[], int board, FILE *in_file, FILE *out_file, void *info)
void Menu_Display (struct menu_command menu_list[], int board, FILE *out_file, void *info)
void Menu_Data_Append (struct menu_data_params *mdp, char *msg_str)
void Menu_Data (struct menu_data *data_list, int column_begin, int board, FILE *out_file, void *info)
void Menu_Termination (void)
void Menu_Initialization (struct menu_command menu_list[])
Macro Definition Documentation
#define DEMO_MENU 22
Definition at line 2 of file menu.h.
#define DEMO_MENU_EC_DEFINITIONS (_)
Value:
_(DEMO_MENU,   EC_DEMO_MENU_OK,                                0,  "")\
        _( DEMO_MENU,   EC_DEMO_MENU_COMMAND_NOT_FOUND,         1,  ""     )\
        _( DEMO_MENU,   EC_DEMO_MENU_QUIT,                              2,  ""     )\
        _( DEMO_MENU,   EC_DEMO_MENU_TIMER_SIGACTION,           3,  ""     )\
        _( DEMO_MENU,   EC_DEMO_MENU_TIMER_CREATE,                      4,  ""     )\
        _( DEMO_MENU,   EC_DEMO_MENU_TIMER_SETTIME,                     5,  ""     )\
        _( DEMO_MENU,   EC_DEMO_MENU_TIMER_ACTIVE,                      6,  ""     )\
        _( DEMO_MENU,   EC_DEMO_MENU_TIMER_INFO_INVALID,        7,  ""     )
Definition at line 53 of file menu.h.
#define DEMO_MENU_NAME "demo_menu"
Definition at line 3 of file menu.h.
#define MENU_DISPLAY_LINE_LENGTH 80
Definition at line 44 of file menu.h.
Referenced by Menu_Data(), and Menu_Display_Clear_Line().
#define NULL_CHARACTER 0x00
Definition at line 43 of file menu.h.
Referenced by Menu_Data(), Menu_Display(), Menu_Display_Clear_Line(), and Menu_Get_Character().
Typedef Documentation
typedef int(* MENU_COMMAND_FNC_TYPE) (struct menu_command_params *p)
Definition at line 106 of file menu.h.
typedef int(* MENU_DATA_FNC_TYPE) (struct menu_data_params *mdp)
Definition at line 145 of file menu.h.
typedef int(* menu_loop_function_type) (void *private_data)
Definition at line 164 of file menu.h.
typedef int(* menu_stop_request_function_type) (void *private_data)
Definition at line 165 of file menu.h.
Enumeration Type Documentation
enum menu_status
Enumerator
EC_DEMO_MENU_END_OF_LIST
Definition at line 66 of file menu.h.
 {
         DEMO_MENU_EC_DEFINITIONS( ERROR_CODE_EXTRACTOR )
         EC_DEMO_MENU_END_OF_LIST
 };
Function Documentation
int Menu_AI_Channel_Set (menu_command_params * p)
Set the analog input (AI) configuration first and last channel by data passed from menu. It assumes that the device has been opened successfully.
Parameters
p menu parameters passed in/out of this function
Returns
Always returns SUCCESS
Definition at line 188 of file menu.c.
References menu_command_params::board, and menu_command_params::channel.
 {
         stx104_ai_cfg_type ai_cfg;
         STX104_AI_CFG_Get( p->board, &ai_cfg );
         ai_cfg.first_channel = (STX104_AI_ENUM) p->channel;
         ai_cfg.last_channel  = (STX104_AI_ENUM) p->channel;
         STX104_AI_CFG_Set( p->board, &ai_cfg );
         return SUCCESS;
 }
int Menu_AI_First_Channel_Set (menu_command_params * p)
Set the analog input (AI) configuration first channel by data passed from menu. It assumes that the device has been opened successfully.
Parameters
p menu parameters passed in/out of this function
Returns
Always returns SUCCESS
Definition at line 154 of file menu.c.
References menu_command_params::board, and menu_command_params::channel.
 {
         stx104_ai_cfg_type ai_cfg;
         STX104_AI_CFG_Get( p->board, &ai_cfg );
         ai_cfg.first_channel = (STX104_AI_ENUM) p->channel;
         STX104_AI_CFG_Set( p->board, &ai_cfg );
         return SUCCESS;
 }
int Menu_AI_Gain_Set (menu_command_params * p)
Set the analog input (AI) configuration gain. It assumes that the device has been opened successfully.
Parameters
p menu parameters passed in/out of this function
Returns
Always returns SUCCESS
Definition at line 208 of file menu.c.
References menu_command_params::board, and menu_command_params::channel.
 {
         stx104_ai_cfg_type ai_cfg;
         STX104_AI_CFG_Get( p->board, &ai_cfg );
         ai_cfg.gain = (STX104_AI_GAIN_ENUM) p->channel;
         STX104_AI_CFG_Set( p->board, &ai_cfg );
         return SUCCESS;
 }
int Menu_AI_Last_Channel_Set (menu_command_params * p)
Set the analog input (AI) configuration last channel by data passed from menu. It assumes that the device has been opened successfully.
Parameters
p menu parameters passed in/out of this function
Returns
Always returns SUCCESS
Definition at line 171 of file menu.c.
References menu_command_params::board, and menu_command_params::channel.
 {
         stx104_ai_cfg_type ai_cfg;
         STX104_AI_CFG_Get( p->board, &ai_cfg );
         ai_cfg.last_channel  = (STX104_AI_ENUM) p->channel;
         STX104_AI_CFG_Set( p->board, &ai_cfg );
         return SUCCESS;
 }
int Menu_AO_Value_Set (struct menu_command_params * p)
Definition at line 217 of file menu.c.
References menu_command_params::board, menu_command_params::channel, menu_command_params::in_file, LOCAL_STRING_BUFFER_SIZE, Menu_Ask_Uint16(), Menu_Display_Clear_Line(), and menu_command_params::out_file.
 {
         uint16_t value;
         char   question_str[LOCAL_STRING_BUFFER_SIZE];
         Menu_Display_Clear_Line( p->out_file );
 #ifdef __BORLANDC__
         sprintf( question_str, "AO%d> ", p->channel );
 #else
         snprintf( question_str, LOCAL_STRING_BUFFER_SIZE, "AO%d> ", p->channel );
 #endif
         value = Menu_Ask_Uint16( p->in_file, p->out_file, question_str );
         STX104_AO_Set( p->board, (STX104_AO_ENUM) p->channel, value );
         return SUCCESS;
 }
uint16_t Menu_Ask_For_Value (FILE * in_file, FILE * out_file, const char * question)
uint16_t Menu_Ask_Uint16 (FILE * in_file, FILE * out_file, const char * question)
Ask for an unsigned 16-bit value.
Parameters
in_file Request input from this location (keyboard)
out_file Produce resulting output to this location (display)
question Question regarding the number request
Returns
The unsigned 16-bit value
Definition at line 98 of file menu.c.
References LOCAL_STRING_BUFFER_SIZE, and MENU_MAX_INPUT_SIZE.
Referenced by Menu_AO_Value_Set(), Menu_DO_All_Set(), and Menu_DO_Value_Set().
 {
         char in_str[LOCAL_STRING_BUFFER_SIZE];
         char *endptr;
         fprintf( out_file, "%s", question );
         fgets( in_str, MENU_MAX_INPUT_SIZE, in_file );
         return( (uint16_t) strtol(in_str, &endptr, 0) );
 }
uint32_t Menu_Ask_Uint32 (FILE * in_file, FILE * out_file, const char * question)
Ask for an unsigned 32-bit value.
Parameters
in_file Request input from this location (keyboard)
out_file Produce resulting output to this location (display)
question Question regarding the number request
Returns
The unsigned 32-bit value
Definition at line 115 of file menu.c.
References LOCAL_STRING_BUFFER_SIZE, and MENU_MAX_INPUT_SIZE.
Referenced by Demo_STX104_Menu_Frame_Max_Set().
 {
         char in_str[LOCAL_STRING_BUFFER_SIZE];
         char *endptr;
         fprintf( out_file, "%s", question );
         fgets( in_str, MENU_MAX_INPUT_SIZE, in_file );
         return( (uint32_t) strtol(in_str, &endptr, 0) );
 }
int Menu_Command (struct menu_command menu_list[], int board, FILE * in_file, FILE * out_file, void * info)
Definition at line 660 of file menu.c.
References menu_command_params::board, menu_command_params::channel, menu_command::function, menu_command_params::in_file, menu_command_params::info, Menu_Get_Character(), and menu_command_params::out_file.
Referenced by STX104_Simple_Main_Loop().
 {
         size_t  index;
         int     char_menu;
         int             error_code;
         BOOL    command_valid;
         struct menu_command_params p;
         p.board    = board;
         p.in_file  = in_file;
         p.out_file = out_file;
         p.info     = info;
         p.channel  = 0;
         error_code = SUCCESS;
         if( Menu_Get_Character( &char_menu ) )
         {
                 index = 0;
                 while ( ( NULL != menu_list[index].function )  ||
                                 ( NULL != menu_list[index].display  )   )
                 {
                         command_valid = false;
                         /* determine channel info and command validity */
                         if ( menu_list[index].char_last >= ' ' )
{
                                 if ( ( char_menu >= menu_list[index].char_first ) &&
                                          ( char_menu <= menu_list[index].char_last  )  )
{
                                         command_valid = true;
                                 }
                         }
                         else if ( char_menu == menu_list[index].char_first )
{
                                 command_valid = true;
                         }
                         if ( command_valid )
                         { /* command found, process it */
                                 /* build channel information here */
                                 if ( ( menu_list[index].char_first >= ' ' ) && ( menu_list[index].char_last >= ' ' ) )
{
                                         p.channel = (size_t) ( char_menu - menu_list[index].char_first );
                                         /*NOTE: this is an exception that is not well handled!!!*/
                                         if ( 'a' == menu_list[index].char_first ) p.channel = p.channel + 10;
                                 }
                                 else if ( menu_list[index].char_last < ' ' )
{
                                         p.channel = (int) menu_list[index].char_last;
                                 }
                                 error_code = (* menu_list[index].function )( &p );
                                 return error_code;
                         }
                         else
                         {  /* command not found - test next */
                         index++;
                         }
                 } /* while */
         } /* if menu character available */
         return error_code;
 }
void Menu_Data (struct menu_data * data_list, int column_begin, int board, FILE * out_file, void * info)
Definition at line 754 of file menu.c.
References menu_data_params::column, menu_data::column_start, menu_data::function, menu_data_params::info, menu_data_str, MENU_DISPLAY_LINE_LENGTH, NULL_CHARACTER, menu_data_params::out_str, menu_data_params::out_str_size, menu_data::prefix, menu_data::prefix_length, menu_data_params::width_max, and menu_data::width_max.
Referenced by STX104_Simple_Main_Loop().
 {
         int index;
         /* int max_width; */
         int col_delta;
         /*int column;*/
         int row;
         int error_code;  /* used for debugging */
         BOOL not_done;
         struct menu_data_params mdp; /* mdp = short hand for menu data parameters */
         (void) board;
         /* assign initial values */
         mdp.out_str_size = ((int) (MENU_DISPLAY_LINE_LENGTH - 1) );
         mdp.info         = info;
         mdp.out_str      = menu_data_str;
         mdp.column   = 0;
         row          = 0;
         not_done     = true;
         /* add spaces, if necessary  */
         col_delta = data_list[row].column_start - column_begin;
         for ( index = 0; index < col_delta; index++ )
         {
                 menu_data_str[mdp.column] = ' ';
                 mdp.column++;
         }
         while ( not_done )
         {
                 /* add spaces, if necessary  */
                 col_delta = data_list[row].column_start - mdp.column;
                 for ( index = 0; index < col_delta; index++ )
                 {
                         menu_data_str[mdp.column] = ' ';
                         mdp.column++;
                 }
                 /* post prefix, if present */
                 if ( data_list[row].prefix_length > 0 )
                 {
                         for ( index = 0; index < data_list[row].prefix_length; index++ )
{
                                 menu_data_str[mdp.column] = data_list[row].prefix[index];
                                 mdp.column++;
                         }
                 }
                 /* run helper function */
                 if ( NULL != data_list[row].function )
                 {
                         mdp.width_max = ((int) MENU_DISPLAY_LINE_LENGTH) - mdp.column - 1 /* null */;
                         /* if width max specified then test against biggest value */
                         if ( data_list[row].width_max > 0 )
{
                                 if ( data_list[row].width_max < mdp.width_max )
                                 mdp.width_max = data_list[row].width_max;
                         }
                         /* call the menu data helper function */
                         error_code = ( *(data_list[row].function) )( &mdp );
                         if ( mdp.column < 0 )
{
                                 menu_data_str[0] = NULL_CHARACTER;
                                 not_done = false;
                         }
                 }
                 /* prepare for next row, quit if at end of rows )  */
                 row++;
                 if (  ( NULL == data_list[row].function )  &&
                 ( NULL == data_list[row].prefix   )   )
                 {
                         not_done = false;
                 }
                 /*if ( row == 2 ) not_done = false;*/
         } /* while */
         menu_data_str[mdp.column] = NULL_CHARACTER;
         fprintf( out_file, "%s\r", menu_data_str );
         /*fprintf( out_file, "%s   col=%d\n", menu_data_str, mdp.column );*/
 }
void Menu_Data_Append (struct menu_data_params * mdp, char * msg_str)
Definition at line 734 of file menu.c.
References menu_data_params::column, menu_data_params::out_str, and menu_data_params::out_str_size.
Referenced by Demo_STX104_Data_Config_AI(), Demo_STX104_Data_DI(), Demo_STX104_Data_Trig(), STX104_Data_Frames(), STX104_Simple_Data_AI_Channel(), and STX104_Simple_Data_AI_Value().
 {
         int msg_str_length;
         int index;
         msg_str_length = (int) strlen( msg_str );
         if ( (mdp->column + msg_str_length) > mdp->out_str_size )
         {
                 msg_str_length = mdp->out_str_size - mdp->column;
         }
         for ( index = 0; index < msg_str_length; index++ )
         {
                 mdp->out_str[mdp->column + index] = msg_str[index];
         }
         mdp->column = mdp->column + msg_str_length;
 }
void Menu_Display (struct menu_command menu_list[], int board, FILE * out_file, void * info)
Definition at line 563 of file menu.c.
References menu_command_params::board, menu_command_params::channel, menu_command::char_first, menu_command::char_last, menu_command::function, menu_command_params::in_file, menu_command_params::info, MENU_DISPLAY_LIST_SIZE, NULL_CHARACTER, and menu_command_params::out_file.
Referenced by main(), and Menu_Redraw().
 {
         size_t  index;
         BOOL    command_valid;
         BOOL    display_only;
         BOOL    line_terminate;
 #define MENU_DISPLAY_LIST_SIZE 12
         char    char_list[MENU_DISPLAY_LIST_SIZE];
         char    char_str[2];
         struct menu_command_params p;
         p.board    = board;
         p.in_file  = NULL;
         p.out_file = out_file;
         p.info     = info;
         p.channel  = 0;
         index = 0;
         strcpy( char_list, "" );
         while ( ( NULL != menu_list[index].function )  ||
                    ( NULL != menu_list[index].display  )   )
         {
                 command_valid  = false;
                 display_only   = false;
                 line_terminate = false;
                 /* build character list */
                 if ( ( menu_list[index].char_first >= ' ' ) && ( menu_list[index].char_last >= ' ' ) )
                 { /* character input range exists */
                         if ( strlen( char_list ) > 0 ) strcat( char_list, "," );
                         char_str[0] = menu_list[index].char_first;
                         char_str[1] = NULL_CHARACTER;
                         strcat( char_list,  char_str );
                         strcat( char_list,  "-" );
                         char_str[0] = menu_list[index].char_last;
                         char_str[1] = NULL_CHARACTER;
                         strcat( char_list,  char_str  );
                 }
                 else if ( menu_list[index].char_first >= ' ' )
                 { /* only first character exists */
                         if ( strlen( char_list ) > 0 ) strcat( char_list, "," );
                         char_str[0] = menu_list[index].char_first;
                         char_str[1] = NULL_CHARACTER;
                         strcat( char_list,  char_str  );
                 }
                 else
                 {  /* display string only  -- because char_first is a null character */
                         display_only = true;
                         if ( menu_list[index].char_last < ' ' )
                         {  /* print out prefix spaces */
                                 size_t index;
                                 for ( index = 0; index < ((size_t) menu_list[index].char_last); index++ )
{
                                         fprintf( out_file, " " );
                                 }
                         }
                         /* determine whether or not to run display helper function */
                         if ( NULL != menu_list[index].function ) command_valid = true;
                         /* output display item if available */
                         if ( NULL != menu_list[index].display )
{
                         fprintf( out_file, "%s", menu_list[index].display );
                         line_terminate = true;
                         }
                 }
                 /* output line */
                 if ( false == display_only )
                 {
                         if ( NULL != menu_list[index].display )
{
                                 fprintf( out_file, "%8s) %s", char_list, menu_list[index].display );
                                 strcpy( char_list, "" );
                                 line_terminate = true;
                         }
                 }
                 /* run display helper function */
                 if ( command_valid )
                 {
                         (* menu_list[index].function )( &p );
                         line_terminate = true;
                         /*command_valid = false;*/
                 }
                 /* line termination */
                 if ( line_terminate )
                 {
                         fprintf( out_file, "\n" );
                         /*line_terminate = false;*/
                 }
                 index++;
         }  /* while */
 }
void Menu_Display_Clear_Line (FILE * out_file)
Clear the line on the output up to the output line length.
Parameters
out_file The output typically the display.
Definition at line 129 of file menu.c.
References MENU_DISPLAY_LINE_LENGTH, and NULL_CHARACTER.
Referenced by Menu_AO_Value_Set(), Menu_DO_All_Set(), and Menu_DO_Value_Set().
 {
         char out_msg[MENU_DISPLAY_LINE_LENGTH];
         int cp;
         for( cp=0; cp<MENU_DISPLAY_LINE_LENGTH; cp++ ) out_msg[cp] = ' ';
         out_msg[MENU_DISPLAY_LINE_LENGTH-1] = NULL_CHARACTER;
         fprintf( out_file, "%s\r", out_msg );
 }
int Menu_DO_All_Set (struct menu_command_params * p)
Definition at line 233 of file menu.c.
References menu_command_params::board, menu_command_params::in_file, LOCAL_STRING_BUFFER_SIZE, Menu_Ask_Uint16(), Menu_Display_Clear_Line(), and menu_command_params::out_file.
 {
         uint16_t value;
         char   question_str[LOCAL_STRING_BUFFER_SIZE];
         Menu_Display_Clear_Line( p->out_file );
 #ifdef __BORLANDC__
         sprintf( question_str, "DOUT ALL (nibble value)> " );
 #else
         snprintf( question_str, LOCAL_STRING_BUFFER_SIZE, "DOUT ALL (nibble value)> " );
 #endif
         value = Menu_Ask_Uint16( p->in_file, p->out_file, question_str );
         STX104_DO_All_Set( p->board, (uint8_t) ( value & 0x0F ) );
         return SUCCESS;
 }
int Menu_DO_Value_Set (struct menu_command_params * p)
Definition at line 248 of file menu.c.
References menu_command_params::board, menu_command_params::channel, menu_command_params::in_file, LOCAL_STRING_BUFFER_SIZE, Menu_Ask_Uint16(), Menu_Display_Clear_Line(), and menu_command_params::out_file.
 {
         uint16_t value;
         char   question_str[LOCAL_STRING_BUFFER_SIZE];
         Menu_Display_Clear_Line( p->out_file );
 #ifdef __BORLANDC__
         sprintf( question_str, "DOUT%d = ", p->channel );
 #else
         snprintf( question_str, LOCAL_STRING_BUFFER_SIZE, "DOUT%d = ", p->channel );
 #endif
         value = Menu_Ask_Uint16( p->in_file, p->out_file, question_str );
         if ( value ) STX104_DO_Set( p->board, (STX104_DO_ENUM) p->channel, true  );
         else         STX104_DO_Set( p->board, (STX104_DO_ENUM) p->channel, false );
         return SUCCESS;
 }
BOOL Menu_Get_Character (int * menu_character)
Definition at line 361 of file menu.c.
References NULL_CHARACTER.
Referenced by Menu_Command().
 {
         BOOL result = false;
 #ifdef __BORLANDC__
         if ( kbhit() )
         {
                 *menu_character = getch();
                 result = true;
         }
         else
         {
                 *menu_character = NULL_CHARACTER;
         }
 #elif _WIN32
         if ( _kbhit() )
         {
                 *menu_character = getch();
                 result = true;
         }
         else
         {
                 *menu_character = NULL_CHARACTER;
         }
 #else /* assuming linux */
         int character = Menu_Keyboard_Get();
         if ( character >= 0 )
         {
                 *menu_character = character;
                 result = true;
         }
         else
         {
                 *menu_character = NULL_CHARACTER;
         }
 #endif
         return result;
 }
void Menu_Initialization (struct menu_command menu_list[])
Definition at line 844 of file menu.c.
References menu_timer_info.
Referenced by main().
 {
 #if __linux__
 /*      Menu_Keyboard_Initialize();*/
         Mem_Set( &menu_timer_info, 0, sizeof( menu_timer_info ) );
 #endif
         menu_menu_list = menu_list;
 }
int Menu_Periodic_Run (double time_sec, menu_loop_function_type loop_function, menu_stop_request_function_type stop_request_function, void * private_data)
The librt.a library to support High Resolution POSIX Timers (HRT) is added to the linker. The following functions are a part of this library: timer_create(), timer_settime(), timer_delete().
Location of library: ./usr/lib/i386-linux-gnu/librt.a
Parameters
time_sec
loop_function
stop_request_function
private_data
Returns
Definition at line 485 of file menu.c.
References menu_timer_data::loop_function, Menu_Signal_Action_Handler(), menu_timer_info, MENU_TIMER_SIG, menu_timer_data::private_data, menu_timer_data::stop_request_function, and menu_timer_data::timer_id.
Referenced by main().
 {
         int                                                     error_code;
         struct sigaction                        sa; /* signal action */
         struct sigevent                         se; /* signal event  */
         struct menu_timer_data *        mtd;/* menu timer data */
         struct itimerspec                       ts; /* timer specification */
         error_code = SUCCESS;
         /* create a signal handler for the timing signal */
         sa.sa_flags             = SA_SIGINFO;
         sa.sa_sigaction         = Menu_Signal_Action_Handler;
         sigemptyset( &sa.sa_mask );
         if ( sigaction( MENU_TIMER_SIG, &sa, NULL ) == -1 )
         { error_code = -EC_DEMO_MENU_TIMER_SIGACTION;   goto Menu_Periodic_Run_Error;   }
         mtd = &(menu_timer_info);
         if ( NULL != mtd->timer_id )
         { error_code = -EC_DEMO_MENU_TIMER_ACTIVE;              goto Menu_Periodic_Run_Error;   }
         if ( time_sec < 0.001 )
         { error_code = -EC_DEMO_MENU_TIMER_INFO_INVALID;  goto Menu_Periodic_Run_Error; }
         if ( NULL == loop_function )
         { error_code = -EC_DEMO_MENU_TIMER_INFO_INVALID;  goto Menu_Periodic_Run_Error; }
         if ( NULL == stop_request_function )
         { error_code = -EC_DEMO_MENU_TIMER_INFO_INVALID;  goto Menu_Periodic_Run_Error; }
         mtd->loop_function                      = loop_function;
         mtd->stop_request_function      = stop_request_function;
         mtd->private_data                       = private_data;
         se.sigev_notify = SIGEV_SIGNAL;                 /* notify via signal    */
         se.sigev_signo  = MENU_TIMER_SIG;               /* timer signal                 */
         se.sigev_value.sival_ptr = mtd;
         ts.it_interval.tv_sec = (long int) time_sec;
         time_sec = time_sec - ( (double) ts.it_interval.tv_sec );  /* remove whole seconds */
         time_sec = time_sec * 1.0e9; /* convert to nanoseconds */
         ts.it_interval.tv_nsec = (long) time_sec;
         ts.it_value.tv_sec  = ts.it_interval.tv_sec;
         ts.it_value.tv_nsec = ts.it_interval.tv_nsec;
         /* http://man7.org/linux/man-pages/man2/timer_create.2.html */
         error_code = timer_create( CLOCK_REALTIME /* clock_id */, &se, &(mtd->timer_id) );
         if ( error_code )
         { error_code = -EC_DEMO_MENU_TIMER_CREATE;  goto Menu_Periodic_Run_Error;       }
         /* http://man7.org/linux/man-pages/man2/timer_settime.2.html */
         error_code = timer_settime( mtd->timer_id, 0, &ts, NULL );
         if ( error_code )
         { error_code = -EC_DEMO_MENU_TIMER_SETTIME;  goto Menu_Periodic_Run_Error;      }
 /*printf( "mtd->timer_id = %p\n", mtd->timer_id );*/
 Menu_Periodic_Run_Error:
         return error_code;
 }
int Menu_Quit (struct menu_command_params * p)
Definition at line 264 of file menu.c.
 {
         (void) p;
         return -EC_DEMO_MENU_QUIT;
 }
int Menu_Redraw (struct menu_command_params * p)
Definition at line 297 of file menu.c.
References menu_command_params::board, menu_command_params::info, Menu_Display(), and menu_command_params::out_file.
 {
         Menu_Display( menu_menu_list, p->board, p->out_file, p->info );
         return SUCCESS;
 }
int Menu_Report_Console (struct menu_command_params * p)
Definition at line 291 of file menu.c.
References menu_command_params::board, menu_command_params::out_file, and STX104_Report_Full().
 {
         STX104_Report_Full( p->board, p->out_file );
         return SUCCESS;
 }
int Menu_Report_File (struct menu_command_params * p)
Definition at line 270 of file menu.c.
References menu_command_params::board, and STX104_Report_Full().
 {
         FILE * report_file;
 #ifdef __BORLANDC__
 #elif _WIN32
         int  error_code;
 #endif
 #ifdef __BORLANDC__
         report_file = fopen( "report.txt", "wt" );
 #elif _WIN32
         error_code = fopen_s( &report_file, "report.txt", "wt" );
 #else
         report_file = fopen( "report.txt", "wt" );
 #endif
         STX104_Report_Full( p->board, report_file );
         /* close the file */
         fclose( report_file );
         return SUCCESS;
 }
void Menu_Termination (void)
Definition at line 853 of file menu.c.
 {
 #if __linux__
 /*      Menu_Keyboard_Terminate();*/
 #endif
         menu_menu_list = NULL;
 }