Demo STX104 Simple: stx104_simple.c File Reference
stx104_simple.c File Reference
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <memory.h>
#include <time.h>
#include "../aul_tree/aul/aul_public.h"
#include "../aul_tree/demo_shared/cfgrprt.h"
#include "../aul_tree/demo_shared/config.h"
#include "../aul_tree/demo_shared/menu.h"
#include "../aul_tree/demo_shared/demo_stx104_shared.h"
Macros
#define STX104_SIMPLE_REV "$Date: 2015-01-12 14:07:46 -0600 (Mon, 12 Jan 2015) $"
#define STX104_SIMPLE_DEBUG_MESSAGE _DEBUG
#define TIMER_PARAMETERS_IMPROVE_DYNAMIC_RANGE 1
#define MENU_UPDATE_TIME_MS 100
#define AI_FRAME_TIME_SEC 0.5
#define MENU_MAIN_LOOP_USE_TIMER_RATHER_THAN_SLEEP_DELAYS_IMPROVED_TIMING 1
#define DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE 1
#define STX104_SIMPLE_REV "$Date: 2015-01-12 14:07:46 -0600 (Mon, 12 Jan 2015) $"
#define AI_BUFFER_SIZE 256
#define STX104_SIMPLE_TEMP_STR_SIZE 4
#define STX104_SIMPLE_TEMP_STR_SIZE 16
Functions
void STX104_Simple_Menu_AI_Data_Readout (struct demo_stx104_data *ds)
Reads the data from the hardware and deposits into ai_buffer. In this case we just dump all but the last value; one could perform an average.
int STX104_Simple_Configuration (char *prefix, struct demo_stx104_data *ds)
Commits the initial configuration information to the library and then onto the hardware.
static int STX104_Simple_Menu_AI_Hex (struct menu_command_params *p)
Set analog input (AI) to display values in hexadecimal value. This function is referenced in stx104_simple_menu_list[] array.
static int STX104_Simple_Menu_AI_Volts (struct menu_command_params *p)
Set analog input (AI) display values in uncalibrated volts. This function is referenced in the stx104_simple_menu_list[] array.
static int STX104_Simple_Menu_AI_Channel_Set (struct menu_command_params *p)
Sets the analog input (AI) channel that we wish to observe on the status line.
static int STX104_Simple_Data_AI_Channel (struct menu_data_params *mdp)
Display the analog input (AI) channel that is currently selected.
static int STX104_Simple_Data_AI_Value (struct menu_data_params *mdp)
int STX104_Simple_Main_Stop_Request (void *private_data)
int STX104_Simple_Main_Loop (void *private_data)
int main (int argc, char *argv[])
Variables
static struct demo_stx104_data demo_stx104_data
static struct menu_command stx104_simple_menu_list []
Menu structure or list.
static struct menu_data stx104_simple_data_list []
Detailed Description
STX104 low speed demonstration
POSIX.1b RealTime Extensions Library
The librt.s library to support High Resolution POSIX Timers (HRT) is added to the linker. The following functions are a part of this library: timer_create(), timer_settime(), timer_delete().
Location of library: ./usr/lib/i386-linux-gnu/librt.a
The library is used by the menu.c file. Please search for "librt.a".
Ubuntu: apt-get install build-essential http://askubuntu.com/questions/398489/how-to-install-build-essential
yum install glibc-static
Definition in file stx104_simple.c.
Macro Definition Documentation
#define AI_BUFFER_SIZE 256
Referenced by STX104_Simple_Menu_AI_Data_Readout().
#define AI_FRAME_TIME_SEC 0.5
CUSTOMER_TODO:
Analog input frame timer, value is in nano-seconds
NOTES:
if set too fast, it will be stuck in Menu_AI_uint16_t_Get(). This example code is intended for low analog input data rates.
The driver software will internally compute the correct sample rate to an accuracy of +/-25nS.
Definition at line 260 of file stx104_simple.c.
Referenced by STX104_Simple_Configuration().
#define DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE 1
CUSTOMER_TODO:
Comment out to not toggle DOUT3 each time we write data to a file. If there is no data to write, then do not toggle.
If uncommented, then DOUT3 (J7.5) will be toggled each time analog input data is written to a file.
Definition at line 285 of file stx104_simple.c.
#define MENU_MAIN_LOOP_USE_TIMER_RATHER_THAN_SLEEP_DELAYS_IMPROVED_TIMING 1
CUSTOMER_TODO:
Comment out to simply revert to usleep() delays rather than using menu interval timer mechanism based on signals.
Definition at line 273 of file stx104_simple.c.
#define MENU_UPDATE_TIME_MS 100
CUSTOMER_TODO:
Roughly the rate in milliseconds that the menu will be updated. Typically, 100mS is about the right value for low speed applications.
NOTE: Your mileage will vary. In other words, depending on CPU, hardware, and your application.
Definition at line 245 of file stx104_simple.c.
Referenced by main().
#define STX104_SIMPLE_DEBUG_MESSAGE _DEBUG
CUSTOMER_TODO:
Enable/Disable debug print messages NOTE: also STX104_CONFIG_DEBUG_MESSAGE in "../demo_shared/config.h".
Definition at line 204 of file stx104_simple.c.
#define STX104_SIMPLE_REV "$Date: 2015-01-12 14:07:46 -0600 (Mon, 12 Jan 2015) $"
Definition at line 299 of file stx104_simple.c.
#define STX104_SIMPLE_REV "$Date: 2015-01-12 14:07:46 -0600 (Mon, 12 Jan 2015) $"
Definition at line 299 of file stx104_simple.c.
#define STX104_SIMPLE_TEMP_STR_SIZE 4
Referenced by STX104_Simple_Data_AI_Channel(), and STX104_Simple_Data_AI_Value().
#define STX104_SIMPLE_TEMP_STR_SIZE 16
#define TIMER_PARAMETERS_IMPROVE_DYNAMIC_RANGE 1
CUSTOMER_TODO:
If enabled this will use the improved timing parameters dynamic range and is the newer preferred method. Timing parameters are passed as doubles rather than the UINT32. It is sometimes easier to express in floating point than in integer values.
Definition at line 233 of file stx104_simple.c.
Function Documentation
int main (int argc, char * argv[])
Parameters
argc not currently used
argv not currently used
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 857 of file stx104_simple.c.
References AUL_Error_String(), demo_stx104_data::board, demo_stx104_data, Demo_STX104_Initialize(), Demo_STX104_Main_Loop_Timing_Calculations(), Demo_STX104_Terminate(), demo_stx104_data::in_file, demo_stx104_data::main_loop_time_sec, Menu_Display(), Menu_Initialization(), Menu_Periodic_Run(), MENU_UPDATE_TIME_MS, demo_stx104_data::out_file, demo_stx104_data::quit_request, STX104_Simple_Configuration(), STX104_Simple_Main_Loop(), and STX104_Simple_Main_Stop_Request().
 {
         int                                             error_code;
         int                                             board;
         FILE *                                          out_file;
         /*FILE *                                                in_file;*/
         struct demo_stx104_data *       ds;
         char                                            prefix[] = "  ";
         ds = &demo_stx104_data;
         /**** initialize global variables shared ****/
         memset( ds, 0, sizeof( struct demo_stx104_data ) );
         ds->in_file  = stdin;
         ds->out_file = stdout;
         /* local file settings -- short hand */
         out_file = ds->out_file;
         /*in_file  = ds->in_file;*/
         fprintf( out_file, "Main: begin:\n" );
         /***** initialize driver and board software interface *****/
         error_code = Demo_STX104_Initialize( prefix,   /* output string prefix string  */
                                                                                  argc,     /* command line arguments count */
                                                                                  argv,     /* command line arguments list  */
                                                                                  &demo_stx104_data       /* data */
                                                                        );
         if ( error_code ) goto Main_Error;
         fprintf( out_file, "Main: Demo_STX104_Initialize() complete\n" );
         board = ds->board;  /* short hand */
         /***** menu timing calculations *****/
         error_code = Demo_STX104_Main_Loop_Timing_Calculations( MENU_UPDATE_TIME_MS, ds );
         if ( error_code ) goto Main_Error;
         /***** stx104 board level configuration *****/
         error_code = STX104_Simple_Configuration( prefix, &demo_stx104_data );
         if ( error_code ) goto Main_Error;
         fprintf( out_file, "Main: STX104_Simple_Configuration() complete\n" );
         /***** menu initialization *****/
         Menu_Initialization( stx104_simple_menu_list );
         /***** Main loop here *****/
         fprintf( out_file, "Main: process loop begin\n\n" );
         Menu_Display( stx104_simple_menu_list, board, out_file, ds );
 #if MENU_MAIN_LOOP_USE_TIMER_RATHER_THAN_SLEEP_DELAYS_IMPROVED_TIMING == 1
         error_code = Menu_Periodic_Run( ds->main_loop_time_sec,
                                                                         STX104_Simple_Main_Loop,
                                                                         STX104_Simple_Main_Stop_Request,
                                                                         ds
                                                                   );
         while(1)
         {
                 if ( true == ds->quit_request ) break;
                 /* keeps cpu available */
                 usleep(1);
         }
 #else
         do
         {  /* process any incoming menu commands */
                 error_code = STX104_Simple_Main_Loop( ds );
         } while ( !error_code );
 #endif
         fprintf( out_file, "\n\nMain: process loop end\n" );
 Main_Error:
         if ( error_code < 0 ) error_code = -error_code;
         if ( error_code )
         {
         printf( "Application Test: exit fail, error_code = %d, %s.\n", error_code, AUL_Error_String( error_code ) );
         }
         Demo_STX104_Terminate( prefix,                  /* output string prefix string  */
                                                ds               /* data */
                                          );
         return -error_code;
 }
int STX104_Simple_Configuration (char * prefix, struct demo_stx104_data * ds)
Commits the initial configuration information to the library and then onto the hardware.
Parameters
prefix A string prefix used in reporting any errors. Typically, it is spaces to get proper indent which is purely to improve readability of the output.
ds DataSet. See demo_stx104_data for further details.
Returns
If successful, returns SUCCESS (0), otherwise an error-code.
Definition at line 416 of file stx104_simple.c.
References stx104_configuration::ai_cfg, AI_FRAME_TIME_SEC, demo_stx104_data::board, demo_stx104_data::cfg, stx104_configuration::di_cfg, stx104_configuration::int_cfg, stx104_configuration::name_interrupt_callback_a, stx104_configuration::name_interrupt_data_set_a, demo_stx104_data::out_file, STX104_Config_Clear(), STX104_Config_Commit(), STX104_Config_Initialize(), and stx104_configuration::trg_cfg.
Referenced by main().
 {
         int                                                     error_code;
         struct stx104_configuration *   cfg;
         FILE *                                                  out_file;
         int                                                             board;
         cfg      = &(ds->cfg);  /* short hand */
         out_file = ds->out_file; /* short hand */
         board    = ds->board;    /* short hand */
         /**** clear the configuration table ****/
         STX104_Config_Clear( cfg );
         /**** initialize interrupts and triggers ****/
         error_code = STX104_Config_Initialize( board, prefix, out_file, cfg );
         if ( SUCCESS != error_code ) return (int) error_code;
         /*********************************************************************/
         /**** set our configuration parameters here for this application  ****/
         /****  Analog Input (AI) configuration ****/
 #ifdef TIMER_PARAMETERS_IMPROVE_DYNAMIC_RANGE
         cfg->ai_cfg.burst_timer_sec = 5000e-9; /* nS */
         cfg->ai_cfg.frame_timer_sec = AI_FRAME_TIME_SEC;
 #else
         cfg->ai_cfg.burst_timer_ns = 5000; /* nS */
         cfg->ai_cfg.frame_timer_ns = AI_FRAME_TIME_NS;
 #endif
         cfg->ai_cfg.strobe_source  = AISS_AI_FRAME_TIMER;
         cfg->ai_cfg.first_channel  = STX104_AI_CH0;
         cfg->ai_cfg.last_channel   = cfg->ai_cfg.first_channel;
         //   ai_cfg.last_channel   = 100; // blatant error test!
         cfg->ai_cfg.use_triggering_subsystem = false;
         /****  Digital Input (DI) configuration ****/
         cfg->di_cfg.swap_din1_and_din3 = true;
         /****  Digital Output (DO) configuration ****/
         // nothing to do here -- we are going to just use a cleared data set.
         /****  Triggering (Trg) configuration ****/
         cfg->trg_cfg.enabled           = true;
         cfg->trg_cfg.start_mode        = STM_IMMEDIATE;
         cfg->trg_cfg.start_sync_source = TSS_NONE;
         cfg->trg_cfg.start_source      = STS_SOFTWARE_STROBE; /* start via software */
         cfg->trg_cfg.stop_source       = ETS_SOFTWARE_STROBE; /* stop via software */
 #ifdef TIMER_PARAMETERS_IMPROVE_DYNAMIC_RANGE
         cfg->trg_cfg.delay_sec = 15025e-9; /* nS */
 #else
         cfg->trg_cfg.delay_ns = 15025;
 #endif
         /****  Interrupts (Int) configuration ****/
 #if defined( STX104_SIMPLE_USE_INTERRUPTS )
         cfg->int_cfg.callback_source_a      = (AUL_INT_CALLBACK) CallBack_Source_A;
         cfg->int_cfg.callback_source_a_user_dataset = (void * ) ds;
         cfg->int_cfg.source_a               = ISA_THRESHOLD_COUNTER;
         cfg->int_cfg.threshold              = 10;
         cfg->int_cfg.threshold_source       = ITS_AI_FRAME;
         cfg->name_interrupt_callback_a      = stx104_simple_interrupt_handler_name;
         cfg->name_interrupt_data_set_a      = stx104_simple_interrupt_data_set_name;
 #else
 #endif
         /****  commit the configuration ****/
    error_code = STX104_Config_Commit( board, prefix, out_file, cfg );
    if ( SUCCESS != error_code ) return (int) error_code;
    return SUCCESS;
 }
static int STX104_Simple_Data_AI_Channel (struct menu_data_params * mdp) static
Display the analog input (AI) channel that is currently selected.
Parameters
mdp See menu_data_params for details.
Returns
Always returns SUCCESS (0)
Definition at line 662 of file stx104_simple.c.
References stx104_configuration::ai_cfg, demo_stx104_data::cfg, menu_data_params::info, Menu_Data_Append(), and STX104_SIMPLE_TEMP_STR_SIZE.
 {
         struct demo_stx104_data *                       ds;
         struct stx104_ai_cfg *                          ai_cfg;
 #define STX104_SIMPLE_TEMP_STR_SIZE  4
         char                                                            tmp_str[STX104_SIMPLE_TEMP_STR_SIZE];
         ds = (struct demo_stx104_data *) mdp->info;
         ai_cfg = &(ds->cfg.ai_cfg);
 #ifdef __BORLANDC__
         sprintf( tmp_str, "%02d", ai_cfg->first_channel );
 #else
         snprintf( tmp_str, STX104_SIMPLE_TEMP_STR_SIZE, "%02d", ai_cfg->first_channel );
 #endif
         Menu_Data_Append( mdp, tmp_str );
         return SUCCESS;
 #undef STX104_SIMPLE_TEMP_STR_SIZE
 }
static int STX104_Simple_Data_AI_Value (struct menu_data_params * mdp) static
Parameters
mdp See menu_data_params for details.
Returns
Always returns SUCCESS (0)
Definition at line 686 of file stx104_simple.c.
References demo_stx104_data::board, menu_data_params::info, demo_stx104_data::interrupt_blocking, demo_stx104_data::menu_ai_voltage_value, Menu_Data_Append(), STX104_Simple_Menu_AI_Data_Readout(), STX104_SIMPLE_TEMP_STR_SIZE, demo_stx104_data::value_raw, and demo_stx104_data::voltage_uncalibrated.
 {
         struct demo_stx104_data *                       ds;
 #define STX104_SIMPLE_TEMP_STR_SIZE  16
         char                                                            tmp_str[STX104_SIMPLE_TEMP_STR_SIZE];
         ds = (struct demo_stx104_data *) mdp->info;
         /****  Update analog input data - if interrupts, then automatic ****/
 #if defined( STX104_SIMPLE_USE_INTERRUPTS )
         while ( ds->interrupt_blocking ) {}; //wait for interrupt to complete.
 #else
         STX104_Simple_Menu_AI_Data_Readout( ds );
 #endif
         //if ( data_set->frames_have_been_read )  //other implementations may require this test!
         //{
         if ( ds->menu_ai_voltage_value )
         {
                 STX104_AI_Raw_To_Volts( ds->board, ds->value_raw, &(ds->voltage_uncalibrated) );
 #ifdef __BORLANDC__
         sprintf( tmp_str, "% 2.4f  ", data_set->voltage_uncalibrated );
 #else
         snprintf( tmp_str, STX104_SIMPLE_TEMP_STR_SIZE, "% 2.4f  ", ds->voltage_uncalibrated );
 #endif
         }
         else
         {
 #ifdef __BORLANDC__
         sprintf( tmp_str, "0x%04X  ", data_set->value_raw );
 #else
         snprintf( tmp_str, STX104_SIMPLE_TEMP_STR_SIZE, "0x%04X  ", ds->value_raw );
 #endif
         }
         //}
         Menu_Data_Append( mdp, tmp_str );
         return SUCCESS;
 #undef STX104_SIMPLE_TEMP_STR_SIZE
 }
int STX104_Simple_Main_Loop (void * private_data)
Parameters
private_data
Returns
Definition at line 791 of file stx104_simple.c.
References demo_stx104_data::board, demo_stx104_data::dout3_state, demo_stx104_data::in_file, Menu_Command(), Menu_Data(), and demo_stx104_data::out_file.
Referenced by main().
 {
         int                                             error_code;
         int                                             board;
         FILE *                                          out_file;
         FILE *                                          in_file;
         struct demo_stx104_data *       ds;
         ds = (struct demo_stx104_data *) private_data;
         out_file= ds->out_file;
         in_file = ds->in_file;
         board   = ds->board;
  #if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
                 ds->dout3_state = !ds->dout3_state;
                 STX104_DO_Set( board, STX104_DO3, ds->dout3_state );
  #endif
         error_code = Menu_Command( stx104_simple_menu_list, board, in_file, out_file, ds );
         /* display status and updated information */
         Menu_Data( stx104_simple_data_list, 0, board, out_file, ds );
 #if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         ds->dout3_state = !ds->dout3_state;
         STX104_DO_Set( board, STX104_DO3, ds->dout3_state );
 #endif
         return error_code;
 }
int STX104_Simple_Main_Stop_Request (void * private_data)
Parameters
private_data
Returns
Always returns SUCCESS (0)
Definition at line 777 of file stx104_simple.c.
References demo_stx104_data::quit_request.
Referenced by main().
 {
         struct demo_stx104_data *       ds;
         ds = (struct demo_stx104_data *) private_data;
         ds->quit_request = true;
         return SUCCESS;
 }
static int STX104_Simple_Menu_AI_Channel_Set (struct menu_command_params * p) static
Sets the analog input (AI) channel that we wish to observe on the status line.
Parameters
p See menu_command_params for details.
Returns
Always returns SUCCESS (0) since the parameter is not likely to be out of range.
Definition at line 543 of file stx104_simple.c.
References stx104_configuration::ai_cfg, demo_stx104_data::board, menu_command_params::board, demo_stx104_data::cfg, menu_command_params::channel, and menu_command_params::info.
 {
         int                                             error_code;
         stx104_ai_cfg_type *            ai_cfg;
         struct demo_stx104_data *       ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         ai_cfg = &(ds->cfg.ai_cfg);
         STX104_AI_CFG_Get( p->board, ai_cfg );
         ai_cfg->first_channel = (STX104_AI_ENUM) p->channel;
         ai_cfg->last_channel  = (STX104_AI_ENUM) p->channel;
         error_code = STX104_AI_CFG_Set( ds->board, ai_cfg );
         return error_code;
 }
void STX104_Simple_Menu_AI_Data_Readout (struct demo_stx104_data * ds)
Reads the data from the hardware and deposits into ai_buffer. In this case we just dump all but the last value; one could perform an average.
It assumes that all the data comes from a single channel. In this example, that is indeed the case.
It updates the total number of hardware frames actually read.
Parameters
ds DataSet. All of the STX104 configuration and control information.
Definition at line 327 of file stx104_simple.c.
References AI_BUFFER_SIZE, demo_stx104_data::board, demo_stx104_data::fifo_full_error, demo_stx104_data::frames_have_been_read, demo_stx104_data::software_frame_count, and demo_stx104_data::value_raw.
Referenced by STX104_Simple_Data_AI_Value().
 {
         int             error_code;
         int             board;
         BOOL            data_available;
         uint16_t        frame_count_actual;
 #define AI_BUFFER_SIZE  256
         uint16_t        ai_buffer[AI_BUFFER_SIZE];
         ds->fifo_full_error             = false;
         ds->frames_have_been_read       = false;
         board                           = ds->board;
         frame_count_actual      = 0;
         data_available          = false;
         do {
                 error_code = STX104_AI_Frames_Get( board, &ai_buffer[0], &frame_count_actual, AI_BUFFER_SIZE );
                 if ( EC_STX104_AI_FIFO_FULL == error_code )
                 {
                         ds->fifo_full_error = true;
                         frame_count_actual = 0;
                 }
                 else
                 {
                         ds->fifo_full_error = false;
                 }
                 if ( frame_count_actual )
                 {
                         ds->software_frame_count += (uint32_t)frame_count_actual;
                         /* Here, we are dumping all but the last sample retrieved.  One could
                            average the data or store to a file.
                         */
                         ds->value_raw = ai_buffer[frame_count_actual - 1];
                         data_available = true;
                 }
         } while ( frame_count_actual );
         ds->frames_have_been_read = data_available;
 #undef AI_BUFFER_SIZE
 }
static int STX104_Simple_Menu_AI_Hex (struct menu_command_params * p) static
Set analog input (AI) to display values in hexadecimal value. This function is referenced in stx104_simple_menu_list[] array.
Parameters
p See menu_command_params for details, see menu.h.
Returns
Always returns SUCCESS (0)
Definition at line 514 of file stx104_simple.c.
References menu_command_params::info, and demo_stx104_data::menu_ai_voltage_value.
 {
         struct demo_stx104_data * ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         ds->menu_ai_voltage_value = false;
         return SUCCESS;
 }
static int STX104_Simple_Menu_AI_Volts (struct menu_command_params * p) static
Set analog input (AI) display values in uncalibrated volts. This function is referenced in the stx104_simple_menu_list[] array.
Parameters
p See menu_command_params for details.
Returns
Always returns SUCCESS (0)
Definition at line 528 of file stx104_simple.c.
References menu_command_params::info, and demo_stx104_data::menu_ai_voltage_value.
 {
         struct demo_stx104_data * ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         ds->menu_ai_voltage_value = true;
         return SUCCESS;
 }
Variable Documentation
struct demo_stx104_data demo_stx104_data static
Definition at line 302 of file stx104_simple.c.
Referenced by main().
struct menu_data stx104_simple_data_list[] static
Initial value:
=
{
        {       0,                      0,              Demo_STX104_Data_Timer_Tick,      0,                            NULL                    },
        {       5,                      0,              Demo_STX104_Data_DI,                      3,                            "DI:"                   },
        {  13,                  0,              Demo_STX104_Data_Config_AI,               3,                            "AI:"                   },
        {  31,                  0,              STX104_Simple_Data_AI_Channel,    2,                            "CH"                    },
        {  35,                  0,              STX104_Simple_Data_AI_Value,      2,                            ": "                    },
        {  48,                  0,              STX104_Data_Frames,                               3,                            "FR:"                   },
        {       0,                      0,              NULL,                                                     0,                            NULL                    }
}
TODO
Definition at line 745 of file stx104_simple.c.
static struct menu_command stx104_simple_menu_list static
Menu structure or list.
The underlying menu processing is performed via menu.c functions. The menu was implemented in this fashion for flexibility which is reused for other demonstration code. It also removes a lot of clutter from the demo source files.
Note that each of the functions used within this list must handle a single pointer to a menu_command_params data structure.
Definition at line 505 of file stx104_simple.c.