Demo STX104 Fast: stx104_fast.c File Reference
stx104_fast.c File Reference
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <memory.h>
#include <time.h>
#include "../aul_tree/aul/aul_public.h"
#include "../aul_tree/demo_shared/cfgrprt.h"
#include "../aul_tree/demo_shared/config.h"
#include "../aul_tree/demo_shared/menu.h"
#include "../aul_tree/demo_shared/demo_stx104_shared.h"
Macros
#define STX104_FAST_REV "$Date: 2014-05-06 17:06:00 -0500 (Tue, 06 May 2014) $"
#define STX104_FAST_DEBUG_MESSAGE _DEBUG
#define DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE 1
#define CONVERT_STRAIGHT_BINARY_TO_TWOS_COMPLEMENT 1
#define MENU_UPDATE_TIME_MS 100 /* mS */
#define FILE_OUTPUT_RATE_HZ (((double) 1000) / ((double) MENU_UPDATE_TIME_MS))
#define AI_FRAME_TIME_NS 20000
#define MENU_MAIN_LOOP_USE_TIMER_RATHER_THAN_SLEEP_DELAYS_IMPROVED_TIMING 1
#define AI_FIRST_CHANNEL 0
#define AI_LAST_CHANNEL 3
#define FIFO_LOG_DATA_AVAILABLE 1
#define AI_MAXIMUM_SAMPLE_BUFFER_SIZE (32768 * 2 - 2)
#define LOCAL_STRING_BUFFER_SIZE 128
#define FILE_NAME_SIZE 256
#define STX104_FAST_CONFIG_FROM_HARDWARE 1
#define STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE 0
Functions
void CallBack_Source_A (void *result)
static void STX104_Fast_Process_Start_Configuration (struct demo_stx104_data *ds)
void STX104_Fast_Process_Stop_Request (struct demo_stx104_data *ds)
static void STX104_Fast_FIFO_Log (struct demo_stx104_data *ds)
static int STX104_Fast_Process_Data (struct demo_stx104_data *ds)
static void Static_Fast_CallBack_Source_A (void *result)
static int64_t STX104_Fast_Time_Delta (struct timespec *ts_start, struct timespec *ts_end)
static int STX104_Fast_Process_Start_Report (struct demo_stx104_data *ds)
static int STX104_Fast_Process_Start (struct demo_stx104_data *ds)
static void STX104_Fast_Process_Stop_Report (struct demo_stx104_data *ds)
void STX104_Fast_Process_Stop (struct demo_stx104_data *ds)
static int STX104_Fast_Menu_Trigger_Start (struct menu_command_params *p)
static int STX104_Fast_Menu_Trigger_Stop (struct menu_command_params *p)
static int STX104_Fast_Menu_Convert_FIFO_Log_File_To_CSV (struct menu_command_params *p)
static int STX104_Fast_Menu_Convert_Data_File_To_CSV (struct menu_command_params *p)
int STX104_Fast_Main_Stop_Request (void *private_data)
int STX104_Fast_Main_Loop (void *private_data)
int main (int argc, char *argv[])
Variables
uint16_t ai_buffer [AI_MAXIMUM_SAMPLE_BUFFER_SIZE]
static struct demo_stx104_data demo_stx104_data
static struct menu_command stx104_fast_menu_list []
Menu structure or list.
static struct menu_data stx104_fast_data_list []
Detailed Description
STX104 any speed demonstration
Definition in file stx104_fast.c.
Macro Definition Documentation
#define AI_FIRST_CHANNEL 0
CUSTOMER_TODO:
Set the first and last analog input channels to be scanned.
Definition at line 338 of file stx104_fast.c.
Referenced by STX104_Fast_Menu_Convert_Data_File_To_CSV(), STX104_Fast_Process_Start_Configuration(), and STX104_Fast_Process_Start_Report().
#define AI_FRAME_TIME_NS 20000
Definition at line 309 of file stx104_fast.c.
Referenced by STX104_Fast_Process_Start_Configuration(), and STX104_Fast_Process_Start_Report().
#define AI_LAST_CHANNEL 3
Definition at line 339 of file stx104_fast.c.
Referenced by STX104_Fast_Menu_Convert_Data_File_To_CSV(), STX104_Fast_Process_Start_Configuration(), and STX104_Fast_Process_Start_Report().
#define AI_MAXIMUM_SAMPLE_BUFFER_SIZE (32768 * 2 - 2)
Definition at line 359 of file stx104_fast.c.
Referenced by STX104_Fast_Process_Start_Report().
#define CONVERT_STRAIGHT_BINARY_TO_TWOS_COMPLEMENT 1
CUSTOMER_TODO:
If you are using audacity to view binary files, uncomment this macro in order to obtain twos complement data.
Definition at line 268 of file stx104_fast.c.
#define DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE 1
Definition at line 238 of file stx104_fast.c.
#define FIFO_LOG_DATA_AVAILABLE 1
CUSTOMER_TODO:
Uncomment to enable logging of FIFO statistics.
Definition at line 348 of file stx104_fast.c.
Referenced by Static_Fast_CallBack_Source_A().
#define FILE_NAME_SIZE 256
Definition at line 373 of file stx104_fast.c.
Referenced by STX104_Fast_Menu_Convert_FIFO_Log_File_To_CSV().
#define FILE_OUTPUT_RATE_HZ (((double) 1000) / ((double) MENU_UPDATE_TIME_MS))
Definition at line 291 of file stx104_fast.c.
Referenced by STX104_Fast_Process_Start_Report().
#define LOCAL_STRING_BUFFER_SIZE 128
Definition at line 372 of file stx104_fast.c.
Referenced by STX104_Fast_Menu_Convert_Data_File_To_CSV().
#define MENU_MAIN_LOOP_USE_TIMER_RATHER_THAN_SLEEP_DELAYS_IMPROVED_TIMING 1
CUSTOMER_TODO:
Comment out to simply revert to usleep() delays rather than using menu interval timer mechanism based on signals.
Definition at line 329 of file stx104_fast.c.
#define MENU_UPDATE_TIME_MS 100 /* mS */
CUSTOMER_TODO:
Roughly the rate in milliseconds that the menu will be updated. Typically, 100mS is about the right value for low speed applications.
This also sets the readout rate of the analog input FIFO (i.e. STX104_AI_Frames_Get()).
NOTE: Your mileage will vary. In other words, depending on CPU, hardware, and your application.
Definition at line 283 of file stx104_fast.c.
Referenced by main().
#define STX104_FAST_CONFIG_FROM_HARDWARE 1
Definition at line 599 of file stx104_fast.c.
#define STX104_FAST_DEBUG_MESSAGE _DEBUG
CUSTOMER_TODO:
Enable/Disable debug print messages NOTE: also STX104_CONFIG_DEBUG_MESSAGE in "../demo_shared/config.h".
Definition at line 233 of file stx104_fast.c.
#define STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE 0
#define STX104_FAST_REV "$Date: 2014-05-06 17:06:00 -0500 (Tue, 06 May 2014) $"
Definition at line 217 of file stx104_fast.c.
Function Documentation
void CallBack_Source_A (void * result)
int main (int argc, char * argv[])
Parameters
argc not currently used
argv not currently used
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 1280 of file stx104_fast.c.
References AUL_Error_String(), demo_stx104_data::board, demo_stx104_data, Demo_STX104_Initialize(), Demo_STX104_Main_Loop_Timing_Calculations(), Demo_STX104_Terminate(), demo_stx104_data::in_file, demo_stx104_data::main_loop_time_sec, Menu_Display(), Menu_Initialization(), Menu_Periodic_Run(), MENU_UPDATE_TIME_MS, demo_stx104_data::out_file, demo_stx104_data::quit_request, STX104_Fast_Main_Loop(), STX104_Fast_Main_Stop_Request(), and STX104_Fast_Process_Stop().
 {
         int                                             error_code;
         int                                             board;
         FILE *                                          out_file;
         /*FILE *                                        in_file;*/
         struct demo_stx104_data *       ds;
         char                                            prefix[] = "  ";
         ds = &demo_stx104_data;
         /**** initialize global variables shared ****/
         memset( ds, 0, sizeof( struct demo_stx104_data ) );
         ds->in_file  = stdin;
         ds->out_file = stdout;
         /* local file settings -- short hand */
         out_file = ds->out_file;
         /*in_file  = ds->in_file;*/
         fprintf( out_file, "Main: begin:\n" );
         /***** initialize driver and board software interface *****/
         error_code = Demo_STX104_Initialize( prefix,   /* output string prefix string  */
                                                                                  argc,     /* command line arguments count */
                                                                                  argv,     /* command line arguments list  */
                                                                                  &demo_stx104_data       /* data */
                                                                        );
         if ( error_code ) goto Main_Error;
         fprintf( out_file, "Main: Demo_STX104_Initialize() complete\n" );
         board = ds->board;  /* short hand */
         /***** menu timing calculations *****/
         error_code = Demo_STX104_Main_Loop_Timing_Calculations( MENU_UPDATE_TIME_MS, ds );
         if ( error_code ) goto Main_Error;
         /***** stx104 board level configuration *****/
 /* TODO:        error_code = STX104_Fast_Configuration( prefix, &demo_stx104_data );
         if ( error_code ) goto Main_Error;
         fprintf( out_file, "Main: STX104_Fast_Configuration() complete\n" );
 */
         /***** menu initialization *****/
         Menu_Initialization( stx104_fast_menu_list );
         /***** Main loop here *****/
         fprintf( out_file, "Main: process loop begin\n\n" );
         Menu_Display( stx104_fast_menu_list, board, out_file, ds );
 #if MENU_MAIN_LOOP_USE_TIMER_RATHER_THAN_SLEEP_DELAYS_IMPROVED_TIMING == 1
         error_code = Menu_Periodic_Run( ds->main_loop_time_sec,
                                                                         STX104_Fast_Main_Loop,
                                                                         STX104_Fast_Main_Stop_Request,
                                                                         ds
                                                                   );
         while(1)
         {
                 if ( true == ds->quit_request )
                 {
                         STX104_Fast_Process_Stop( ds );
                         break;
                 }
                 /* keeps cpu available */
                 usleep(1);
         }
 #else
         do
         {  /* process any incoming menu commands */
                 error_code = STX104_Fast_Main_Loop( ds );
         } while ( !error_code );
 #endif
         STX104_Fast_Process_Stop( ds );
         if ( error_code ) goto Main_Error;
         fprintf( out_file, "\n\nMain: process loop end\n" );
 Main_Error:
         if ( error_code < 0 ) error_code = -error_code;
         if ( error_code )
         {
         printf( "Application Test: exit fail, error_code = %d, %s.\n", error_code, AUL_Error_String( error_code ) );
         }
         Demo_STX104_Terminate( prefix,                  /* output string prefix string  */
                                                ds               /* data */
                                          );
         return -error_code;
 }
static void Static_Fast_CallBack_Source_A (void * result) static
Definition at line 521 of file stx104_fast.c.
References ai_buffer, demo_stx104_data::board, demo_stx104_data::data_output_file, demo_stx104_data::dout3_state, demo_stx104_data::fifo_full_error, FIFO_LOG_DATA_AVAILABLE, demo_stx104_data::frame_quantity_request_per_write_cycle, demo_stx104_data::frame_size_in_bytes, STX104_Fast_FIFO_Log(), and STX104_Fast_Process_Stop_Request().
Referenced by STX104_Fast_Process_Start_Configuration().
 {
         STX104_INT_RESULT_TYPE*         event_result;
         uint16_t                                        frame_count_actual;
         int                                                     error_code;
         int                                                     board;
         struct demo_stx104_data *       ds;
         event_result = (STX104_INT_RESULT_TYPE*) result;
         ds = ( struct demo_stx104_data * ) event_result->user_defined_dataset;
         board = event_result->board;
 #if defined( FIFO_LOG_DATA_AVAILABLE )
         /* log fifo activity */
         STX104_Fast_FIFO_Log( ds );
 #endif
 #if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
                 ds->dout3_state = !ds->dout3_state;
                 STX104_DO_Set( board, STX104_DO3, ds->dout3_state );
 #endif
         error_code = STX104_AI_Frames_Get(      board,                           /* board descriptor */
                                                                                 &ai_buffer[0],       /* starting position of the destination buffer */
                                                                                 &frame_count_actual, /* actual frames that are copied to the buffer */
                                                                                 ds->frame_quantity_request_per_write_cycle /* frames requested */
                                                                         );
         if ( error_code )
         {  /* Don't bother to write anything because at this point we
                         now have data loss, better to restart.
                 */
                 STX104_Int_Enable_Set( board, false );
                 STX104_Trg_Software_Stop( board );
                 /*TODO fprintf( out_file, "\n\nCallBack_Source_A: FIFO full error: " );*/
                 /*TODO fprintf( out_file, "terminating file write due to data loss.\n" );*/
                 ds->fifo_full_error = true;
                 frame_count_actual = 0;
                 STX104_Fast_Process_Stop_Request( ds );;
                 return;
         }
 //printf( "event: frame_count_actual=%d\n", frame_count_actual );
         if ( frame_count_actual )
         {
                 fwrite( &ai_buffer[0],                  /* buffer to send to file */
                                 ds->frame_size_in_bytes,/* size of each frame in bytes */
                                 frame_count_actual,             /* number of frames in the buffer */
                                 ds->data_output_file    /* data file that buffer will be copied to */
                       );
         }
 #if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
                 ds->dout3_state = !ds->dout3_state;
                 STX104_DO_Set( board, STX104_DO3, ds->dout3_state );
 #endif
 }
static void STX104_Fast_FIFO_Log (struct demo_stx104_data * ds) static
Definition at line 402 of file stx104_fast.c.
References demo_stx104_data::board, and demo_stx104_data::fifo_log_file.
Referenced by Static_Fast_CallBack_Source_A(), and STX104_Fast_Process_Data().
 {
         uint32_t fifo_count;
         if ( NULL == ds->fifo_log_file ) return; /* nothing to do */
         STX104_AI_FIFO_Data_Count_Get( ds->board, &fifo_count );
         fwrite( &fifo_count, sizeof( uint32_t ), 1, ds->fifo_log_file );
 }
int STX104_Fast_Main_Loop (void * private_data)
Parameters
private_data
Returns
Definition at line 1152 of file stx104_fast.c.
References demo_stx104_data::board, demo_stx104_data::dout3_state, demo_stx104_data::in_file, Menu_Command(), Menu_Data(), demo_stx104_data::out_file, STX104_Fast_Process_Data(), and STX104_Fast_Process_Stop().
Referenced by main().
 {
         int                                             error_code;
         int                                             board;
         FILE *                                          out_file;
         FILE *                                          in_file;
         struct demo_stx104_data *       ds;
         int                                                     frame_count;  /* indicates how many frames per loop, debug use only */
         BOOL                                            dout3_state;
         ds = (struct demo_stx104_data *) private_data;
         out_file= ds->out_file;
         in_file = ds->in_file;
         board   = ds->board;
 #define STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE  0
 #if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 1;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 #endif
         error_code = Menu_Command( stx104_fast_menu_list, board, in_file, out_file, ds );
 #if STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE == 1
 # if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 0;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 # endif
 #endif
 #if STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE == 1
 # if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 1;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 # endif
 #endif
         /* display status and updated information */
         Menu_Data( stx104_fast_data_list, 0, board, out_file, ds );
 #if STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE == 1
 # if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 0;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 # endif
 #endif
 #if STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE == 1
 # if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 1;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 # endif
 #endif
  #ifndef  STX104_FAST_USE_INTERRUPTS
         /* collect more data in a non-interrupt situation */
         frame_count = STX104_Fast_Process_Data( ds );
  #endif
 #if STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE == 1
 # if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 0;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 # endif
 #endif
 #if STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE == 1
 # if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 1;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 # endif
 #endif
         STX104_Fast_Process_Stop( ds );
 #if defined( DOUT3_TOGGLE_EACH_PERIODIC_WRITE_CYCLE )
         dout3_state = 0;
         STX104_DO_Set( board, STX104_DO3, dout3_state );
 #endif
 #undef STX104_FAST_MAIN_FUNCTION_EACH_TIME_MEASURE
         return error_code;
 }
int STX104_Fast_Main_Stop_Request (void * private_data)
Parameters
private_data
Returns
Always returns SUCCESS (0)
Definition at line 1137 of file stx104_fast.c.
References demo_stx104_data::quit_request, and STX104_Fast_Process_Stop_Request().
Referenced by main().
 {
         struct demo_stx104_data *       ds;
         ds = (struct demo_stx104_data *) private_data;
         STX104_Fast_Process_Stop_Request( ds );
         ds->quit_request = true;
         return SUCCESS;
 }
static int STX104_Fast_Menu_Convert_Data_File_To_CSV (struct menu_command_params * p) static
Definition at line 941 of file stx104_fast.c.
References AI_FIRST_CHANNEL, AI_LAST_CHANNEL, demo_stx104_data::data_output_file, demo_data_file_name, demo_data_file_name_csv, Demo_STX104_Data_Timer_Tick_State(), menu_command_params::info, LOCAL_STRING_BUFFER_SIZE, and demo_stx104_data::out_file.
 {
         struct demo_stx104_data * ds;  /* data set */
         FILE *          csv_file;
         /*char          file_name[FILE_NAME_SIZE];*/
         char            out_str[LOCAL_STRING_BUFFER_SIZE];
         char            tmp_str[16];
         uint16_t        buf[16];
         long            frame_count;
         int             frame_in_bytes_size;
         int             chan;
         int             channel_max;
 #if defined( __BORLANDC__ ) || defined( __linux__ )
 #else
         errno_t  error_code;
 #endif
         ds = (struct demo_stx104_data *) p->info;
         /* open data file */
 #if defined( _WIN32 )
         error_code = fopen_s( &(ds->data_output_file), demo_data_file_name, "rb" );
 #else
         ds->data_output_file = fopen( demo_data_file_name, "rb" );
 #endif
         if ( NULL == ds->data_output_file )
         {
                 fprintf( ds->out_file, "Cannot open data output file.\n" );
                 return -EC_DEMO_MENU_QUIT;
         }
 #if defined( _WIN32 )
         error_code = fopen_s( &csv_file, demo_data_file_name_csv, "wt" );
 #else
         csv_file = fopen( demo_data_file_name_csv, "wt" );
 #endif
         if ( NULL == csv_file )
         {
                 fclose( ds->data_output_file );   ds->data_output_file = NULL;
                 fprintf( ds->out_file, "Cannot open file CSV file.\n" );
                 return -EC_DEMO_MENU_QUIT;
         }
         fprintf( ds->out_file, "\n" );
         fprintf( ds->out_file, "Data File CSV Dump:\n" );
         channel_max         = (int) ( AI_LAST_CHANNEL - AI_FIRST_CHANNEL );
         frame_in_bytes_size = (int) ( ( AI_LAST_CHANNEL - AI_FIRST_CHANNEL + 1 ) * sizeof( uint16_t /* sample data type */ ) );
         frame_count         = 0;
         /* NOTE: Excel file limit is 65535 lines */
         while( (!feof(ds->data_output_file)) && (frame_count <= 65534) )
         {
                 fread( &buf[0], frame_in_bytes_size, 1, ds->data_output_file );
                 if ( feof(ds->data_output_file) ) break;
 #if defined( _WIN32 )
                 strcpy_s( out_str, LOCAL_STRING_BUFFER_SIZE, "" );
 #else
                 strcpy( out_str, "" );
 #endif
                 for( chan=0; chan<=channel_max; chan++ )
                 {
 # if defined( _WIN32 )
                         sprintf_s( tmp_str, 16, "%u", buf[chan] );
                         strcat_s( out_str, LOCAL_STRING_BUFFER_SIZE, tmp_str );
                         if ( chan == channel_max )  strcat_s( out_str, LOCAL_STRING_BUFFER_SIZE, "\n" );
                         else                        strcat_s( out_str, LOCAL_STRING_BUFFER_SIZE, "," );
 # else
                         sprintf( tmp_str, "%u", buf[chan] );
                         strcat( out_str, tmp_str );
                         if ( chan == channel_max )  strcat( out_str, "\n" );
                         else                        strcat( out_str, "," );
 # endif
                 }
                 if ( !(frame_count % 256) )
                 {
                         fprintf( ds->out_file, "\r%c", Demo_STX104_Data_Timer_Tick_State() );
                 }
                 fwrite( &out_str[0], sizeof( char ), strlen( out_str ), csv_file );
                 frame_count++;
         }
         /* close the file */
         fclose( ds->data_output_file );  ds->data_output_file = NULL;
         fclose( csv_file );
         return SUCCESS;
 }
static int STX104_Fast_Menu_Convert_FIFO_Log_File_To_CSV (struct menu_command_params * p) static
Definition at line 878 of file stx104_fast.c.
References demo_fifo_log_file_name, demo_fifo_log_file_name_csv, Demo_STX104_Data_Timer_Tick_State(), demo_stx104_data::fifo_log_file, FILE_NAME_SIZE, menu_command_params::info, and demo_stx104_data::out_file.
 {
         struct demo_stx104_data * ds;  /* data set */
         FILE *          csv_file;
         uint32_t        fifo_count;
         char            file_name[FILE_NAME_SIZE];
         uint32_t        row_count;
 #if defined( __BORLANDC__ ) || defined( __linux__ )
 #else
         errno_t  error_code;
 #endif
         ds = (struct demo_stx104_data *) p->info;
         /* open data file */
 #if defined( _WIN32 )
         error_code = fopen_s( &(ds->fifo_log_file), demo_fifo_log_file_name, "rb" );
 #else
         ds->fifo_log_file = fopen( demo_fifo_log_file_name, "rb" );
 #endif
         if ( NULL == ds->fifo_log_file )
         {
                 fprintf( ds->out_file, "Cannot open FIFO log output file.\n" );
                 return -EC_DEMO_MENU_QUIT;
         }
 #if defined( _WIN32 )
         error_code = fopen_s( &csv_file, demo_fifo_log_file_name_csv, "wt" );
 #else
         csv_file = fopen( demo_fifo_log_file_name_csv, "wt" );
 #endif
         if ( NULL == csv_file )
         {
                 fclose( ds->fifo_log_file );  ds->fifo_log_file = NULL;
                 fprintf( ds->out_file, "Cannot open file CSV file.\n" );
                 return -EC_DEMO_MENU_QUIT;
         }
         fprintf( ds->out_file, "\n" );
         fprintf( ds->out_file, "Log File CSV Dump:\n" );
         row_count = 0;
         while( (!feof(ds->fifo_log_file)) && (row_count <= 65534) )
         {
                 fread( &fifo_count, sizeof( uint32_t ), 1, ds->fifo_log_file );
                 if ( feof(ds->fifo_log_file) ) break;
 #if defined( __BORLANDC__ )
                 sprintf( file_name, "%lu\n", fifo_count );
 #elif defined( _WIN32 )
                 sprintf_s( file_name, FILE_NAME_SIZE, "%lu\n", fifo_count );
 #else /* assume Linux */
                 sprintf( file_name, "%u\n", fifo_count );
 #endif
                 fwrite( &file_name[0], sizeof( char ), strlen( file_name ), csv_file );
                 if ( !(row_count % 256) )
                 {
                         fprintf( ds->out_file, "\r%c", Demo_STX104_Data_Timer_Tick_State() );
                 }
                 row_count++;
         }
         fclose( ds->fifo_log_file );   ds->fifo_log_file = NULL;
         fclose( csv_file );
         return SUCCESS;
 }
static int STX104_Fast_Menu_Trigger_Start (struct menu_command_params * p) static
Definition at line 860 of file stx104_fast.c.
References menu_command_params::info, and STX104_Fast_Process_Start().
 {
         int error_code;
         struct demo_stx104_data * ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         error_code = STX104_Fast_Process_Start( ds );
         return error_code;
 }
static int STX104_Fast_Menu_Trigger_Stop (struct menu_command_params * p) static
Definition at line 869 of file stx104_fast.c.
References menu_command_params::info, and STX104_Fast_Process_Stop_Request().
 {
         struct demo_stx104_data * ds;  /* data set */
         ds = (struct demo_stx104_data *) p->info;
         STX104_Fast_Process_Stop_Request( ds );
         return SUCCESS;
 }
static int STX104_Fast_Process_Data (struct demo_stx104_data * ds) static
Definition at line 411 of file stx104_fast.c.
References ai_buffer, demo_stx104_data::ai_cfg_encoding, demo_stx104_data::board, demo_stx104_data::data_output_file, demo_stx104_data::fifo_full_error, demo_stx104_data::frame_quantity_request_per_write_cycle, demo_stx104_data::frame_size_in_bytes, demo_stx104_data::out_file, demo_stx104_data::revision_firmware, demo_stx104_data::software_frame_count, demo_stx104_data::software_frame_count_max, STX104_Fast_FIFO_Log(), and STX104_Fast_Process_Stop_Request().
Referenced by STX104_Fast_Main_Loop().
 {
         uint16_t                frame_count_actual;
         size_t                  frame_count_write;
         int                             error_code;
         int                             board;    /* short hand */
         FILE *                  out_file; /* short hand */
         uint32_t        scratch;
 /*
 #if defined( FIFO_LOG_DATA_AVAILABLE )
         uint32_t                fifo_count;
 #endif
 */
 #if defined( FIFO_LOG_DATA_AVAILABLE )
         STX104_Fast_FIFO_Log( ds );
 #endif
         if ( NULL == ds->data_output_file ) return 0; /* nothing to do */
         board    = ds->board;
         out_file = ds->out_file;
         frame_count_write = 0;
         error_code = STX104_AI_Frames_Get( board,               /* board descriptor */
                                                                            &ai_buffer[0],       /* starting position of the destination buffer */
                                                                            &frame_count_actual, /* actual frames that are copied to the buffer */
                                                                            ds->frame_quantity_request_per_write_cycle /* frames requested */
                                                                         );
         if ( EC_STX104_AI_FIFO_FULL == error_code )
         {  /* Don't bother to write anything because at this point we
                         now have data loss (and out of sync with channels),
                         better to restart.
                 */
                 STX104_Fast_Process_Stop_Request( ds );
                 fprintf( out_file, "\nMPD: Terminate FIFO full error: " );
                 fprintf( out_file, "terminating file write due to data loss.\n\n" );
                 ds->fifo_full_error = true;
                 /*frame_count_actual = 0;
                 STX104_Fast_Process_Start_Configuration( ds );*/
                 return 0;
         }
         if ( frame_count_actual > 0 )
         { /* compute software frame count and max frames to further process */
                 if ( ds->software_frame_count_max > 0 )
                 {
                         if ( ds->software_frame_count >= ds->software_frame_count_max )
{
                                 frame_count_write = 0;
                         }
                         else
{
                                 scratch  = ds->software_frame_count;
                                 scratch += (uint32_t) frame_count_actual;
                                 if ( scratch < ds->software_frame_count_max )
{
                                         ds->software_frame_count = scratch;
                                         frame_count_write        = (size_t) frame_count_actual;
                                 }
                                 else
{
                                         scratch = ds->software_frame_count_max - ds->software_frame_count;
                                         ds->software_frame_count   += scratch;
                                         frame_count_write                       = (size_t) scratch;
                                         STX104_Fast_Process_Stop_Request( ds );
                                 }
                         }
                 }
                 else
                 {
                         frame_count_write         = (size_t) frame_count_actual;
                         ds->software_frame_count += (uint32_t) frame_count_actual;
                 }
 /*printf( "  frame_quantity_request_per_write_cycle = %d\n", ds->frame_quantity_request_per_write_cycle );
 printf( "  frame_count_actual                     = %d\n", frame_count_actual );
 printf( "  frame_count_write                      = %d\n", frame_count_write );
 printf( "  software_frame_count                   = %d\n", ds->software_frame_count );*/
                 if ( frame_count_write > 0 )
                 { /* process frames */
 #if defined( CONVERT_STRAIGHT_BINARY_TO_TWOS_COMPLEMENT )
                         if ( ds->revision_firmware < STX104_REVISION_120328 )
                 {
                         size_t index;
                         for( index = 0; index < frame_count_write; index++ )
{
                                                 ai_buffer[index] = ai_buffer[index] ^ 0x8000;
                         }
                 }
                 else
                 {
                         if ( ( AI_ENCODING_STRAIGHT_BINARY == ds->ai_cfg_encoding ) ||
                                          ( AI_ENCODING_STRAIGHT_BINARY == ds->ai_cfg_encoding )  )
{
                                 size_t index;
                                 for( index = 0; index < frame_count_write; index++ )
{
                                         ai_buffer[index] = ai_buffer[index] ^ 0x8000;
                         }
                         }
                 }
 #endif
                         fwrite(         ai_buffer,                                      /* buffer to send to file */
                                                 ds->frame_size_in_bytes,        /* size of each frame in bytes */
                                                 frame_count_write,                      /* number of frames in the buffer */
                                                 ds->data_output_file            /* data file that buffer will be copied to */
                                   );
                 } /* frame_count_write */
         } /* frame_count_actual -- The number of samples sitting in the FIFO just after
                                    the completion of a frame readout.
           */
         return (int) frame_count_write;
 }
static int STX104_Fast_Process_Start (struct demo_stx104_data * ds) static
Definition at line 765 of file stx104_fast.c.
References demo_stx104_data::board, Demo_STX104_Files_Open(), demo_stx104_data::software_frame_count, demo_stx104_data::stop_request, STX104_Fast_Process_Start_Configuration(), STX104_Fast_Process_Start_Report(), and demo_stx104_data::time_start.
Referenced by STX104_Fast_Menu_Trigger_Start().
 {
         int error_code;
         /* open data and fifo log files */
         error_code = Demo_STX104_Files_Open( NULL, /* use default analog input data file name */
                                                                                  NULL, /* use default fifo log file name                */
                                                                                  ds
                                                                            );
         if ( error_code ) return error_code;
         /* produce report indicating setup */
         error_code = STX104_Fast_Process_Start_Report( ds );
         if ( error_code ) return error_code;
         /* initialize device and data structures */
         ds->software_frame_count = 0;
         ds->stop_request         = false;
         STX104_Fast_Process_Start_Configuration( ds );
         /* start time -- for statistical calculation use */
 #if _POSIX_TIMERS
         clock_gettime( CLOCK_REALTIME, &(ds->time_start) );
 #endif
         /* issue hardware trigger (i.e. enable analog input data sampling ) */
         error_code = STX104_Trg_Software_Start( ds->board );
         /*ds->active_sampling_interlock = true;*/
 #ifdef STX104_FAST_USE_INTERRUPTS
         error_code = STX104_Int_Enable_Set( board, true );
 #endif
         return error_code;
 }
static void STX104_Fast_Process_Start_Configuration (demo_stx104_data * ds) static
Definition at line 611 of file stx104_fast.c.
References stx104_configuration::ai_cfg, demo_stx104_data::ai_cfg_encoding, AI_FIRST_CHANNEL, AI_FRAME_TIME_NS, AI_LAST_CHANNEL, demo_stx104_data::board, demo_stx104_data::cfg, stx104_configuration::di_cfg, demo_stx104_data::frame_quantity_request_per_write_cycle, stx104_configuration::int_cfg, demo_stx104_data::revision_firmware, Static_Fast_CallBack_Source_A(), and stx104_configuration::trg_cfg.
Referenced by STX104_Fast_Process_Start().
 {
         int                             error_code;  /* for debug use only */
         stx104_ai_cfg_type  ai_cfg;
         STX104_DI_CFG_TYPE  di_cfg;
         /*STX104_DO_CFG_TYPE  do_cfg;*/
         STX104_TRG_CFG_TYPE trg_cfg;
         STX104_INT_CFG_TYPE int_cfg;
         int                                     board;
         board = ds->board;
         /* interrupts */
         error_code = STX104_Int_Enable_Set( board, false ); /* make STX104 interrupts are disabled */
 #ifdef STX104_FAST_CONFIG_FROM_HARDWARE
         error_code = STX104_Int_CFG_Get( board, &int_cfg );
 #else
         memset( &int_cfg, 0, sizeof( STX104_INT_CFG_TYPE ) );
 #endif
         int_cfg.callback_source_a = (AUL_INT_CALLBACK) Static_Fast_CallBack_Source_A;
         int_cfg.source_a          = ISA_THRESHOLD_COUNTER;
         int_cfg.threshold_source  = ITS_AI_FRAME;
         int_cfg.threshold         = ((uint32_t) ds->frame_quantity_request_per_write_cycle );  /* event rate */
 #ifdef STX104_FAST_USE_INTERRUPTS
         error_code = STX104_Int_CFG_Set( board, &int_cfg );
 #endif
         /* triggering   */
         error_code = STX104_Trg_Software_Stop( board );  /* make sure triggering has been stopped */
 #ifdef STX104_FAST_CONFIG_FROM_HARDWARE
         error_code = STX104_Trg_CFG_Get( board, &trg_cfg );
 #else
         memset( &trg_cfg, 0, sizeof( STX104_TRG_CFG_TYPE ) );
 #endif
         trg_cfg.enabled           = true;
         trg_cfg.start_mode        = STM_IMMEDIATE;
         trg_cfg.start_sync_source = TSS_NONE;
         trg_cfg.start_source      = STS_SOFTWARE_STROBE; /* start via software */
         trg_cfg.stop_source       = ETS_SOFTWARE_STROBE; /* stop via software */
         error_code = STX104_Trg_CFG_Set( board, &trg_cfg );
         /* make sure trigger is now inactive/off */
         error_code = STX104_Trg_Software_Stop( board );
         /* analog inputs */
 #ifdef STX104_FAST_CONFIG_FROM_HARDWARE
         error_code = STX104_AI_CFG_Get( board, &ai_cfg );
 #else
         memset( &ai_cfg, 0, sizeof( stx104_ai_cfg_type ) ); /* clear configuration */
 #endif
         ai_cfg.gain            = ACFG_GAIN_10V;
         ai_cfg.burst_timer_sec = 0.0; /* ignore */
         ai_cfg.frame_timer_sec = 0.0; /* ignore */
         ai_cfg.burst_timer_ns  = 5000; /* nS */
         ai_cfg.frame_timer_ns  = AI_FRAME_TIME_NS;
         ai_cfg.strobe_source   = AISS_AI_FRAME_TIMER;
         ai_cfg.first_channel   = AI_FIRST_CHANNEL;
         ai_cfg.last_channel    = AI_LAST_CHANNEL;
         ai_cfg.use_triggering_subsystem  = true;
         ai_cfg.high_speed_pre_queue_fifo = true;
 #if defined( CONVERT_STRAIGHT_BINARY_TO_TWOS_COMPLEMENT )
         if ( ds->revision_firmware >= STX104_REVISION_120328 )
         { /* let the hardware do the conversion! */
                 ds->ai_cfg_encoding = AI_ENCODING_TWOS_COMPLEMENT;
                 ai_cfg.encoding = AI_ENCODING_TWOS_COMPLEMENT;
         }
 #endif
         error_code = STX104_AI_CFG_Set( board, &ai_cfg ); /* update configuration to board */
         /* digital inputs */
 #ifdef STX104_FAST_CONFIG_FROM_HARDWARE
         error_code = STX104_DI_CFG_Get( board, &di_cfg );
 #else
         memset( &di_cfg, 0, sizeof( STX104_DI_CFG_TYPE ) );
 #endif
         di_cfg.swap_din1_and_din3 = true;
         error_code = STX104_DI_CFG_Set( board, &di_cfg );
         /* copy configurations to dataset */
         memset( &(ds->cfg), 0, sizeof(ds->cfg) );
         memcpy( &(ds->cfg.int_cfg), &int_cfg, sizeof(ds->cfg.int_cfg) );
         memcpy( &(ds->cfg.ai_cfg),  &ai_cfg,  sizeof(ds->cfg.ai_cfg)  );
         memcpy( &(ds->cfg.trg_cfg), &trg_cfg, sizeof(ds->cfg.trg_cfg) );
         memcpy( &(ds->cfg.di_cfg),  &di_cfg,  sizeof(ds->cfg.di_cfg)  );
         memcpy( &(ds->cfg.int_cfg), &int_cfg, sizeof(ds->cfg.int_cfg) );
 }
static int STX104_Fast_Process_Start_Report (struct demo_stx104_data * ds) static
Definition at line 691 of file stx104_fast.c.
References AI_FIRST_CHANNEL, AI_FRAME_TIME_NS, AI_LAST_CHANNEL, AI_MAXIMUM_SAMPLE_BUFFER_SIZE, FILE_OUTPUT_RATE_HZ, demo_stx104_data::frame_quantity_request_per_write_cycle, demo_stx104_data::frame_size_in_bytes, demo_stx104_data::out_file, and demo_stx104_data::software_frame_count_max.
Referenced by STX104_Fast_Process_Start().
 {
         double          frames_per_second;
         double          frames_per_file_write;
         double          samples_per_file_write;
         uint16_t        samples_per_frame;
         FILE *          out_file = ds->out_file;  /* short hand */
         /* determine if timing requests will work */
         fprintf( out_file, "\n\n" );
         fprintf( out_file, "-----------------\n" );
         fprintf( out_file, "Calculated values:\n" );
 #ifndef STX104_FAST_USE_INTERRUPTS
         fprintf( out_file, " Interrupts in use      =      No\n" );
 #else
     fprintf( out_file, " Interrupts in use      =     Yes\n" );
 #endif
     fprintf( out_file, " Frames to be collected = " );
     if ( ds->software_frame_count_max > 0 )
     {
         fprintf( out_file, "%7u\n", ds->software_frame_count_max );
     }
     else
     {
         fprintf( out_file, "  MANUAL\n" );
     }
         samples_per_frame   = (uint16_t) ( AI_LAST_CHANNEL - AI_FIRST_CHANNEL + 1 );
         ds->frame_size_in_bytes = samples_per_frame * sizeof( uint16_t /* sample data type */ );
         fprintf( out_file, " frame_size_in_bytes    = %7d\n", ds->frame_size_in_bytes );
         frames_per_second   = ( (double) 1.0 ) / ( ((double) AI_FRAME_TIME_NS) * 1.0e-9 /*ns*/ );
         fprintf( out_file, " frames_per_second      = %10.2f\n", frames_per_second );
         frames_per_file_write  = frames_per_second / ( (double) FILE_OUTPUT_RATE_HZ );
         fprintf( out_file, " frames_per_file_write  = %10.2f\n", frames_per_file_write );
         samples_per_file_write = frames_per_file_write * ((double) samples_per_frame );
         fprintf( out_file, " samples_per_file_write = %10.2f\n", samples_per_file_write );
         if ( samples_per_file_write > ((long) AI_MAXIMUM_SAMPLE_BUFFER_SIZE) )
         {
                 fprintf( out_file, " Samples per file write cycle exceed AI_MAXIMUM_SAMPLE_BUFFER_SIZE\n" );
                 return -EC_DEMO_STX104_FILE_OPEN_ERROR;
         }
         if ( samples_per_file_write >= ((long) 65535 ) )
         {
                 fprintf( out_file, " Frame per write cycle too big\n" );
                 return -1;
         }
         ds->frame_quantity_request_per_write_cycle = (uint16_t) frames_per_file_write ;
         /*  In order for the FIFO sample count to be maintained at an average DC
          *  value it was important on your test system to increase the frame quantity
          *  per file write cycle.  In other words, due to large amount of jitter in
          *  our system the best compensation method is by increasing the frame request
          *  (i.e. frame_quantity_request_per_write_cycle ) by a percentage.  Another
          *  way of saying this is that when we achieve a relatively constant amount
          *  of samples sitting in the FIFO (even though it is going up and down) then
          *  we know that the system will keep up long term.
          *
          *  We can observe this behavior by plotting the fifo.csv file.
          *
          */
         ds->frame_quantity_request_per_write_cycle = (uint16_t) ( frames_per_file_write * 1.25 );
 /*      ds->frame_quantity_request_per_write_cycle = (uint16_t) ( frames_per_file_write * 1.5  );*/
         fprintf( out_file, " frame_quantity_request_per_write_cycle = %d\n", ds->frame_quantity_request_per_write_cycle );
         if ( ds->frame_quantity_request_per_write_cycle == 0 )
         {
                 fprintf( out_file, " Frames per write cycle is zero\n" );
                 return -EC_DEMO_STX104_FILE_OPEN_ERROR;
         }
         fprintf( out_file, "-----------------\n\n" );
         return SUCCESS;
 }
void STX104_Fast_Process_Stop (struct demo_stx104_data * ds)
Definition at line 817 of file stx104_fast.c.
References demo_stx104_data::board, Demo_STX104_Files_Close(), demo_stx104_data::out_file, demo_stx104_data::stop_request, STX104_Fast_Process_Stop_Report(), and demo_stx104_data::time_stop.
Referenced by main(), and STX104_Fast_Main_Loop().
 {
         int             error_code;  /* debug only */
         if ( !ds->stop_request ) return; /* nothing to do */
         ds->stop_request = false;
         /* issue a trigger stop */
         error_code = STX104_Trg_Software_Stop( ds->board );
         /* shut down events (interrupts) */
 #ifdef STX104_FAST_USE_INTERRUPTS
         error_code = STX104_Int_Enable_Set( ds->board, false );
 #endif
         /* end of sample timing */
 #if _POSIX_TIMERS
         clock_gettime( CLOCK_REALTIME, &(ds->time_stop) );
 #endif
         /* output statistics */
         STX104_Fast_Process_Stop_Report( ds );
         /* close out data and log files */
         Demo_STX104_Files_Close( ds );
         fprintf( ds->out_file, "Done\n\n" );
 }
static void STX104_Fast_Process_Stop_Report (struct demo_stx104_data * ds) static
Definition at line 794 of file stx104_fast.c.
References demo_stx104_data::frame_size_in_bytes, demo_stx104_data::out_file, demo_stx104_data::software_frame_count, STX104_Fast_Time_Delta(), demo_stx104_data::time_start, and demo_stx104_data::time_stop.
Referenced by STX104_Fast_Process_Stop().
 {
         int64_t delta_usec;
         double  frames_per_sec;
         /* Post summary information */
         fprintf( ds->out_file, "\n\nData collection complete\n" );
         /* STX104_AI_Frame_Count_Get( board, &frame_count ); */
 #if defined( __BORLANDC__ )
         fprintf( ds->out_file, "  Total frames written = %8ld\n", ds->software_frame_count );
         fprintf( ds->out_file, "  Total bytes written  = %8lu\n", ds->software_frame_count * ((uint32_t) ds->frame_size_in_bytes) );
 #else
         fprintf( ds->out_file, "  Total frames written = %8d\n", ds->software_frame_count );
         fprintf( ds->out_file, "  Total bytes written  = %8u\n", ds->software_frame_count * ((uint32_t) ds->frame_size_in_bytes) );
 #endif
         /*fprintf( out_file, "\n" );*/
         delta_usec = STX104_Fast_Time_Delta( &(ds->time_start), &(ds->time_stop) );
         fprintf( ds->out_file, "  Time interval        = %8lu us\n", delta_usec );
         fprintf( ds->out_file, "  Total frames         = %8lu\n", ds->software_frame_count );
         frames_per_sec = 1.0e6 /* us/sec */ * ((double) ds->software_frame_count) / ((double) delta_usec );
         fprintf( ds->out_file, "  Frames/sec           = %10.1f\n", frames_per_sec );
         fprintf( ds->out_file, "\n" );
 }
void STX104_Fast_Process_Stop_Request (demo_stx104_data * ds)
Definition at line 839 of file stx104_fast.c.
References demo_stx104_data::stop_request.
Referenced by Static_Fast_CallBack_Source_A(), STX104_Fast_Main_Stop_Request(), STX104_Fast_Menu_Trigger_Stop(), and STX104_Fast_Process_Data().
 {
         ds->stop_request = true;
 }
static int64_t STX104_Fast_Time_Delta (struct timespec * ts_start, struct timespec * ts_end) static
Definition at line 573 of file stx104_fast.c.
Referenced by STX104_Fast_Process_Stop_Report().
 {
     /* seconds, multiplied with 1 million */
     int64_t usec_start = ts_start->tv_sec * 1000000;
     int64_t usec_end   = ts_end->tv_sec * 1000000;
     /* Add full microseconds */
     usec_start += ts_start->tv_nsec/1000;
     usec_end += ts_end->tv_nsec/1000;
     /* round up if necessary */
     if (ts_start->tv_nsec % 1000 >= 500) ++usec_start;
     if (ts_end->tv_nsec % 1000 >= 500) ++usec_end;
     usec_end = usec_end - usec_start;
     return usec_end;
 }
Variable Documentation
uint16_t ai_buffer[AI_MAXIMUM_SAMPLE_BUFFER_SIZE]
Definition at line 370 of file stx104_fast.c.
Referenced by Static_Fast_CallBack_Source_A(), and STX104_Fast_Process_Data().
struct demo_stx104_data demo_stx104_data static
Definition at line 375 of file stx104_fast.c.
Referenced by main().
struct menu_data stx104_fast_data_list[] static
Initial value:
=
{
        {       0,                      0,              Demo_STX104_Data_Timer_Tick,      0,                            NULL                    },
        {       5,                      0,              Demo_STX104_Data_DI,                      3,                            "DI:"                   },
        {  14,                  0,              Demo_STX104_Data_Config_AI,               3,                            "AI:"                   },
        {  32,                  0,              Demo_STX104_Data_Trig,                    4,                            "TRG:"                  },
        {  38,                  0,              STX104_Data_Frames,                               3,                            "FR:"                   },
        {       0,                      0,              NULL,                                                     0,                            NULL                    }
}
TODO
Definition at line 1098 of file stx104_fast.c.
struct menu_command stx104_fast_menu_list[] static
Menu structure or list.
The underlying menu processing is performed via menu.c functions. The menu was implemented in this fashion for flexibility which is reused for other demonstration code. It also removes a lot of clutter from the demo source files.
Note that each of the functions used within this list must handle a single pointer to a menu_command_params data structure.
Definition at line 1038 of file stx104_fast.c.