#!/bin/bash

# Apex Universal Library Kernel Module Loader  
# Apex Embedded Systems
#
# 
# "$Date: 2014-04-29 09:54:14 -0500 (Tue, 29 Apr 2014) $"

#
# Make sure we are root
#
if [[ $EUID -ne 0 ]]; then
	echo "NOTICE: this script must be run as root" 1>&2
	exit 1
fi

#
#find the root group
#
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

#
# install the module
#
# NOTE: this is temporary, but gives an example of all parameters.
sudo insmod mod_auldrv.ko offset=0x300,0x310 bytes=0x10,0x10 acronym="stx104","tracere" type="stx104","tracere"
#allows parameters to be sent via text file.
#insmod mod_auldrv.ko "$(< aul_hw.txt)"
#chgrp $group /dev/auldrv
#chmod 666 /dev/auldrv
#chgrp $group /dev/stx104
#chmod 666 /dev/stx104


#!/bin/bash

####################################################################################
# Kernel Module Manual Loader  
# Apex Embedded Systems
#
# "$Date: 2015-01-14 17:25:35 -0600 (Wed, 14 Jan 2015) $"
####################################################################################

####################################################################################
# Make sure we use sudo if necessary
#
if [ $EUID -eq 0 ]; then
   DOIT_AS_SUDO=0
else
   DOIT_AS_SUDO=1
fi

####################################################################################
#find the root group
#
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

####################################################################################
# install the module
#
# NOTE: This is just an example, and your exact implementation will be dictated 
#       by the boards you are using.

if [ $DOIT_AS_SUDO -eq 1 ]; then
  echo Loading kernel module as root
  insmod mod_auldrv.ko offset=0x300,0x310 bytes=0x10,0x10 acronym="stx104","tracere" type="stx104","tracere"
else
  echo Loading kernel module
  insmod mod_auldrv.ko offset=0x300,0x310 bytes=0x10,0x10 acronym="stx104","tracere" type="stx104","tracere"
fi

####################################################################################
# Notes
#

#allows parameters to be sent via text file.
#insmod mod_auldrv.ko "$(< aul_hw.txt)"

#all of this is now performed via udev rule.  See the readme.txt file for more information.
#chgrp $group /dev/auldrv
#chmod 666 /dev/auldrv
#chgrp $group /dev/stx104
#chmod 666 /dev/stx104

