#!/bin/bash

# Apex Universal Library Kernel Module Loader  
# Apex Embedded Systems
#
# "$Date: 2014-04-29 09:54:14 -0500 (Tue, 29 Apr 2014) $"

#
# Make sure we are root
#
if [[ $EUID -ne 0 ]]; then
	echo "NOTICE: this script must be run as root" 1>&2
	exit 1
fi

rmmod mod_auldrv_sim
