Isolated Digital Input Test Utility: src/idi.c File Reference
idi.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
Data Structures
struct ec_human_readable
struct reg_definition
struct spi_cfg
struct spi_status
struct din_cfg
struct idi_dataset
struct command_line
Macros
#define strcmpi strcasecmp
#define IDI_REV "$Date: 2015-03-05 08:48:57 -0600 (Thu, 05 Mar 2015) $"
The Subversion (SVN) time/date marker which is updated during commit of the source file to the repository.
#define false 0
#define true 1
#define CLOCK_PERIOD_SEC 20.0e-9
Board clock period as defined by the on-board oscillator which is 50MHz.
#define ID_ALWAYS_REPORT_AS_GOOD 1
#define IDI_ERROR_CODES(_)
An organized error code listing. This macro is used to build the complete error code enumeration list.
#define EC_EXTRACT_ENUM(symbol, code, message) symbol = code,
#define EC_EXTRACT_HUMAN_READABLE(symbol, code, message) { code, message },
#define EC_HUMAN_READABLE_TERMINATE { 0, NULL }
#define IDI_REGISTER_SET_DEFINITION(_)
Organized list of registers and associate attributes of each of the registers. This macro does not consume any memory of in itself, and is only 'consumed' or used to automatically build enumerations and pre-built data structures.
#define REG_BANK_SET(bank) (bank << 8)
#define REG_OFFSET_SET(offset) (offset & 0xff)
#define REG_LOCATION_BANK_GET(location) ((location >> 8) & 0xFF)
#define REG_LOCATION_OFFSET_GET(location) (location & 0xff)
#define REG_EXTRACT_ENUM(symbol, index, offset, register_bytes, aperture_bytes, read_write, name, bank) symbol = (REG_BANK_SET(bank) | REG_OFFSET_SET(offset)),
#define REG_EXTRACT_DEFINITION(symbol, index, offset, register_bytes, aperture_bytes, read_write, name, bank) { ((IDI_REG_ENUM) (REG_BANK_SET(bank) | REG_OFFSET_SET(offset))), read_write, bank, offset, #symbol, name },
#define IDI_DIN_GROUP_SIZE 8
#define IDI_DIN_SHIFT_RIGHT 3
#define IDI_DIN_GROUP_QTY 6
#define IDI_DIN_QTY (IDI_DIN_GROUP_SIZE * IDI_DIN_GROUP_QTY)
#define FRAM_BLOCK_SIZE 256
#define IDI_MESSAGE_SIZE 256
#define SPI_BLOCK_SIZE 256
#define IDI_IO_DIRECTION_TEST 1
Typedefs
typedef int BOOL
The C89 compiler is typically void of these definitions, so we include them here. Defines specific data width information. The idea is to make this target independent.
Enumerations
enum { FALSE = 0, TRUE = 1 }
enum { ID_DIN = 0x8012, ID_SPI = 0x8013 }
These are the unique IDs assigned to the hardware components. If there is a firmware revision within any of these components within the board, a new ID will be assigned. The philosophy behind the ID scheme is that it embodies both a unique ID and revision information in a purely arbitrary scheme. It assumes that all components defined within the system will never have the same ID numbers. We maintain a unique list of those ID numbers. We will provide a list to customers as required.
enum EC_ENUM
enum IDI_BANK_ENUM {
IDI_BANK_0 = 0x00, IDI_BANK_1 = 0x40, IDI_BANK_2 = 0x80, IDI_BANK_3 = 0xC0,
IDI_BANK_4 = 0x20, IDI_BANK_5 = 0x60, IDI_BANK_6 = 0xA0, IDI_BANK_7 = 0xE0,
IDI_BANK_NONE = 0xFE, IDI_BANK_UNDEFINED = 0xFF
}
The bank register mapping. This mapping is upwardly compatible with the legacy hardware banking register. It also allows for future expansion utilizing the lower bits which are currently unused.
enum REG_DIR_ENUM { REG_DIR_NONE = 0x00, REG_DIR_READ = 0x01, REG_DIR_WRITE = 0x02, REG_DIR_READ_WRITE = 0x03 }
enum IDI_REG_ENUM
enum SPI_CSB_ENUM { IDI_CSB_SOFTWARE = 0, IDI_CSB_BUFFER = 1, IDI_CSB_UINT8 = 2, IDI_CSB_UINT16 = 3 }
enum { SPI_FIFO_SIZE = 16 }
enum { HEX_DUMP_BYTES_PER_LINE = 16 }
Dumps a hexadecimal and ASCII equivalent string to the desired output. The format, illustrated below is a classic memory dump format.
enum { FRAM_DENSITY_BYTES = 8192 }
FRAM Density current in use.
Functions
static const char * IDI_Symbol_Name_Bank (IDI_BANK_ENUM bank)
Outputs a human readable CSV to the desired output file or stdout.
int IDI_Register_Report_CSV (const struct reg_definition *table, FILE *out)
Outputs a human readable CSV to the desired output file or stdout.
BOOL String_To_Bool (const char *str)
General function used to convert a string into a boolean equivalent value.
int Hex_Dump_Line (uint16_t address, size_t count, uint8_t *buffer, FILE *out)
const char * EC_Code_To_Human_Readable (EC_ENUM error_code)
BOOL Character_Get (int *character)
Obtains a key from the keyboard in a non-blocking way. This is exerpetted from AES Universal Library/Driver.
static char * IO_Get_Symbol_Name (IDI_REG_ENUM location)
Translates a register enumerated symbol into a string that is the same as the enumerated symbol used throughout this code base.
static BOOL IO_Direction_IsNotValid (IDI_REG_ENUM location, REG_DIR_ENUM direction)
Looks up in the register definitions list for the ports possible read/write directions.
int IO_Write_U8 (IDI_REG_ENUM location, uint8_t value)
Writes uint8_t to I/O port. Macros are used to guide the target implementation.
int IO_Read_U8 (IDI_REG_ENUM location, uint8_t *value)
Reads uint8_t from I/O port. Macros are used to guide the target implementation.
void IO_Write_U16_Address_Increment (IDI_REG_ENUM location, uint16_t value)
Writes uint16_t to I/O ports in a uint8_t succession incrementing the offset address. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
void IO_Read_U16_Address_Increment (IDI_REG_ENUM location, uint16_t *value)
Reads uint16_t from I/O ports in a uint8_t succession incrementing the offset address. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
void IO_Write_U16_Address_Fixed (IDI_REG_ENUM location, uint16_t value)
Writes uint16_t to I/O ports in a uint8_t succession to the same address location. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
void IO_Read_U16_Address_Fixed (IDI_REG_ENUM location, uint16_t *value)
Reads uint16_t from I/O ports in a uint8_t succession to the same address location. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
int IDI_DIN_ID_Get (uint16_t *id)
Obtains the DIN component (or board ID in this case) ID number.
BOOL IDI_DIN_IsNotPresent (void)
Determines if the DIN component and/or board is present. Returns true if not present (i.e. error).
static int IDI_DIN_Channel_Get (size_t channel, BOOL *value)
Obtains and reports a single digital input channel.
static int IDI_DIN_Group_Get (size_t group, uint8_t *value)
Reads the selected digital input port (8-bits).
int SPI_ID_Get (uint16_t *id)
Retrieves the SPI ID register value.
int SPI_IsNotPresent (void)
Reports if the SPI component is available within the register space by matching a known ID. The SPI register map is only enabled within the hardware if the hardware mode is not zero (i.e. M1 and M0 jumpers on the board provide a nonzero value).
int SPI_Calculate_Half_Clock (double half_clock_request_sec, double *half_clock_actual_sec, double *error, uint16_t *hci)
Computes the half clock register value given a requested time interval. It will also produce a 'report' indicating the actual value (due to integer resolution) as well as a computed error between requested and actual. The error can be used to determine whether timing constraints are met.
int SPI_Calculate_Clock (double clock_request_hz, double *clock_actual_hz, double *error, uint16_t *hci)
Computes the SPI clock half clock register value given a requested SPI clock frequency. It will also produce a 'report' indicating the actual value (due to integer resolution) as well as a computed error between requested and actual. The eror can be used to determine whether timing constraints are met.
double SPI_Calculate_Half_Clock_Interval_Sec (uint16_t half_clock_interval)
Computes the half clock interval in seconds given the value from the half clock interval register.
int SPI_Calculate_End_Cycle_Delay (double spi_half_clock_interval_sec, double delay_request_sec, double *delay_actual_sec, double *error, uint8_t *ecd)
Computes the time delay at the end of each byte transmitted. It will only output the parameters whose pointers are not NULL.
int SPI_Configuration_Chip_Select_Behavior_Get (SPI_CSB_ENUM *chip_select_behavior)
Extracts the chip select behavior from the SPI configuration register.
int SPI_Configuration_Chip_Select_Behavior_Set (SPI_CSB_ENUM chip_select_behavior)
Sets the chip select behavior to the SPI configuration register.
int SPI_Configuration_Set (struct spi_cfg *cfg)
Commits the configuration data structure to the hardware.
int SPI_Configuration_Get (struct spi_cfg *cfg)
Obtains the SPI configuration from the hardware.
int SPI_Report_Configuration_Text (struct spi_cfg *cfg, FILE *out)
Creates a human readable report of the SPI configuration data structure.
int SPI_Report_Status_Text (struct spi_status *status, FILE *out)
Produces a human readable report of the SPI status data structure.
int SPI_Configuration_Initialize (struct spi_cfg *cfg)
Initializes the SPI configuration data structure.
int SPI_Status_Write (struct spi_status *status)
Builds a detailed status data structure of the transmit/write outgoing SPI data FIFO. Reports the quantity of bytes currently in the transmit FIFO, full flag, empty flag, the total size of the FIFO in bytes, and sets tx_status to true indicating that this is status specific to the transmit FIFO.
void SPI_Status_Write_FIFO_Status (BOOL *full, BOOL *empty, size_t *bytes_in_fifo)
Returns the complete write/transmit FIFO status.
BOOL SPI_Status_Write_FIFO_Is_Full (void)
Returns the transmit/write FIFO full status flag. It is preferable to use the SPI_Status_Write() or SPI_Status_Write_FIFO_Status() because all status is retrieved at one time.
void SPI_Status_Read_FIFO_Status (BOOL *empty, size_t *bytes_available)
Returns the complete read/receive FIFO status.
int SPI_Status_Read (struct spi_status *status)
Builds a detailed status data structure of the receive/read incoming SPI data FIFO. Reports the quantity of bytes currently in the receive FIFO, full flag, empty flag, the total size of the FIFO in bytes, and sets tx_status to false indicating that this is status specific to the receive FIFO.
BOOL SPI_Status_Write_FIFO_Is_Not_Empty (void)
Returns the transmit/write FIFO empty status flag. This function is typically used to wait for the transmit/write FIFO to become empty.
BOOL SPI_Status_Read_FIFO_Is_Not_Empty (void)
Returns the receive/read FIFO empty status flag. This function is typically used to determine if the FIFO is empty.
int SPI_Commit (uint8_t chip_select)
Sets/Clears the chip select or used to commit the transmit/write FIFO to the spi interface. The mode of operation is dependent on the chip_select_behavior.
int SPI_FIFO_Write (const void *buffer, size_t size, size_t count, FILE *fd_log)
Writes specifically to the SPI transmit/write data FIFO. It does not attempt to correlate the number of transmit bytes with receive bytes. Its purpose is more for low level hardware testing. Note that this function has a signature identical to the fwrite() function (i.e. make use of function pointers to guide destination of data).
int SPI_FIFO_Read (const void *buffer, size_t size, size_t count, FILE *fd_log)
Reads from the SPI receive/read data FIFO. It does not attempt to correlate the number of transmit bytes with receive bytes. Its purpose is more for low level hardware testing. Note that this function has a signature identical to the fread() function (i.e. make use of function pointers to guide sourcing of data).
static int SPI_Data_Write_Read_Helper (size_t size, size_t tx_count, const void *tx_buffer, size_t rx_size, const void *rx_buffer, BOOL active_tx, BOOL active_rx, SPI_CSB_ENUM csb)
int SPI_Data_Write_Read (size_t size, size_t tx_count, const void *tx_buffer, size_t rx_size, const void *rx_buffer)
This function will write/read virtually any kind of data with almost any kind of chips select wrapping surrounding the data.
int SPI_Data_Write (const void *tx_buffer, size_t size, size_t tx_count, FILE *fd_log)
Special case of Write/Read that has a function signature same as fread() or fwrite().
int SPI_Data_Read (const void *rx_buffer, size_t size, size_t rx_size, FILE *fd_log)
Special case of Write/Read that has a function signature same as fread() or fwrite().
int FRAM__Write_Enable_Latch_Set (void)
FRAM Write Enable Latch Set command (WREN)
int FRAM__Write_Disable (void)
FRAM Write Latch disable (or clear) command (WRDI).
int FRAM__Read_Status_Register (uint8_t *status)
Read the FRAM status register and output the value.
int FRAM__Write_Status_Register (uint8_t status)
Write to the FRAM status register.
int FRAM__Memory_Read (uint16_t address, size_t count, uint8_t *buffer)
Reads data from FRAM memory to the output buffer.
int FRAM__Memory_Write (uint16_t address, size_t count, uint8_t *buffer)
Writes data from buffer to FRAM memory.
int FRAM__Read_ID (uint32_t *id)
int FRAM_Set (size_t count, uint8_t *buffer)
This function will be used when creating a memory pool so that as blocks are allocated one can determine if we have an issue outside of any allocated space (i.e. overflows and so on).
int FRAM_Report (uint16_t address, size_t length, FILE *out)
int FRAM_Memory_To_File (uint16_t address, size_t length, FILE *binary)
int FRAM_File_To_Memory (uint16_t address, size_t length, FILE *binary)
static int IDI_CMD__SPI_ID (int argc, char *argv[])
static int IDI_CMD__SPI_Config_Get (int argc, char *argv[])
static int IDI_CMD__SPI_Config_Clock_Hz (int argc, char *argv[])
static int IDI_CMD__SPI_Config_End_Cycle_Delay_Sec (int argc, char *argv[])
static int IDI_CMD__SPI_Config_Mode (int argc, char *argv[])
CPOL CPHA MODE 0 0 0 1 0 1 2 1 0 3 1 1.
static int IDI_CMD__SPI_Config_SDI_Polarity (int argc, char *argv[])
static int IDI_CMD__SPI_Config_SDO_Polarity (int argc, char *argv[])
static int IDI_CMD__SPI_Config_SDIO_Wrap (int argc, char *argv[])
static int IDI_CMD__SPI_Config_Chip_Select_Behavior (int argc, char *argv[])
static int IDI_CMD__SPI_Status (int argc, char *argv[])
static int IDI_CMD__SPI_Data (int argc, char *argv[])
static int IDI_CMD__SPI_FIFO (int argc, char *argv[])
static int IDI_CMD__SPI_Commit (int argc, char *argv[])
int IDI_Command_Line_SPI (int argc, char *argv[])
static int IDI_CMD__FRAM_Dump (int argc, char *argv[])
static int IDI_CMD__FRAM_Save (int argc, char *argv[])
static int IDI_CMD__FRAM_Load (int argc, char *argv[])
static int IDI_CMD__FRAM_Init (int argc, char *argv[])
static int IDI_CMD__FRAM_WREN (int argc, char *argv[])
static int IDI_CMD__FRAM_WRDI (int argc, char *argv[])
static int IDI_CMD__FRAM_RDSR (int argc, char *argv[])
static int IDI_CMD__FRAM_WRSR (int argc, char *argv[])
static int IDI_CMD__FRAM_RDID (int argc, char *argv[])
int IDI_Command_Line_FRAM (int argc, char *argv[])
static int IDI_CMD__DIN_ID (int argc, char *argv[])
static int IDI_CMD__DIN_All (int argc, char *argv[])
static int IDI_CMD__DIN_Channel (int argc, char *argv[])
static int IDI_CMD__DIN_Group (int argc, char *argv[])
int IDI_Command_Line_Digital_Input (int argc, char *argv[])
int IDI_Command_Line_Register_Transaction (int argc, char *argv[])
Either reads or writes a register using the form: idi <register acronym>=""> [].
static int IDI_CMD__Main_IO_Behavior (int argc, char *argv[])
static int IDI_CMD__Main_Base (int argc, char *argv[])
int IDI_Command_Line_Set (int argc, char *argv[])
int IDI_Command_Line_Main (int argc, char *argv[])
Processes and dispatches the top level of the command and passes the remaining string list onto specialized functions to further process arguments. If no command is specified then a help output is produced.
void IDI_Help (FILE *out)
Outputs a help listing to the user.
int IDI_Termination (void)
Runs upon application exit. It saves the idi_dataset data structure.
int IDI_Initialization (void)
Runs upon application startup. It restores the idi_dataset data structure or if the file cannot be found it will simply initialize those parameters to default values.
int main (int argc, char *argv[])
Processes and dispatches the top level of the command and passes the remaining string list onto specialized functions to further process arguments. If no command is specified then a help output is produced.
Variables
static const char idi_svn_revision_string [] = { IDI_REV }
Global variables.
const struct ec_human_readable ec_human_readable []
static const char * idi_bank_symbol_names []
static const struct reg_definition definitions []
struct idi_dataset idi_dataset
static const char ec_unknown [] = "unknown error code"
Translates an error code into a human readable message.
static struct command_line idi_cmd_spi []
static struct command_line idi_cmd_fram []
static struct command_line idi_cmd_din []
static struct command_line idi_cmd_main []
Macro Definition Documentation
#define CLOCK_PERIOD_SEC 20.0e-9
Board clock period as defined by the on-board oscillator which is 50MHz.
Definition at line 81 of file idi.c.
Referenced by SPI_Calculate_End_Cycle_Delay(), SPI_Calculate_Half_Clock(), SPI_Calculate_Half_Clock_Interval_Sec(), and SPI_Configuration_Get().
#define EC_EXTRACT_ENUM (symbol, code, message) symbol = code,
Definition at line 160 of file idi.c.
#define EC_EXTRACT_HUMAN_READABLE (symbol, code, message) { code, message },
Definition at line 161 of file idi.c.
#define EC_HUMAN_READABLE_TERMINATE { 0, NULL }
Definition at line 162 of file idi.c.
#define false 0
Definition at line 72 of file idi.c.
#define FRAM_BLOCK_SIZE 256
Definition at line 372 of file idi.c.
Referenced by FRAM_File_To_Memory(), FRAM_Memory_To_File(), and FRAM_Set().
#define ID_ALWAYS_REPORT_AS_GOOD 1
Definition at line 124 of file idi.c.
#define IDI_DIN_GROUP_QTY 6
Definition at line 355 of file idi.c.
Referenced by IDI_CMD__DIN_All(), and IDI_CMD__DIN_Group().
#define IDI_DIN_GROUP_SIZE 8
Definition at line 353 of file idi.c.
Referenced by IDI_DIN_Channel_Get().
#define IDI_DIN_QTY (IDI_DIN_GROUP_SIZE * IDI_DIN_GROUP_QTY)
Definition at line 356 of file idi.c.
#define IDI_DIN_SHIFT_RIGHT 3
Definition at line 354 of file idi.c.
Referenced by IDI_DIN_Channel_Get().
#define IDI_ERROR_CODES (_)
Value:
/*    enum_symbol                      code     human readable             */ \
        _( SUCCESS,                         0,      ""                          ) \
        _( EC_BUFFER_TOO_LARGE,             1,      "buffer too large"          ) \
        _( EC_DIRECTION,                    2,      "direction"                 ) \
        _( EC_PARAMETER,                    3,      "parameter"                 ) \
        _( EC_NOT_FOUND,                    4,      "not found"                 ) \
        _( EC_PARAMETER_MISSING,            5,      "missing parameter"         ) \
        _( EC_SYNTAX,                       6,      "syntax error"              ) \
        _( EC_HEX_DUMP_COUNT,               7,      "hex dump count"            ) \
        _( EC_INIT_FILE,                    8,      "write init file failed"    ) \
        _( EC_SPI_ECD_OUT_OF_RANGE,        20,      "SPI ECD range"             ) \
        _( EC_SPI_HALF_CLOCK_OUT_OF_RANGE, 21,      "SPI half clock range"      ) \
        _( EC_SPI_CSB_OUT_OF_RANGE,        22,      "SPI CSB range"             ) \
        _( EC_SPI_NOT_FOUND,               23,      "SPI not found"             ) \
        _( EC_SPI_BUFFER_SIZE_ODD,         24,      "buffer size odd"           ) \
        _( EC_SPI_BUFFER_SIZE,             25,      "buffer size out of range"  ) \
        _( EC_SPI_OBJECT_SIZE,             26,      "spi tx/rx object size"     )
An organized error code listing. This macro is used to build the complete error code enumeration list.
Definition at line 139 of file idi.c.
#define IDI_IO_DIRECTION_TEST 1
Definition at line 680 of file idi.c.
#define IDI_MESSAGE_SIZE 256
Definition at line 373 of file idi.c.
#define IDI_REGISTER_SET_DEFINITION (_)
Organized list of registers and associate attributes of each of the registers. This macro does not consume any memory of in itself, and is only 'consumed' or used to automatically build enumerations and pre-built data structures.
Definition at line 222 of file idi.c.
#define IDI_REV "$Date: 2015-03-05 08:48:57 -0600 (Thu, 05 Mar 2015) $"
The Subversion (SVN) time/date marker which is updated during commit of the source file to the repository.
Definition at line 48 of file idi.c.
#define REG_BANK_SET (bank) (bank << 8)
Definition at line 285 of file idi.c.
#define REG_EXTRACT_DEFINITION (symbol, index, offset, register_bytes, aperture_bytes, read_write, name, bank) { ((IDI_REG_ENUM) (REG_BANK_SET(bank) | REG_OFFSET_SET(offset))), read_write, bank, offset, #symbol, name },
Definition at line 293 of file idi.c.
#define REG_EXTRACT_ENUM (symbol, index, offset, register_bytes, aperture_bytes, read_write, name, bank) symbol = (REG_BANK_SET(bank) | REG_OFFSET_SET(offset)),
Definition at line 291 of file idi.c.
#define REG_LOCATION_BANK_GET (location) ((location >> 8) & 0xFF)
Definition at line 287 of file idi.c.
Referenced by IO_Read_U8(), and IO_Write_U8().
#define REG_LOCATION_OFFSET_GET (location) (location & 0xff)
Definition at line 288 of file idi.c.
Referenced by IO_Read_U8(), and IO_Write_U8().
#define REG_OFFSET_SET (offset) (offset & 0xff)
Definition at line 286 of file idi.c.
#define SPI_BLOCK_SIZE 256
Definition at line 374 of file idi.c.
#define strcmpi strcasecmp
Definition at line 36 of file idi.c.
Referenced by IDI_CMD__DIN_All(), IDI_CMD__DIN_Group(), IDI_CMD__Main_IO_Behavior(), IDI_CMD__SPI_Config_Chip_Select_Behavior(), IDI_CMD__SPI_FIFO(), IDI_CMD__SPI_Status(), IDI_Command_Line_Digital_Input(), IDI_Command_Line_FRAM(), IDI_Command_Line_Main(), IDI_Command_Line_Register_Transaction(), IDI_Command_Line_Set(), IDI_Command_Line_SPI(), and main().
#define true 1
Definition at line 73 of file idi.c.
Typedef Documentation
typedef int BOOL
The C89 compiler is typically void of these definitions, so we include them here. Defines specific data width information. The idea is to make this target independent.
Boolean logic definitions
Definition at line 71 of file idi.c.
Enumeration Type Documentation
anonymous enum
Enumerator
FALSE
TRUE
Definition at line 74 of file idi.c.
 { FALSE = 0, TRUE = 1 };
anonymous enum
These are the unique IDs assigned to the hardware components. If there is a firmware revision within any of these components within the board, a new ID will be assigned. The philosophy behind the ID scheme is that it embodies both a unique ID and revision information in a purely arbitrary scheme. It assumes that all components defined within the system will never have the same ID numbers. We maintain a unique list of those ID numbers. We will provide a list to customers as required.
Software uses these ID numbers to determine which portion of the driver/library to apply to that portion of the hardware. For example, if we end up having DINs with different ID numbers, this simply means that the each will require (potentially) a unique portion of driver/library in order to properly use that portion of the hardware. This requires that the library/driver has some knowledge related to the ID numbers assigned.
At this point, an ID=0x8012 implies an Isolated Digital Input component that has a register map identical to the WinSystems Opto48 card. The actual DIN48 component has a more straight forward register mapping, but within the STD-bus space we have re-arranged it to appear like the WinSystems Opto48 card.
Similarly with the SPI component, we have mangled the register set in order that it fit within the constrained register space.
One could argue that there ought to be a nibble for revision and an upper nibble for the component ID itself, but quickly you find out the limitation of that implementation. If we simply use an arbitrary list from 1 to 65535 we can fit it within 16-bits and it will be a fairly long time until it is filled. In a couple years we will likely move to 32-bit and simply continue where we left off. The software really does not care, so long as the numbers are always unique. We can use the uniqueness of the IDs along with some implied intelligence (i.e. what board is this, what bus are we on, and perhaps a little bit of knowledge of the component itself) we can always build and grow software to accommodate new revisions and still support older revision hardware.
Enumerator
ID_DIN
component DIN48 ID
ID_SPI
component SPI ID
Definition at line 114 of file idi.c.
 {
     ID_DIN = 0x8012,
     ID_SPI = 0x8013
 };
anonymous enum
Enumerator
SPI_FIFO_SIZE
Definition at line 324 of file idi.c.
 { SPI_FIFO_SIZE = 16 };
anonymous enum
Dumps a hexadecimal and ASCII equivalent string to the desired output. The format, illustrated below is a classic memory dump format.
<address>: <hex> [<hex>].... <ascii list>="">
Parameters
[in] address starting address.
[in] count number of bytes in the buffer
[in] buffer buffer containing the bytes to output
[out] out desired output destination.
Returns
An error code is returned.
Enumerator
HEX_DUMP_BYTES_PER_LINE
Definition at line 570 of file idi.c.
 { HEX_DUMP_BYTES_PER_LINE = 16 };
anonymous enum
FRAM Density current in use.
Enumerator
FRAM_DENSITY_BYTES
Definition at line 2059 of file idi.c.
 { FRAM_DENSITY_BYTES = 8192 };
enum EC_ENUM
Definition at line 167 of file idi.c.
 {
     IDI_ERROR_CODES( EC_EXTRACT_ENUM )
 } EC_ENUM;  /* EC = Error Code */
enum IDI_BANK_ENUM
The bank register mapping. This mapping is upwardly compatible with the legacy hardware banking register. It also allows for future expansion utilizing the lower bits which are currently unused.
Enumerator
IDI_BANK_0
IDI_BANK_1
IDI_BANK_2
IDI_BANK_3
IDI_BANK_4
IDI_BANK_5
IDI_BANK_6
IDI_BANK_7
IDI_BANK_NONE
indicates exclusive of bank address
IDI_BANK_UNDEFINED
indicates that no banking has been defined
Definition at line 191 of file idi.c.
 {
     IDI_BANK_0          = 0x00,
     IDI_BANK_1          = 0x40,
     IDI_BANK_2          = 0x80,
     IDI_BANK_3          = 0xC0,
     IDI_BANK_4          = 0x20,
     IDI_BANK_5          = 0x60,
     IDI_BANK_6          = 0xA0,
     IDI_BANK_7          = 0xE0,
     IDI_BANK_NONE       = 0xFE,
     IDI_BANK_UNDEFINED  = 0xFF
 } IDI_BANK_ENUM;
enum IDI_REG_ENUM
Definition at line 296 of file idi.c.
 {
     IDI_REGISTER_SET_DEFINITION( REG_EXTRACT_ENUM )
 } IDI_REG_ENUM;
enum REG_DIR_ENUM
Enumerator
REG_DIR_NONE
REG_DIR_READ
REG_DIR_WRITE
REG_DIR_READ_WRITE
Definition at line 205 of file idi.c.
 {
     REG_DIR_NONE        = 0x00,
     REG_DIR_READ        = 0x01,
     REG_DIR_WRITE       = 0x02,
     REG_DIR_READ_WRITE  = 0x03
 } REG_DIR_ENUM;
enum SPI_CSB_ENUM
Enumerator
IDI_CSB_SOFTWARE
IDI_CSB_BUFFER
IDI_CSB_UINT8
IDI_CSB_UINT16
Definition at line 315 of file idi.c.
 {
     IDI_CSB_SOFTWARE    = 0,
     IDI_CSB_BUFFER      = 1,
     IDI_CSB_UINT8       = 2,
     IDI_CSB_UINT16      = 3
 } SPI_CSB_ENUM;
Function Documentation
BOOL Character_Get (int * character)
Obtains a key from the keyboard in a non-blocking way. This is exerpetted from AES Universal Library/Driver.
Parameters
[out] character Character from keyboard otherwise null character.
Returns
If true, then a valid character is available at the keyboard, otherwise false.
Definition at line 652 of file idi.c.
Referenced by main().
 {
     int  char_temp;
     BOOL result = false;
 #ifdef __BORLANDC__
     if ( kbhit() )
     {
         char_temp = getch();
         result    = true;
     }
     else
     {
         char_temp = '\0';
     }
 #else
     char_temp = '\0';
     result    = false;
 #endif
     if ( NULL != character ) *character = char_temp;
     return result;
 }
const char* EC_Code_To_Human_Readable (EC_ENUM error_code)
Definition at line 626 of file idi.c.
References ec_unknown, ec_human_readable::message, and idi_dataset::message.
Referenced by main().
 {
     int index;
     if ( error_code < 0 ) error_code = -error_code;
     index = 0;
     while( NULL != ec_human_readable[index].message )
     {
         if ( ((EC_ENUM) error_code) == ec_human_readable[index].error_code )
         {
             return ec_human_readable[index].message;
         }
         index++;
     }
     return ec_unknown;
 }
int FRAM__Memory_Read (uint16_t address, size_t count, uint8_t * buffer)
Reads data from FRAM memory to the output buffer.
Parameters
[in] address Starting FRAM address
[in] count Number of bytes to transfer
[out] buffer Destination buffer in which to store the data
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2142 of file idi.c.
References IDI_CSB_SOFTWARE, SPI_Commit(), SPI_Configuration_Chip_Select_Behavior_Set(), SPI_Data_Write_Read(), and SPI_Status_Write_FIFO_Is_Not_Empty().
Referenced by FRAM_Memory_To_File(), and FRAM_Report().
 {
     int             error_code;
 //  SPI_CSB_ENUM    csb_copy;
     uint8_t         tx_buf[3] = { 0x03, 0x00, 0x00 }; /* opcode: READ = 0x03 */
     //uint8_t rx_buf[3];
     tx_buf[1] = (uint8_t)( address & 0xFF );
     tx_buf[2] = (uint8_t)( address >>   8 );
 //  /* retain an existing copy of the actual csb value */
 //  error_code = SPI_Configuration_Chip_Select_Behavior_Get( &csb_copy );
 //  if ( error_code ) return error_code;
     /* over-ride and set it to what we wish it to be */
     error_code = SPI_Configuration_Chip_Select_Behavior_Set( IDI_CSB_SOFTWARE );
     if ( error_code ) return error_code;
     SPI_Commit( 1 );
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), 3, tx_buf, 0, NULL );
     if ( error_code ) return error_code;
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), 0, NULL, count, buffer );
     if ( error_code ) return error_code;
     while ( SPI_Status_Write_FIFO_Is_Not_Empty() ); /* wait for buffer to empty */
     SPI_Commit( 0 );
 //  /* restore the csb */
 //  error_code = SPI_Configuration_Chip_Select_Behavior_Set( csb_copy );
 //  if ( error_code ) return error_code;
     return SUCCESS;
 }
int FRAM__Memory_Write (uint16_t address, size_t count, uint8_t * buffer)
Writes data from buffer to FRAM memory.
Parameters
[in] address Starting FRAM address
[in] count Number of bytes to transfer
[out] buffer Source buffer from which data will be transfered to FRAM
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2187 of file idi.c.
References IDI_CSB_SOFTWARE, SPI_Commit(), SPI_Configuration_Chip_Select_Behavior_Set(), SPI_Data_Write_Read(), and SPI_Status_Write_FIFO_Is_Not_Empty().
Referenced by FRAM_File_To_Memory(), and FRAM_Set().
 {
     int             error_code;
 //  SPI_CSB_ENUM    csb_copy;
     uint8_t         tx_buf[3] = { 0x02, 0x00, 0x00 }; /* opcode: WRITE = 0x02 */
     tx_buf[1] = (uint8_t)( address & 0xFF );
     tx_buf[2] = (uint8_t)( address >>   8 );
 //  /* retain an existing copy of the actual csb value */
 //  error_code = SPI_Configuration_Chip_Select_Behavior_Get( &csb_copy );
 //  if ( error_code ) return error_code;
     /* over-ride and set it to what we wish it to be */
     error_code = SPI_Configuration_Chip_Select_Behavior_Set( IDI_CSB_SOFTWARE );
     if ( error_code ) return error_code;
     SPI_Commit( 1 );
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), 3, tx_buf, 0, NULL );
     if ( error_code ) return error_code;
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), count, buffer, 0, NULL );
     if ( error_code ) return error_code;
     while ( SPI_Status_Write_FIFO_Is_Not_Empty() ); /* wait for buffer to empty */
     SPI_Commit( 0 );
 //  /* restore the csb */
 //  error_code = SPI_Configuration_Chip_Select_Behavior_Set( csb_copy );
 //  if ( error_code ) return error_code;
     return SUCCESS;
 }
int FRAM__Read_ID (uint32_t * id)
Parameters
[out] id The 32-bit ID register read from the FRAM. This appears to be only available with Fujistu parts.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2228 of file idi.c.
References IDI_CSB_BUFFER, SPI_Configuration_Chip_Select_Behavior_Set(), and SPI_Data_Write_Read().
Referenced by FRAM_Set(), and IDI_CMD__FRAM_RDID().
 {
     int         error_code;
     uint8_t     tx_buf[5] = { 0x9F, 0x00, 0x00, 0x00, 0x00 }; /* opcode: RDID = 0x9F */
     uint8_t     rx_buf[5];
     SPI_Configuration_Chip_Select_Behavior_Set( IDI_CSB_BUFFER );
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), 5, tx_buf, 5, rx_buf );
     if ( error_code ) return error_code;
     {
         int id_scratch = 0;
         int index;
         for ( index = 4; index > 0; index-- )
         {
             id_scratch = ( id_scratch << 8 ) | ( (uint32_t) rx_buf[index] );
         }
         *id = id_scratch;
     }
     return SUCCESS;
 }
int FRAM__Read_Status_Register (uint8_t * status)
Read the FRAM status register and output the value.
Parameters
status A pointer to the destination location of the status data.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2098 of file idi.c.
References IDI_CSB_BUFFER, SPI_Configuration_Chip_Select_Behavior_Set(), and SPI_Data_Write_Read().
Referenced by IDI_CMD__FRAM_RDSR().
 {
     int     error_code;
     uint8_t tx_buf[2] = { 0x05, 0x00 }; /* opcode: RDSR = 0x04 */
     uint8_t rx_buf[2];
     SPI_Configuration_Chip_Select_Behavior_Set( IDI_CSB_BUFFER );
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), 2, tx_buf, 2, rx_buf );
     if ( error_code ) return error_code;
     *status = rx_buf[1];
     return SUCCESS;
 }
int FRAM__Write_Disable (void)
FRAM Write Latch disable (or clear) command (WRDI).
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2083 of file idi.c.
References IDI_CSB_BUFFER, SPI_Configuration_Chip_Select_Behavior_Set(), and SPI_Data_Write_Read().
Referenced by IDI_CMD__FRAM_WRDI().
 {
     uint8_t tx_buf[1] = { 0x04 }; /* opcode: WRDI = 0x04 */
     SPI_Configuration_Chip_Select_Behavior_Set( IDI_CSB_BUFFER );
     return SPI_Data_Write_Read( sizeof( uint8_t ), 1, tx_buf, 0, NULL );
 }
int FRAM__Write_Enable_Latch_Set (void)
FRAM Write Enable Latch Set command (WREN)
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2069 of file idi.c.
References IDI_CSB_BUFFER, SPI_Configuration_Chip_Select_Behavior_Set(), and SPI_Data_Write_Read().
Referenced by IDI_CMD__FRAM_WREN().
 {
     uint8_t tx_buf[1] = { 0x06 }; /* opcode: WREN = 0x06 */
     SPI_Configuration_Chip_Select_Behavior_Set( IDI_CSB_BUFFER );
     return SPI_Data_Write_Read( sizeof( uint8_t ), 1, tx_buf, 0, NULL );
 }
int FRAM__Write_Status_Register (uint8_t status)
Write to the FRAM status register.
Parameters
[in] FRAM status value to be written.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2119 of file idi.c.
References IDI_CSB_BUFFER, SPI_Configuration_Chip_Select_Behavior_Set(), and SPI_Data_Write_Read().
Referenced by IDI_CMD__FRAM_WRSR().
 {
     int     error_code;
     uint8_t tx_buf[2] = { 0x05, 0x00 }; /* opcode: RDSR = 0x04 */
     uint8_t rx_buf[2];
     tx_buf[1] = status;
     SPI_Configuration_Chip_Select_Behavior_Set( IDI_CSB_BUFFER );
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), 2, tx_buf, 2, rx_buf );
     if ( error_code ) return error_code;
     return SUCCESS;
 }
int FRAM_File_To_Memory (uint16_t address, size_t length, FILE * binary)
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2393 of file idi.c.
References FRAM__Memory_Write(), idi_dataset::fram_block, and FRAM_BLOCK_SIZE.
Referenced by IDI_CMD__FRAM_Load().
 {
     int     error_code;
     size_t  count_read;
     size_t  count_total;
     size_t  count_actual;
     count_total = 0;
     count_read  = FRAM_BLOCK_SIZE;
     if ( 0 == length )
     {
         do
         {
             count_actual = fread( idi_dataset.fram_block, 1, count_read, binary );
             error_code   = FRAM__Memory_Write( address, count_read, idi_dataset.fram_block );
             if ( error_code ) return error_code;
             count_total += count_actual;
             if ( count_actual != count_read ) count_read = 0; /* must be at end of file */
         } while ( count_read > 0 );
     }
     else
     {
         if ( length < count_read ) count_read = length;
         do
         {
             count_actual = fread( idi_dataset.fram_block, 1, count_read, binary );
             error_code   = FRAM__Memory_Write( address, count_read, idi_dataset.fram_block );
             if ( error_code ) return error_code;
             count_total += count_actual;
             length      -= count_actual;
             if ( count_actual != count_read ) count_read = 0; /* must be at end of file */
             if ( length < count_read ) count_read = length;
         } while ( count_read > 0 );
     }
     return SUCCESS;
 }
int FRAM_Memory_To_File (uint16_t address, size_t length, FILE * binary)
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2362 of file idi.c.
References FRAM__Memory_Read(), idi_dataset::fram_block, and FRAM_BLOCK_SIZE.
Referenced by IDI_CMD__FRAM_Save().
 {
     int         error_code;
     size_t      block_count;
     size_t      block_remainder;
     block_count = length / ((size_t) FRAM_BLOCK_SIZE);
     block_remainder = length - ( block_count * ((size_t) FRAM_BLOCK_SIZE) );
     while ( block_count > 0 )
     {
         error_code = FRAM__Memory_Read( address, ((size_t) FRAM_BLOCK_SIZE), idi_dataset.fram_block );
         fwrite( idi_dataset.fram_block, 1, ((size_t) FRAM_BLOCK_SIZE), binary );
         address += FRAM_BLOCK_SIZE;
         block_count--;
     }
     if ( block_remainder > 0 )
     {
         error_code = FRAM__Memory_Read( address, block_remainder, idi_dataset.fram_block );
         fwrite( idi_dataset.fram_block, 1, block_remainder, binary );
         if ( error_code ) return error_code;
     }
     return SUCCESS;
 }
int FRAM_Report (uint16_t address, size_t length, FILE * out)
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2329 of file idi.c.
References FRAM__Memory_Read(), idi_dataset::fram_block, HEX_DUMP_BYTES_PER_LINE, and Hex_Dump_Line().
Referenced by IDI_CMD__FRAM_Dump().
 {
     int         error_code;
     const int   block_size = HEX_DUMP_BYTES_PER_LINE;
     size_t      block_count;
     size_t      block_remainder;
     block_count = ((size_t) length) / block_size;
     block_remainder = ((size_t) length) - ( block_count * block_size );
     while ( block_count > 0 )
     { /* output a line at a time */
         error_code = FRAM__Memory_Read( address, block_size, idi_dataset.fram_block );
         error_code = Hex_Dump_Line( address, block_size, idi_dataset.fram_block, out );
         address += block_size;
         block_count--;
     }
     if ( block_remainder > 0 )
     { /* output any remaining portion */
         error_code = FRAM__Memory_Read( address, block_remainder, idi_dataset.fram_block );
         error_code = Hex_Dump_Line( address, block_remainder, idi_dataset.fram_block, out );
         if ( error_code ) return error_code;
     }
     return SUCCESS;
 }
int FRAM_Set (size_t count, uint8_t * buffer)
This function will be used when creating a memory pool so that as blocks are allocated one can determine if we have an issue outside of any allocated space (i.e. overflows and so on).
Parameters
[in] cfg pass in the configuration to be written to hardware.
Returns
a nonzero if successful, else return zero.
Writes a repeating pattern to the entire FRAM memory array. the pattern is obtained from the buffer. If the buffer is NULL, then all zeros are written to the FRAM.
Parameters
[in] count Length in bytes of the pattern found within the buffer
[in] buffer input buffer containing the repeat pattern to be written to FRAM
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2273 of file idi.c.
References FRAM__Memory_Write(), FRAM__Read_ID(), idi_dataset::fram_block, FRAM_BLOCK_SIZE, and FRAM_DENSITY_BYTES.
Referenced by IDI_CMD__FRAM_Init().
 {
     int         error_code;
     int         block_count;
     int         block_remainder;
     uint16_t    address;
     uint32_t    id;
     error_code = FRAM__Read_ID( &id );
     if ( error_code ) return error_code;
     address = 0;
     if ( count > 1 )
     { /* */
         block_count     = ((int) FRAM_DENSITY_BYTES) / ((int) count );
         block_remainder = ((int) FRAM_DENSITY_BYTES) - ( block_count * ((int) FRAM_BLOCK_SIZE) );
     }
     else
     { /* only one fill character, so we create a buffer of it to make things a bit faster */
         int         index;
         const int   block_size = FRAM_BLOCK_SIZE;
         /* prefill */
         if ( NULL == buffer )
         {
             for ( index = 0; index < block_size; index++ ) idi_dataset.fram_block[index]= 0;
         }
         else
         {
             for ( index = 0; index < block_size; index++ ) idi_dataset.fram_block[index]= buffer[0];
         }
         block_count     = ((int) FRAM_DENSITY_BYTES) / block_size;
         block_remainder = ((int) FRAM_DENSITY_BYTES) - ( block_count * block_size );
         buffer          = idi_dataset.fram_block;
     }
     while ( block_count > 0 )
     {
         error_code = FRAM__Memory_Write( address, ((int) count), buffer );
         address += (uint16_t) count;
         block_count--;
     }
     if ( block_remainder > 0 )
     {
         error_code = FRAM__Memory_Write( address, block_remainder, buffer );
         if ( error_code ) return error_code;
     }
     return SUCCESS;
 }
int Hex_Dump_Line (uint16_t address, size_t count, uint8_t * buffer, FILE * out)
Definition at line 572 of file idi.c.
References HEX_DUMP_BYTES_PER_LINE.
Referenced by FRAM_Report(), IDI_CMD__SPI_Data(), and IDI_CMD__SPI_FIFO().
 {
     size_t  index;
     char    str_temp[8];
     char    str_ascii[20];
     char    str_hex_list[64];
     //if ( count > 16 ) return -EC_BUFFER_TOO_LARGE;
     if ( count > HEX_DUMP_BYTES_PER_LINE ) return -EC_HEX_DUMP_COUNT;
     sprintf( str_hex_list, "%04X: ", ((int) address) );
     strcpy( str_ascii,    "" );
     for ( index = 0; index < count; index++ )
     {   /* append/build hex list */
         sprintf( str_temp, "%02X", buffer[index] );
         strcat( str_hex_list, str_temp );
         /* output spacer in the middle and end */
         if ( 0x07 == ( index & 0x07 ) ) strcat( str_hex_list, "  " );
         /* add a space after hex value and spacers */
         strcat( str_hex_list, " " );
         /* append/build ASCII list */
         if ( ( buffer[index] < ' ' ) || ( buffer[index] > '~' ) )
         { /* since these characters will not display replace them with a period */
             strcat( str_ascii, "." );
         }
         else
         { /* print the character as is */
             sprintf( str_temp, "%c", buffer[index] );
             strcat( str_ascii, str_temp );
         }
     }
     /* compute any remaining filler required to properly align ASCII portion */
     index = strlen( str_hex_list );
     /* total = ( 6 ) 'address characters' + ( 16 * 3 ) 'hex characters' + ( 2 * 3 ) 'spacers'  = 60 */
     count = 60 - index;
     while ( count > 0 )
     { /* add sufficient characters so that the ASCII portion is in the proper columns */
         strcat( str_hex_list, " " );
         count--;
     }
     /* output the results */
     fprintf( out, "%s%s\n", str_hex_list, str_ascii );
     return SUCCESS;
 }
static int IDI_CMD__DIN_All (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3284 of file idi.c.
References IDI_DIN_Group_Get(), IDI_DIN_GROUP_QTY, and strcmpi.
 { /* idi din all [<binary/hex/group>]  */
     int     error_code;            /* used primarily for debug purposes */
     int     channel;
     //BOOL  value;
     int     cp;
     enum { MODE_NONE = 0, MODE_BINARY = 1, MODE_HEX = 2, MODE_ALL = 3 } mode_out;
     int     group;
     char    message[64];
     uint8_t din_grp[6];
     uint8_t mask;
     (void)  argc;
     (void)  argv;
     mode_out = MODE_ALL;
     if ( argc > 0 )
     {
         int index;
         mode_out = MODE_NONE;
         for ( index = 0; index < argc; index++ )
         {
             if      ( 0 == strcmpi( "binary", argv[index] ) ) mode_out |= MODE_BINARY;
             else if ( 0 == strcmpi( "group",  argv[index] ) ) mode_out |= MODE_HEX;
             else if ( 0 == strcmpi( "hex",    argv[index] ) ) mode_out |= MODE_HEX;
             else                                              mode_out |= MODE_ALL;
         }
     }
     /* build in binary format */
     cp    = 0;
     group = 0;
     for ( group = 0; group < IDI_DIN_GROUP_QTY; group++ )
     {
         error_code = IDI_DIN_Group_Get( group, &(din_grp[group]) );
         mask = 0x01;
         for ( channel = 0; channel < 8; channel++ )
         {
             message[cp++] = !!(din_grp[group] & mask) ? '1' : '0';
             mask = mask << 1;
         }
         message[cp++] = ' ';
     }
     message[cp] = '\0';
     if ( MODE_BINARY == ( mode_out & MODE_BINARY ) )
     {
         printf( "DIN: %s\n", message );
     }
     if ( MODE_HEX == ( mode_out & MODE_HEX ) )
     {
         printf( "DIN:" );
         for ( group = 0; group < IDI_DIN_GROUP_QTY; group++ ) printf( " %02X", din_grp[group] );
         printf( "\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__DIN_Channel (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3345 of file idi.c.
References IDI_DIN_Channel_Get().
 {
     int     error_code;            /* used primarily for debug purposes */
     int     channel;
     char    message[8];
     BOOL    value;
     if ( argc < 1 ) return -EC_NOT_FOUND;
     channel = (int) strtol( argv[0], NULL, 0 );
     error_code = IDI_DIN_Channel_Get( channel, &value );
     message[0] = value ? '1' : '0';
     message[1] = '\0';
     printf( "DIN%02d: %s\n", channel, message );
     return SUCCESS;
 }
static int IDI_CMD__DIN_Group (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3368 of file idi.c.
References IDI_DIN_Group_Get(), IDI_DIN_GROUP_QTY, and strcmpi.
 {
     int     error_code;
 //  int     index;
     int     group;
     int     group_count;
     BOOL    do_all;
     uint8_t din_grp[6];
     if ( argc < 1 ) do_all = true;
     else            do_all = false;
     if ( 0 == strcmpi( "all", argv[0] ) ) do_all = true;
     if ( do_all )
     { /* all */
         for ( group = 0; group < IDI_DIN_GROUP_QTY; group ++ )
         {
             error_code = IDI_DIN_Group_Get( group, &(din_grp[group]) );
         }
         group_count = IDI_DIN_GROUP_QTY;
     }
     else
     {
         group = (int) strtol( argv[0], NULL, 0 );
         error_code = IDI_DIN_Group_Get( group, &(din_grp[0]) );
         group_count = 1;
     }
     printf( "DIN_GROUP:" );
     for ( group = 0; group < group_count; group++ )
     {
         printf( " 0x%02X", ((int) din_grp[group]) );
     }
     printf( "\n" );
     return SUCCESS;
 }
static int IDI_CMD__DIN_ID (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3269 of file idi.c.
References IDI_DIN_ID_Get().
 { /*  idi spi id */
     uint16_t    id;
     (void)      argc;
     (void)      argv;
     IDI_DIN_ID_Get( &id );
     printf( "DIN ID: 0x%04X\n", id );
     return SUCCESS;
 }
static int IDI_CMD__FRAM_Dump (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3054 of file idi.c.
References FRAM_DENSITY_BYTES, FRAM_Report(), and HEX_DUMP_BYTES_PER_LINE.
 { /* idi fram dump <address> <length>  */
     uint16_t address;
     uint16_t length;
     if ( argc < 1 ) return -EC_PARAMETER;
     address = (uint16_t) strtol( argv[0], NULL, 0 );
     if ( argc < 2 ) length = HEX_DUMP_BYTES_PER_LINE;
     else            length  = (uint16_t) strtol( argv[1], NULL, 0 );
     if ( ( address + length ) > FRAM_DENSITY_BYTES ) length = FRAM_DENSITY_BYTES - address;
     return FRAM_Report( address, length, stdout );
 }
static int IDI_CMD__FRAM_Init (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3119 of file idi.c.
References FRAM_Set().
 { /*  idi fram init <pattern list: 0x55 0x33 '3' '5' 'q' >  */
     int         error_code;
     int         index;
     uint8_t     buf[16];
     if ( argc < 1 )
     { /* initialize all zeros */
         error_code = FRAM_Set( 0, NULL );
     }
     else
     {
         if ( argc > 16 ) argc = 16;
         for ( index = 0; index < argc; index++ )
         {
             buf[index] = (uint8_t) strtol( argv[index], NULL, 0 );
         }
         error_code = FRAM_Set( argc, buf );
     }
     return error_code;
 }
static int IDI_CMD__FRAM_Load (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3098 of file idi.c.
References FRAM_File_To_Memory().
 { /* idi fram load <address> <source_file> */
     int         error_code;
     uint16_t    address;
 //  uint16_t    length;
     FILE *      out;
     if ( argc < 2 ) return -EC_PARAMETER;
     address = (uint16_t) strtol( argv[0], NULL, 0 );
     out = fopen( argv[2], "r" );
     error_code = FRAM_File_To_Memory( address, 0 /* no length specified */, out );
     fclose( out );
     return error_code;
 }
static int IDI_CMD__FRAM_RDID (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3200 of file idi.c.
References FRAM__Read_ID().
 { /*  idi fram RDID  */
     uint32_t    id;
     (void)      argc;
     (void)      argv;
     FRAM__Read_ID( &id );
     printf( "FRAM ID: 0x%08X\n", id );
     return SUCCESS;
 }
static int IDI_CMD__FRAM_RDSR (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3169 of file idi.c.
References FRAM__Read_Status_Register().
 { /* idi fram RDSR  */
     int         error_code;
     uint8_t     status;
     (void)      argc;
     (void)      argv;
     error_code = FRAM__Read_Status_Register( &status );
     printf( "FRAM STATUS: 0x%02X\n", ((int) status) );
     return error_code;
 }
static int IDI_CMD__FRAM_Save (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3076 of file idi.c.
References FRAM_Memory_To_File().
 { /* idi fram save <address> <length> <destination_file> */
     int         error_code;
     uint16_t    address;
     size_t      length;
     FILE *      out;
     if ( argc < 3 ) return -EC_PARAMETER;
     address = (uint16_t) strtol( argv[0], NULL, 0 );
     length  = (uint16_t) strtol( argv[1], NULL, 0 );
     out = fopen( argv[2], "w" );
     error_code = FRAM_Memory_To_File( address, length, out );
     fclose( out );
     return error_code;
 }
static int IDI_CMD__FRAM_WRDI (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3157 of file idi.c.
References FRAM__Write_Disable().
 { /*  idi fram WRDI  */
     (void)      argc;
     (void)      argv;
     return FRAM__Write_Disable();
 }
static int IDI_CMD__FRAM_WREN (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3145 of file idi.c.
References FRAM__Write_Enable_Latch_Set().
 { /* idi fram WREN */
     (void)      argc;
     (void)      argv;
     return FRAM__Write_Enable_Latch_Set();
 }
static int IDI_CMD__FRAM_WRSR (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3185 of file idi.c.
References FRAM__Write_Status_Register().
 { /*  idi fram WRSR <value>  */
 //  int     error_code;
     uint8_t status;
     if ( argc < 1 ) return -EC_PARAMETER;
     status = (uint8_t) strtol( argv[0], NULL, 0 );
     return FRAM__Write_Status_Register( status );
 }
static int IDI_CMD__Main_Base (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3583 of file idi.c.
References idi_dataset::base_address.
 { /*  idi spi ecd [<time sec>] */
     int      error_code;               /* used primarily for debug purposes */
     if ( argc < 1 )
     { /* read */
         printf( "BASE_ADDRESS: 0x%04X\n", idi_dataset.base_address );
     }
     else
     { /* write */
         idi_dataset.base_address = (uint16_t) strtol( argv[0], NULL, 0 );
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__Main_IO_Behavior (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3543 of file idi.c.
References idi_dataset::io_report, idi_dataset::io_simulate, strcmpi, and String_To_Bool().
 { /*  idi spi ecd [<time sec>] */
     int      error_code;               /* used primarily for debug purposes */
     if ( argc < 1 )
     { /* read */
         printf( "IO Simulate = %s\n", idi_dataset.io_simulate ? "true" : "false" );
         printf( "IO Report   = %s\n", idi_dataset.io_report   ? "true" : "false" );
     }
     else if ( argc > 1 )
     { /* write */
         if       ( 0 == strcmpi( "simulate", argv[0] ) )
         {
             idi_dataset.io_simulate = String_To_Bool( argv[1] );
         }
         else if  ( 0 == strcmpi( "report", argv[0] ) )
         {
             idi_dataset.io_report = String_To_Bool( argv[1] );
         }
         printf( "OK\n" );
     }
     else
     { /* read individual */
         if       ( 0 == strcmpi( "simulate", argv[0] ) )
         {
             printf( "IO Simulate = %s\n", idi_dataset.io_simulate ? "true" : "false" );
         }
         else if  ( 0 == strcmpi( "report", argv[0] ) )
         {
             printf( "IO Report   = %s\n", idi_dataset.io_report   ? "true" : "false" );
         }
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Commit (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2975 of file idi.c.
References SPI_Commit(), and String_To_Bool().
 { /*  idi spi commit [<true/1/false/0>] */
     int      error_code;
     uint8_t  chip_select;
     if      ( argc < 1                  ) chip_select = 0x01;
     else if ( String_To_Bool( argv[0] ) ) chip_select = 0x01;
     else                                  chip_select = 0x00;
     error_code = SPI_Commit( chip_select );
     if ( error_code ) return error_code;
     printf( "OK\n" );
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_Chip_Select_Behavior (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2717 of file idi.c.
References spi_cfg::chip_select_behavior, IDI_CSB_BUFFER, IDI_CSB_SOFTWARE, IDI_CSB_UINT16, IDI_CSB_UINT8, SPI_Configuration_Get(), SPI_Configuration_Set(), and strcmpi.
 { /*  idi spi mode [0/1/2/3/software/buffer/uint8/uint16] */
     int      error_code;
 //  int      csb;
     struct   spi_cfg cfg;
     /* pull current configuration from the hardware -- allows for warm restore so to speak */
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     if ( argc < 1 )
     { /* read */
         printf( "SPI CSB: ");
         switch ( cfg.chip_select_behavior )
         {
             case IDI_CSB_SOFTWARE:  printf( "software" );   break;
             case IDI_CSB_BUFFER:    printf( "buffer"   );   break;
             case IDI_CSB_UINT8:     printf( "uint8"    );   break;
             case IDI_CSB_UINT16:    printf( "uint16"   );   break;
             default:                printf( "undefined");   break;
         }
         printf( "\n" );
     }
     else
     { /* write */
         if      ( 0 == strcmpi( "software", argv[0] ) ) cfg.chip_select_behavior = 0;
         else if ( 0 == strcmpi( "buffer",   argv[0] ) ) cfg.chip_select_behavior = 1;
         else if ( 0 == strcmpi( "uint8",    argv[0] ) ) cfg.chip_select_behavior = 2;
         else if ( 0 == strcmpi( "uint16",   argv[0] ) ) cfg.chip_select_behavior = 3;
         else
         {
             cfg.chip_select_behavior = (SPI_CSB_ENUM) strtol( argv[0], NULL, 0 );
             switch ( cfg.chip_select_behavior )
             {
                 case IDI_CSB_SOFTWARE:
                 case IDI_CSB_BUFFER:
                 case IDI_CSB_UINT8:
                 case IDI_CSB_UINT16:
                     break;
                 default:
                     error_code = -EC_SPI_CSB_OUT_OF_RANGE;
                     break;
             }
         }
          if ( error_code ) return error_code;
         /* commit configuration to hardware */
         error_code = SPI_Configuration_Set( &cfg );
         if ( error_code ) return error_code;
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_Clock_Hz (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2499 of file idi.c.
References spi_cfg::clock_hz, SPI_Calculate_Clock(), SPI_Configuration_Get(), and SPI_Configuration_Set().
 { /*  idi spi clk [<freq_hz>] */
     int      error_code;
     double   clock_request_hz;
     double   clock_actual_hz;
     double   error;
     uint16_t hci;
     struct   spi_cfg cfg;
     /* pull current configuration from the hardware -- allows for warm restore so to speak */
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     if ( argc < 1 )
     { /* read */
         printf( "SPI CLK: %f hz\n", cfg.clock_hz );
     }
     else
     { /* write */
         clock_request_hz = atof( argv[0] );
         error_code = SPI_Calculate_Clock( clock_request_hz, &clock_actual_hz, &error, &hci );
         if ( error_code ) return error_code;
         //cfg.half_clock_interval = hci;
         /* commit configuration to hardware */
         cfg.clock_hz = clock_actual_hz;
         error_code   = SPI_Configuration_Set( &cfg );
         if ( error_code ) return error_code;
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_End_Cycle_Delay_Sec (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2536 of file idi.c.
References spi_cfg::end_delay_ns, spi_cfg::half_clock_interval, SPI_Calculate_End_Cycle_Delay(), SPI_Calculate_Half_Clock_Interval_Sec(), SPI_Configuration_Get(), and SPI_Configuration_Set().
 { /*  idi spi ecd [<time sec>] */
     int      error_code;
     double   request_sec;
     double   actual_sec;
     double   error;
     uint8_t  ecd;
     struct   spi_cfg cfg;
     /* pull current configuration from the hardware -- allows for warm restore so to speak */
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     if ( argc < 1 )
     { /* read */
         printf( "SPI ECD: %g sec\n", ( cfg.end_delay_ns * 1.0e-9 ) );
     }
     else
     { /* write */
         request_sec = atof( argv[0] );
         error_code = SPI_Calculate_End_Cycle_Delay( SPI_Calculate_Half_Clock_Interval_Sec( cfg.half_clock_interval ),
                                                     request_sec,
                                                     &actual_sec,
                                                     &error,
                                                     &ecd
                                                   );
         if ( error_code ) return error_code;
         cfg.end_delay_ns = actual_sec * 1.0e9;
         /* commit configuration to hardware */
         error_code = SPI_Configuration_Set( &cfg );
         if ( error_code ) return error_code;
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_Get (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2477 of file idi.c.
References SPI_Configuration_Get(), and SPI_Report_Configuration_Text().
 { /*  idi spi cfg */
     int     error_code;
     struct  spi_cfg cfg;
     (void)  argc;
     (void)  argv;
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     error_code = SPI_Report_Configuration_Text( &cfg, stdout );
     if ( error_code ) return error_code;
     printf( "\n" );
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_Mode (int argc, char * argv[]) static
CPOL CPHA MODE 0 0 0 1 0 1 2 1 0 3 1 1.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2586 of file idi.c.
References spi_cfg::sclk_phase, spi_cfg::sclk_polarity, SPI_Configuration_Get(), and SPI_Configuration_Set().
 { /*  idi spi mode [0/1/2/3] */
     int      error_code;
     int      mode;
     struct   spi_cfg cfg;
     /* pull current configuration from the hardware -- allows for warm restore so to speak */
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     if ( argc < 1 )
     { /* read */
         if      ( (false == cfg.sclk_polarity ) && (false == cfg.sclk_phase) ) mode = 0;
         else if ( (false == cfg.sclk_polarity ) && (true  == cfg.sclk_phase) ) mode = 1;
         else if ( (true  == cfg.sclk_polarity ) && (false == cfg.sclk_phase) ) mode = 2;
         else if ( (true  == cfg.sclk_polarity ) && (true  == cfg.sclk_phase) ) mode = 3;
         printf( "SPI MODE: %d\n", mode );
     }
     else
     { /* write */
         mode = (int) strtol( argv[0], NULL, 0 );
         switch ( mode )
         {
             case 0: cfg.sclk_polarity = false;  cfg.sclk_phase = false;     break;
             case 1: cfg.sclk_polarity = false;  cfg.sclk_phase = true;      break;
             case 2: cfg.sclk_polarity = true;   cfg.sclk_phase = false;     break;
             case 3: cfg.sclk_polarity = true;   cfg.sclk_phase = true;      break;
         }
         /* commit configuration to hardware */
         error_code = SPI_Configuration_Set( &cfg );
         if ( error_code ) return error_code;
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_SDI_Polarity (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2627 of file idi.c.
References spi_cfg::sdi_polarity, SPI_Configuration_Get(), SPI_Configuration_Set(), and String_To_Bool().
 { /*  idi spi sdi [<true/1/false/0>] */
     int      error_code;
 //  BOOL     value;
     struct   spi_cfg cfg;
     /* pull current configuration from the hardware -- allows for warm restore so to speak */
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     if ( argc < 1 )
     { /* read */
         printf( "SPI SDI POLARITY: %s\n", cfg.sdi_polarity ? "true" : "false" );
     }
     else
     { /* write */
         cfg.sdi_polarity = String_To_Bool( argv[0] );
         /* commit configuration to hardware */
         error_code = SPI_Configuration_Set( &cfg );
         if ( error_code ) return error_code;
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_SDIO_Wrap (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2687 of file idi.c.
References spi_cfg::sdio_wrap, SPI_Configuration_Get(), SPI_Configuration_Set(), and String_To_Bool().
 { /*  idi spi wrap [<true/1/false/0>] */
     int      error_code;
 //  BOOL     value;
     struct   spi_cfg cfg;
     /* pull current configuration from the hardware -- allows for warm restore so to speak */
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     if ( argc < 1 )
     { /* read */
         printf( "SPI wrap: %s\n", cfg.sdio_wrap ? "true" : "false" );
     }
     else
     { /* write */
         cfg.sdio_wrap = String_To_Bool( argv[0] );
         /* commit configuration to hardware */
         error_code = SPI_Configuration_Set( &cfg );
         if ( error_code ) return error_code;
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Config_SDO_Polarity (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2657 of file idi.c.
References spi_cfg::sdo_polarity, SPI_Configuration_Get(), SPI_Configuration_Set(), and String_To_Bool().
 { /*  idi spi sdo [<true/1/false/0>] */
     int      error_code;
 //  BOOL     value;
     struct   spi_cfg cfg;
     /* pull current configuration from the hardware -- allows for warm restore so to speak */
     error_code = SPI_Configuration_Get( &cfg );
     if ( error_code ) return error_code;
     if ( argc < 1 )
     { /* read */
         printf( "SPI SDO POLARITY: %s\n", cfg.sdo_polarity ? "true" : "false" );
     }
     else
     { /* write */
         cfg.sdo_polarity = String_To_Bool( argv[0] );
         /* commit configuration to hardware */
         error_code = SPI_Configuration_Set( &cfg );
         if ( error_code ) return error_code;
         printf( "OK\n" );
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_Data (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2813 of file idi.c.
References HEX_DUMP_BYTES_PER_LINE, Hex_Dump_Line(), SPI_Data_Write_Read(), and SPI_FIFO_SIZE.
 { /*  idi spi data [byte] [character] ... */
     int                 error_code;
     size_t              index;
     size_t              count;
     size_t              transfer_count; /* */
     size_t              lines;
     uint8_t *           bp;             /* buffer pointer */
     uint8_t             tx_buffer[SPI_FIFO_SIZE];
     uint8_t             rx_buffer[SPI_FIFO_SIZE];
     if ( argc < 1 ) return -EC_PARAMETER;
     index = 1;
     transfer_count = argc - 1;
     if ( transfer_count > SPI_FIFO_SIZE )
     {
         transfer_count = SPI_FIFO_SIZE;
         printf( "Warning: ignored %d values\n", argc - 1 - SPI_FIFO_SIZE );
     }
     count = transfer_count;
     while ( count != 0 )
     {
         tx_buffer[index-1] = (uint8_t) strtol( argv[index], NULL, 0 );
         count--; index++;
     }
     error_code = SPI_Data_Write_Read( sizeof( uint8_t ), transfer_count, tx_buffer, transfer_count, rx_buffer );
     if ( error_code ) return error_code;
     lines = transfer_count / HEX_DUMP_BYTES_PER_LINE;
     if ( 0 == ( transfer_count - lines * HEX_DUMP_BYTES_PER_LINE ) ) lines = lines - 1;
     for ( index = 0; index <= lines; index++ )
     {
         bp = &(rx_buffer[index * HEX_DUMP_BYTES_PER_LINE]);
         if ( transfer_count < HEX_DUMP_BYTES_PER_LINE )
         {
             Hex_Dump_Line( 0, transfer_count, bp, stdout );
         }
         else
         {
             Hex_Dump_Line( 0, HEX_DUMP_BYTES_PER_LINE, bp, stdout );
         }
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_FIFO (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2865 of file idi.c.
References HEX_DUMP_BYTES_PER_LINE, Hex_Dump_Line(), SPI_Commit(), SPI_FIFO_Read(), SPI_FIFO_SIZE, SPI_FIFO_Write(), SPI_Status_Read_FIFO_Is_Not_Empty(), SPI_Status_Write_FIFO_Is_Not_Empty(), strcmpi, and String_To_Bool().
 { /*  idi spi data [byte] [character] ... */
     int                 error_code;
     int                 index;
     int                 count;
     int                 read_count; /* */
     uint8_t             data_temp;
     uint8_t             tx_buffer[SPI_FIFO_SIZE];
     uint8_t             rx_buffer[SPI_FIFO_SIZE];
     read_count = 0;
     if ( argc < 1 )
     {
         read_count = SPI_FIFO_SIZE;
     }
     else
     {
         if      ( 0 == strcmpi( "rx", argv[0] ) )
         {
             if ( argc > 1)
             {
                 if ( 0 == strcmpi( "all", argv[1] ) ) read_count = SPI_FIFO_SIZE;
                 else read_count = (int) strtol( argv[1], NULL, 0 );
             }
         }
         else if ( 0 == strcmpi( "tx", argv[0] ) )
         {
             char * endptr;
             index = 1;
             count = argc - 1;
             if ( count > SPI_FIFO_SIZE )
             {
                 count = SPI_FIFO_SIZE;
                 printf( "Warning: ignored %d values\n", argc - 1 - SPI_FIFO_SIZE );
             }
             while ( count > 0 )
             {
                 data_temp = (uint8_t) strtol( argv[index], &endptr, 0 );
                 if ( endptr == argv[index] ) data_temp = (uint8_t) argv[index][0];
                 tx_buffer[index-1] = data_temp;
                 count--; index++;
             }
             error_code = SPI_FIFO_Write( (void *) tx_buffer, sizeof( uint8_t ), count, NULL );
             if ( error_code ) return error_code;
             printf( "OK\n" );
             return error_code;
         }
         else if ( 0 == strcmpi( "commit", argv[0] ) )
         {
             if ( argc > 2 )
             {
                 if ( String_To_Bool( argv[1] ) ) SPI_Commit( 0xFF );
                 else                             SPI_Commit( 0x00 );
                 printf( "OK\n" );
                 error_code = SUCCESS;
             }
             else
             {
 //TODO: add ability to read-back the chip select under certain conditions.
                 error_code = -EC_PARAMETER_MISSING;
             }
             return error_code;
         }
     }
     /* wait for transmit data to empty out */
     while ( SPI_Status_Write_FIFO_Is_Not_Empty() ) { /* do nothing */ }
     if ( read_count > 0 )
     {
         int       lines;
         uint8_t * bp; /* buffer pointer */
         if ( SPI_Status_Read_FIFO_Is_Not_Empty() )
         {
             error_code = SPI_FIFO_Read( (void *) rx_buffer, sizeof( uint8_t ), read_count, NULL );
             if ( error_code ) return error_code;
             lines = read_count / HEX_DUMP_BYTES_PER_LINE;
             if ( 0 == ( read_count - lines * HEX_DUMP_BYTES_PER_LINE ) ) lines = lines - 1;
             for ( index = 0; index <= lines; index++ )
             {
                 bp = &(rx_buffer[index * HEX_DUMP_BYTES_PER_LINE]);
                 if ( read_count < HEX_DUMP_BYTES_PER_LINE )
                 {
                     Hex_Dump_Line( 0, read_count, bp, stdout );
                 }
                 else
                 {
                     Hex_Dump_Line( 0, HEX_DUMP_BYTES_PER_LINE, bp, stdout );
                 }
             }
         }
         else
         {
             printf( "FIFO Empty\n" );
         }
     }
     return SUCCESS;
 }
static int IDI_CMD__SPI_ID (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2461 of file idi.c.
References SPI_ID_Get().
 { /*  idi spi id */
     uint16_t    id;
     (void)      argc;
     (void)      argv;
     SPI_ID_Get( &id );
     printf( "SPI ID: 0x%04X\n", id );
     return SUCCESS;
 }
static int IDI_CMD__SPI_Status (int argc, char * argv[]) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 2775 of file idi.c.
References SPI_Report_Status_Text(), SPI_Status_Read(), SPI_Status_Write(), and strcmpi.
 { /*  idi spi status [rx] [tx] ...  */
     int                 error_code;
     int                 index;
     struct spi_status   status;
     if ( argc < 1 )
     {
         error_code = SPI_Status_Read( &status );
         if ( error_code ) return error_code;
         SPI_Report_Status_Text( &status, stdout );
     }
     else
     {
         for ( index = 0; index < argc; index++ )
         {
             if ( 0 == strcmpi( "rx", argv[index] ) )
             {
                 error_code = SPI_Status_Read( &status );
                 if ( error_code ) return error_code;
                 SPI_Report_Status_Text( &status, stdout );
             }
             else if ( 0 == strcmpi( "tx", argv[index] ) )
             {
                 error_code = SPI_Status_Write( &status );
                 if ( error_code ) return error_code;
                 SPI_Report_Status_Text( &status, stdout );
             }
         }
     }
     return SUCCESS;
 }
int IDI_Command_Line_Digital_Input (int argc, char * argv[])
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3425 of file idi.c.
References command_line::cmd_fnc, command_line::name, and strcmpi.
Referenced by IDI_Command_Line_Main().
 { /*  idi din <channel/all>  */
     int         error_code;
     int         index;
     int         argc_new;
     char **     argv_new;
     char *      endptr;
     //int           channel;
     if ( argc < 1 ) return -EC_NOT_FOUND;
     error_code = -EC_SYNTAX;
     //channel = (int) strtol( argv[0], &endptr, 0 );
     strtol( argv[0], &endptr, 0 ); /* just want to know where it fails */
     if ( argv[0] != endptr )
     {  /* assume channel number */
         error_code = (* idi_cmd_din[0].cmd_fnc )( argc, argv );
     }
     else
     { /* otherwise a normal command */
         index = 0;
         while ( NULL != idi_cmd_din[index].cmd_fnc )
         {
             if ( 0 == strcmpi( idi_cmd_din[index].name, argv[0] )  )
             {
                 argv_new = &(argv[1]);
                 argc_new = argc - 1;
                 error_code = (* idi_cmd_din[index].cmd_fnc )( argc_new, argv_new );
                 break;
             }
             index++;
         }
     }
     return error_code;
 }
int IDI_Command_Line_FRAM (int argc, char * argv[])
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3232 of file idi.c.
References command_line::cmd_fnc, command_line::name, and strcmpi.
Referenced by IDI_Command_Line_Main().
 {
     int         error_code;
     int         index;
     int         argc_new;
     char **     argv_new;
     if ( argc < 1 ) return -EC_NOT_FOUND;
     index = 0;
     while ( NULL != idi_cmd_fram[index].cmd_fnc )
     {
         if ( 0 == strcmpi( idi_cmd_fram[index].name, argv[0] )  )
         {
             argv_new = &(argv[1]);
             argc_new = argc - 1;
             error_code = (* idi_cmd_fram[index].cmd_fnc )( argc_new, argv_new );
             break;
         }
         index++;
     }
     return error_code;
 }
int IDI_Command_Line_Main (int argc, char * argv[])
Processes and dispatches the top level of the command and passes the remaining string list onto specialized functions to further process arguments. If no command is specified then a help output is produced.
Parameters
[in] argc number of arguments including the executable file name
[in] argv list of string arguments lex'd from the command line
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 3651 of file idi.c.
References IDI_Command_Line_Digital_Input(), IDI_Command_Line_FRAM(), IDI_Command_Line_Register_Transaction(), IDI_Command_Line_Set(), IDI_Command_Line_SPI(), IDI_Register_Report_CSV(), and strcmpi.
Referenced by main().
 {
     int     error_code;
     int     index;
     int     argc_new;
     char ** argv_new;
     index = 0; /* offset into the string list */
     if ( argc > 0 /* at least one */ )
     {
         if      ( 0 == strcmpi( "set", argv[index] ) )
         { /* idi set .... */
             index++;
             argv_new = &(argv[index]);
             argc_new = argc - index;
             error_code = IDI_Command_Line_Set( argc_new, argv_new );
             if ( error_code ) goto IDI_COMMAND_LINE_MAIN_TERMINATE;
         }
         else if ( 0 == strcmpi( "dump", argv[index] ) )
         { /* idi dump .... */
             FILE * fd_out;
             index++;
             if ( argc > 2 )
             {
                 fd_out = fopen( argv[index], "w" );
                 if ( NULL == fd_out ) fd_out = stdout;
             }
             else
             {
                 fd_out = stdout;
             }
             error_code = IDI_Register_Report_CSV( definitions, fd_out );
             if ( (argc > 2) && (NULL != fd_out) && (stdout != fd_out) )
             {
                 fclose( fd_out );
             }
             if ( error_code ) goto IDI_COMMAND_LINE_MAIN_TERMINATE;
         }
         else if ( 0 == strcmpi( "spi", argv[index] ) )
         { /* idi spi .... */
             // idi spi id
             // idi spi
             index++;
             argv_new = &(argv[index]);
             argc_new = argc - index;
             error_code = IDI_Command_Line_SPI( argc_new, argv_new );
             if ( error_code ) goto IDI_COMMAND_LINE_MAIN_TERMINATE;
         }
         else if ( 0 == strcmpi( "fram", argv[index] ) )
         { /* idi fram .... */
             index++;
             argv_new = &(argv[index]);
             argc_new = argc - index;
             error_code = IDI_Command_Line_FRAM( argc_new, argv_new );
             if ( error_code ) goto IDI_COMMAND_LINE_MAIN_TERMINATE;
         }
         else if ( 0 == strcmpi( "din", argv[index] ) )
         { /* idi din .... */
             index++;
             argv_new = &(argv[index]);
             argc_new = argc - index;
             error_code = IDI_Command_Line_Digital_Input( argc_new, argv_new );
             if ( error_code ) goto IDI_COMMAND_LINE_MAIN_TERMINATE;
         }
         else
         {
             argv_new = &(argv[index]);
             argc_new = argc - index;
             error_code = IDI_Command_Line_Register_Transaction( argc_new, argv_new );
             if ( error_code ) goto IDI_COMMAND_LINE_MAIN_TERMINATE;
         }
     }
 IDI_COMMAND_LINE_MAIN_TERMINATE:
     return error_code;
 }
int IDI_Command_Line_Register_Transaction (int argc, char * argv[])
Either reads or writes a register using the form: idi <register acronym>=""> [].
If
is not include, then it is assumed to be a read. If value is included, then a write to the specified register is made.
This function uses the definitions[] array which is global and built from IDI_REGISTER_SET_DEFINITION macro which is a nicely organized register list.
Parameters
[in] argc number of arguments including the executable file name
[in] argv list of string arguments lex'd from the command line
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 3488 of file idi.c.
References IO_Read_U8(), IO_Write_U8(), REG_DIR_NONE, and strcmpi.
Referenced by IDI_Command_Line_Main().
 {
     int error_code;
     int index;
     int found;
     if ( argc < 1 ) return -EC_NOT_FOUND;
     found = -1;
     index =  0;
     while ( definitions[index].direction != REG_DIR_NONE )
     {
         if ( 0 == strcmpi( definitions[index].acronym, argv[0] )  )
         {
             found = index;
             break;
         }
         index++;
     }
     if ( found < 0 )
     {
         //printf( "ER: \n" );
         return  -EC_NOT_FOUND;
     }
     if ( argc < 2 )
     { /* read operation */
         uint8_t value;
         error_code = IO_Read_U8( definitions[index].symbol, &value );
         if ( SUCCESS == error_code )
         {
             printf( "RD: %s=0x%02X\n",  definitions[index].acronym, value );
         }
     }
     else
     {
         uint8_t value;
         value = (uint8_t) strtol( argv[1], NULL, 0 );
         error_code = IO_Write_U8( definitions[index].symbol, value );
         if ( SUCCESS == error_code )
         {
             printf( "WR: %s=0x%02X\n", definitions[index].acronym, value );
         }
     }
     return SUCCESS;
 }
int IDI_Command_Line_Set (int argc, char * argv[])
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3616 of file idi.c.
References command_line::cmd_fnc, command_line::name, and strcmpi.
Referenced by IDI_Command_Line_Main().
 {
     int         error_code;
     int         index;
     int         argc_new;
     char **     argv_new;
     if ( argc < 1 ) return -EC_NOT_FOUND;
     index = 0;
     while ( NULL != idi_cmd_fram[index].cmd_fnc )
     {
         if ( 0 == strcmpi( idi_cmd_main[index].name, argv[0] )  )
         {
             argv_new = &(argv[1]);
             argc_new = argc - 1;
             error_code = (* idi_cmd_main[index].cmd_fnc )( argc_new, argv_new );
             break;
         }
         index++;
     }
     return error_code;
 }
int IDI_Command_Line_SPI (int argc, char * argv[])
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3017 of file idi.c.
References command_line::cmd_fnc, command_line::name, and strcmpi.
Referenced by IDI_Command_Line_Main().
 {
     int         error_code;
     int         index;
     int         argc_new;
     char **     argv_new;
     if ( argc < 1 ) return -EC_NOT_FOUND;
     index = 0;
     while ( NULL != idi_cmd_spi[index].cmd_fnc )
     {
         if ( 0 == strcmpi( idi_cmd_spi[index].name, argv[0] )  )
         {
             argv_new = &(argv[1]);
             argc_new = argc - 1;
             error_code = (* idi_cmd_spi[index].cmd_fnc )( argc_new, argv_new );
             break;
         }
         index++;
     }
     return error_code;
 }
static int IDI_DIN_Channel_Get (size_t channel, BOOL * value) static
Obtains and reports a single digital input channel.
Parameters
[in] channel channel to be read out.
[out] value Pointer to the boolean value to be set based on the digital input value
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 992 of file idi.c.
References IDI_DIN_GROUP_SIZE, IDI_DIN_SHIFT_RIGHT, and IO_Read_U8().
Referenced by IDI_CMD__DIN_Channel().
 {
     size_t  group;
     size_t  bit;
     uint8_t reg_value;
     group = channel >> IDI_DIN_SHIFT_RIGHT;
     bit   = channel - group * IDI_DIN_GROUP_SIZE;
     IO_Read_U8( IDI_DI_GROUP0 + group, &reg_value );
     if ( 0 != ( reg_value & ( 0x01 << bit ) ) ) *value = true;
     else                                        *value = false;
     return SUCCESS;
 }
static int IDI_DIN_Group_Get (size_t group, uint8_t * value) static
Reads the selected digital input port (8-bits).
Parameters
[in] group the group, range is 0 to 5.
[out] value pointer to the destination for the data read out
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1018 of file idi.c.
References IO_Read_U8().
Referenced by IDI_CMD__DIN_All(), and IDI_CMD__DIN_Group().
 {
     IO_Read_U8( IDI_DI_GROUP0 + group, value );
     return SUCCESS;
 }
int IDI_DIN_ID_Get (uint16_t * id)
Obtains the DIN component (or board ID in this case) ID number.
Parameters
[out] id The 16-bit ID number
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 955 of file idi.c.
References ID_DIN, and IO_Read_U8().
Referenced by IDI_CMD__DIN_ID(), and IDI_DIN_IsNotPresent().
 {
     uint8_t     lsb, msb;
     IO_Read_U8( IDI_ID_LSB, &lsb );
     IO_Read_U8( IDI_ID_MSB, &msb );
     *id = ( ((uint16_t) msb) << 8 ) | ((uint16_t) lsb);
 #if defined( ID_ALWAYS_REPORT_AS_GOOD )
     *id = ID_DIN;
 #endif
     return SUCCESS;
 }
BOOL IDI_DIN_IsNotPresent (void)
Determines if the DIN component and/or board is present. Returns true if not present (i.e. error).
Returns
A zero is returned if present, otherwise a 1 is returned.
Definition at line 975 of file idi.c.
References ID_DIN, and IDI_DIN_ID_Get().
 {
     uint16_t id;
     IDI_DIN_ID_Get( &id );
     if (ID_DIN == id ) return 0;
     return 1;
 }
void IDI_Help (FILE * out)
Outputs a help listing to the user.
Definition at line 3746 of file idi.c.
References command_line::help, command_line::name, and idi_dataset::svn_revision_string.
Referenced by main().
 {
     int index;
     fprintf( out, "\n" );
     fprintf( out, "Isolated Digital Input Test Code\n" );
     fprintf( out, "Apex Embedded Systems\n" );
     fprintf( out, "Revision: %s\n", idi_dataset.svn_revision_string );
     fprintf( out, "\n" );
     fprintf( out, "help - outputs help information\n" );
     fprintf( out, "\n" );
     fprintf( out, "loop - any command below can run in a loop until key pressed\n" );
     fprintf( out, "\n" );
     fprintf( out, "dump - outputs register information in a comma delimited format\n" );
     fprintf( out, "\n" );
     fprintf( out, "set  - Set/Get main parameters.\n" );
     index = 0;
     while ( NULL != idi_cmd_main[index].help )
     {
     fprintf( out, "       %8s - %s\n", idi_cmd_main[index].name, idi_cmd_main[index].help );
     index++;
     }
     fprintf( out, "\n" );
     fprintf( out, "spi  - SPI related functions\n" );
     index = 0;
     while ( NULL != idi_cmd_spi[index].help )
     {
     fprintf( out, "       %8s - %s\n", idi_cmd_spi[index].name, idi_cmd_spi[index].help );
     index++;
     }
     fprintf( out, "\n" );
     fprintf( out, "fram - FRAM related functions\n" );
     index = 0;
     while ( NULL != idi_cmd_fram[index].help )
     {
     fprintf( out, "       %8s - %s\n", idi_cmd_fram[index].name, idi_cmd_fram[index].help );
     index++;
     }
     fprintf( out, "\n" );
     fprintf( out, "din  - Digital input related functions\n" );
     index = 0;
     while ( NULL != idi_cmd_din[index].help )
     {
     fprintf( out, "       %8s - %s\n", idi_cmd_din[index].name, idi_cmd_din[index].help );
     index++;
     }
     fprintf( out, "\n" );
 }
int IDI_Initialization (void)
Runs upon application startup. It restores the idi_dataset data structure or if the file cannot be found it will simply initialize those parameters to default values.
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 3836 of file idi.c.
References idi_dataset::bank_previous, idi_dataset::base_address, IDI_BANK_0, idi_svn_revision_string, and idi_dataset::svn_revision_string.
Referenced by main().
 {
     FILE * fd;
     /* restore the data set, if we can otherwise initialize with defaults */
     fd = fopen( "idi_init.bin", "r" );
     if ( NULL == fd )
     { /* defaults */
         memset( &idi_dataset, 0, sizeof(struct idi_dataset) );
         idi_dataset.base_address        = 0xff00;
         idi_dataset.bank_previous       = IDI_BANK_0;
     }
     else
     { /* read in dataset */
         fread( &idi_dataset, 1, sizeof( struct idi_dataset ), fd );
         fclose( fd );
     }
     idi_dataset.svn_revision_string = idi_svn_revision_string;
     return SUCCESS;
 }
int IDI_Register_Report_CSV (const struct reg_definition * table, FILE * out)
Outputs a human readable CSV to the desired output file or stdout.
Parameters
[in] table register definition table or data structure array
[in] out destination of the human readable text to specified file or terminal.
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 485 of file idi.c.
References IDI_BANK_0, IDI_BANK_1, IDI_BANK_2, IDI_BANK_3, IDI_BANK_4, IDI_BANK_5, IDI_BANK_6, IDI_BANK_7, IDI_BANK_NONE, IDI_BANK_UNDEFINED, REG_DIR_NONE, REG_DIR_READ, REG_DIR_READ_WRITE, and REG_DIR_WRITE.
Referenced by IDI_Command_Line_Main().
 {
     int index = 0;
     fprintf( out, "\"acronym\",\"symbol\",\"bank\",\"direction\",\"physical_offset\"\n" );
     do
     {
         fprintf( out, "\"%s\",", table[index].acronym     );
         fprintf( out, "\"%s\",", table[index].symbol_name );
         switch( table[index].bank )
         {
         case IDI_BANK_0:            fprintf( out, "IDI_BANK_0" );           break;
         case IDI_BANK_1:            fprintf( out, "IDI_BANK_1" );           break;
         case IDI_BANK_2:            fprintf( out, "IDI_BANK_2" );           break;
         case IDI_BANK_3:            fprintf( out, "IDI_BANK_3" );           break;
         case IDI_BANK_4:            fprintf( out, "IDI_BANK_4" );           break;
         case IDI_BANK_5:            fprintf( out, "IDI_BANK_5" );           break;
         case IDI_BANK_6:            fprintf( out, "IDI_BANK_6" );           break;
         case IDI_BANK_7:            fprintf( out, "IDI_BANK_7" );           break;
         case IDI_BANK_NONE:         fprintf( out, "IDI_BANK_NONE" );        break;
         case IDI_BANK_UNDEFINED:    fprintf( out, "IDI_BANK_UNDEFINED" );   break;
         }
         fprintf( out, "," );
         switch( table[index].direction )
         {
             case REG_DIR_NONE:          fprintf( out, "REG_DIR_NONE" );         break;
             case REG_DIR_READ:          fprintf( out, "REG_DIR_READ" );         break;
             case REG_DIR_WRITE:         fprintf( out, "REG_DIR_WRITE" );        break;
             case REG_DIR_READ_WRITE:    fprintf( out, "REG_DIR_READ_WRITE" );   break;
         }
         fprintf( out, "," );
         fprintf( out, "\"%d\"", table[index].physical_offset );
         fprintf( out, "\n\r" ); /* separate so we have flexibility to re-organize columns */
         index++;
     } while ( definitions[index].direction != REG_DIR_NONE );
     return SUCCESS;
 }
static const char* IDI_Symbol_Name_Bank (IDI_BANK_ENUM bank) static
Outputs a human readable CSV to the desired output file or stdout.
Parameters
[in] bank the bank enumerated value written to the bank register.
Returns
a string that describes the selected bank.
Definition at line 456 of file idi.c.
References IDI_BANK_0, IDI_BANK_1, IDI_BANK_2, IDI_BANK_3, IDI_BANK_4, IDI_BANK_5, IDI_BANK_6, IDI_BANK_7, IDI_BANK_NONE, idi_bank_symbol_names, and IDI_BANK_UNDEFINED.
Referenced by IO_Read_U8(), and IO_Write_U8().
 {
     int index;
     switch( bank )
     {
         case IDI_BANK_0:            index = 0;  break;
         case IDI_BANK_1:            index = 1;  break;
         case IDI_BANK_2:            index = 2;  break;
         case IDI_BANK_3:            index = 3;  break;
         case IDI_BANK_4:            index = 4;  break;
         case IDI_BANK_5:            index = 5;  break;
         case IDI_BANK_6:            index = 6;  break;
         case IDI_BANK_7:            index = 7;  break;
         case IDI_BANK_NONE:         index = 8;  break;
         case IDI_BANK_UNDEFINED:    index = 9;  break;
     }
     return idi_bank_symbol_names[index];
 }
int IDI_Termination (void)
Runs upon application exit. It saves the idi_dataset data structure.
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 3809 of file idi.c.
Referenced by main().
 {
     FILE * fd;
     /* save the data set */
     fd = fopen( "idi_init.bin", "w" );
     if ( NULL == fd )
     { /* defaults */
         return -EC_INIT_FILE;
     }
     else
     { /* read in dataset */
         fwrite( &idi_dataset, 1, sizeof( struct idi_dataset ), fd );
         fclose( fd );
     }
     return SUCCESS;
 }
static BOOL IO_Direction_IsNotValid (IDI_REG_ENUM location, REG_DIR_ENUM direction) static
Looks up in the register definitions list for the ports possible read/write directions.
Parameters
[in] location the enumerated register symbol. The enumerated symbol is composed of offset and bank information used to determine the final address information.
[in] direction The desired direction that is to run
Returns
A false is returned if the direction is valid, otherwise a true is returned
Definition at line 718 of file idi.c.
References REG_DIR_NONE.
Referenced by IO_Read_U8(), and IO_Write_U8().
 {
     int index;
     index =  0;
     while ( definitions[index].direction != REG_DIR_NONE )
     {
         if ( location == definitions[index].symbol  )
         {
             if ( definitions[index].direction & direction ) return false;
             else                                            return true;
         }
         index++;
     }
     return true;
 }
static char* IO_Get_Symbol_Name (IDI_REG_ENUM location) static
Translates a register enumerated symbol into a string that is the same as the enumerated symbol used throughout this code base.
Parameters
[in] location The enumerated symbol representing the register.
Returns
a human readable string of the symbol.
Definition at line 692 of file idi.c.
References REG_DIR_NONE, and reg_definition::symbol_name.
Referenced by IO_Read_U8(), and IO_Write_U8().
 {
     int index;
     index =  0;
     while ( definitions[index].direction != REG_DIR_NONE )
     {
         if ( location == definitions[index].symbol  )
         {
             return definitions[index].symbol_name;
         }
         index++;
     }
     return NULL;
 }
void IO_Read_U16_Address_Fixed (IDI_REG_ENUM location, uint16_t * value)
Reads uint16_t from I/O ports in a uint8_t succession to the same address location. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
Parameters
[in] location the enumerated register symbol. The enumerated symbol is composed of offset and bank information used to determine the final address information.
[in] value The pointer to the destination of the read uint16_t value.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 931 of file idi.c.
References IO_Read_U8().
 {
 //TODO: assumes little endian.
     uint8_t lsb, msb;
     IO_Read_U8( (IDI_REG_ENUM)(((int) location) + 0), &lsb );
     IO_Read_U8( (IDI_REG_ENUM)(((int) location) + 0), &msb );
     *value = ( ((uint16_t) msb) << 8 ) | ( ((uint16_t) lsb) & 0xFF );
 }
void IO_Read_U16_Address_Increment (IDI_REG_ENUM location, uint16_t * value)
Reads uint16_t from I/O ports in a uint8_t succession incrementing the offset address. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
Parameters
[in] location the enumerated register symbol. The enumerated symbol is composed of offset and bank information used to determine the final address information.
[in] value The pointer to the destination of the read uint16_t value.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 887 of file idi.c.
References IO_Read_U8().
 {
 //TODO: assumes little endian.
     uint8_t lsb, msb;
     IO_Read_U8( (IDI_REG_ENUM)(((int) location) + 0), &lsb );
     IO_Read_U8( (IDI_REG_ENUM)(((int) location) + 1), &msb );
     *value = ( ((uint16_t) msb) << 8 ) | ( ((uint16_t) lsb) & 0xFF );
 }
int IO_Read_U8 (IDI_REG_ENUM location, uint8_t * value)
Reads uint8_t from I/O port. Macros are used to guide the target implementation.
Parameters
[in] location the enumerated register symbol. The enumerated symbol is composed of offset and bank information used to determine the final address information.
[in] value The pointer to the destination of the read uint8_t value.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 802 of file idi.c.
References idi_dataset::bank_previous, idi_dataset::base_address, IDI_BANK_NONE, IDI_Symbol_Name_Bank(), IO_Direction_IsNotValid(), IO_Get_Symbol_Name(), idi_dataset::io_report, idi_dataset::io_simulate, REG_DIR_READ, REG_LOCATION_BANK_GET, and REG_LOCATION_OFFSET_GET.
Referenced by IDI_Command_Line_Register_Transaction(), IDI_DIN_Channel_Get(), IDI_DIN_Group_Get(), IDI_DIN_ID_Get(), IO_Read_U16_Address_Fixed(), IO_Read_U16_Address_Increment(), SPI_Configuration_Chip_Select_Behavior_Get(), SPI_Configuration_Chip_Select_Behavior_Set(), SPI_Configuration_Get(), SPI_Data_Write_Read_Helper(), SPI_FIFO_Read(), SPI_ID_Get(), SPI_Status_Read(), SPI_Status_Read_FIFO_Is_Not_Empty(), SPI_Status_Read_FIFO_Status(), SPI_Status_Write(), SPI_Status_Write_FIFO_Is_Full(), SPI_Status_Write_FIFO_Is_Not_Empty(), and SPI_Status_Write_FIFO_Status().
 {
     uint8_t     bank;
     int         offset;
     int         address;
 #if defined( IDI_IO_DIRECTION_TEST )
     if ( IO_Direction_IsNotValid( location, REG_DIR_READ ) )
     {
         printf( "IO_Read_U8: %s, error in direction\n", IO_Get_Symbol_Name( location ) );
         return -EC_DIRECTION;
     }
 #endif
     bank   = (uint8_t) REG_LOCATION_BANK_GET( location );
     if ( ( IDI_BANK_NONE != bank ) && ( bank != idi_dataset.bank_previous ) )
     {   /* write to bank register only if different -- don't bother even checking it, will take too much time. */
         offset = (int) REG_LOCATION_OFFSET_GET( IDI_BANK );
         address = ((int) idi_dataset.base_address) + offset;
         idi_dataset.bank_previous = bank;
         if ( !idi_dataset.io_simulate )
         {
 #if defined( __MSDOS__ )
         outportb( address, bank );
 #endif
         }
         if ( ( idi_dataset.io_report ) || ( idi_dataset.io_simulate ) )
         {
         printf( "IO_Read_U8: %s, address = 0x%04X, bank = %s\n", IO_Get_Symbol_Name( IDI_BANK ), address, IDI_Symbol_Name_Bank( bank ) );
         }
     }
     offset = (int) REG_LOCATION_OFFSET_GET(location);
     address = ((int) idi_dataset.base_address) + offset;
     if ( !idi_dataset.io_simulate )
     {
 #if defined( __MSDOS__ )
     *value = inportb( address );
 #endif
     }
     if ( ( idi_dataset.io_report ) || ( idi_dataset.io_simulate ) )
     {
     printf( "IO_Read_U8: %s, address = 0x%04X, ", IO_Get_Symbol_Name( location ), address );
 #if defined( __MSDOS__ )
     printf( "value = 0x%02X\n", *value );
 #else
     printf( "value = unknown\n" );
 #endif
     }
     return SUCCESS;
 }
void IO_Write_U16_Address_Fixed (IDI_REG_ENUM location, uint16_t value)
Writes uint16_t to I/O ports in a uint8_t succession to the same address location. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
Parameters
[in] location the enumerated register symbol. The enumerated symbol is composed of offset and bank information used to determine the final address information.
[in] value The uint16_t value to be written to the I/O register
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 910 of file idi.c.
References IO_Write_U8().
 {
 //TODO: assumes little endian.
     IO_Write_U8( (IDI_REG_ENUM)(((int) location) + 0), (uint8_t)(     value      & 0xFF ) );
     IO_Write_U8( (IDI_REG_ENUM)(((int) location) + 0), (uint8_t)( ( value >> 8 ) & 0xFF ) );
 }
void IO_Write_U16_Address_Increment (IDI_REG_ENUM location, uint16_t value)
Writes uint16_t to I/O ports in a uint8_t succession incrementing the offset address. Macros are used to guide the target implementation. In this case, bus width (which we typcially refer to the port width, which is different than register width) is assumed to be byte (uint8_t) wide.
Parameters
[in] location the enumerated register symbol. The enumerated symbol is composed of offset and bank information used to determine the final address information.
[in] value The uint16_t value to be written to the I/O register
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 866 of file idi.c.
References IO_Write_U8().
 {
 //TODO: assumes little endian.
     IO_Write_U8( (IDI_REG_ENUM)(((int) location) + 0), (uint8_t)(   value        & 0xFF ) );
     IO_Write_U8( (IDI_REG_ENUM)(((int) location) + 1), (uint8_t)( ( value >> 8 ) & 0xFF ) );
 }
int IO_Write_U8 (IDI_REG_ENUM location, uint8_t value)
Writes uint8_t to I/O port. Macros are used to guide the target implementation.
Parameters
[in] location the enumerated register symbol. The enumerated symbol is composed of offset and bank information used to determine the final address information.
[in] value The data to be written out.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 746 of file idi.c.
References idi_dataset::bank_previous, idi_dataset::base_address, IDI_BANK_NONE, IDI_Symbol_Name_Bank(), IO_Direction_IsNotValid(), IO_Get_Symbol_Name(), idi_dataset::io_report, idi_dataset::io_simulate, REG_DIR_WRITE, REG_LOCATION_BANK_GET, and REG_LOCATION_OFFSET_GET.
Referenced by IDI_Command_Line_Register_Transaction(), IO_Write_U16_Address_Fixed(), IO_Write_U16_Address_Increment(), SPI_Commit(), SPI_Configuration_Chip_Select_Behavior_Set(), SPI_Configuration_Set(), SPI_Data_Write_Read_Helper(), and SPI_FIFO_Write().
 {
     uint8_t     bank;
     uint8_t     offset;
     uint16_t    address;
 #if defined( IDI_IO_DIRECTION_TEST )
     if ( IO_Direction_IsNotValid( location, REG_DIR_WRITE ) )
     {
         printf( "IO_Write_U8: %s, error in direction\n", IO_Get_Symbol_Name( location ) );
         return -EC_DIRECTION;
     }
 #endif
     bank   = (uint8_t) REG_LOCATION_BANK_GET( location );
     if ( ( IDI_BANK_NONE != bank ) && ( bank != idi_dataset.bank_previous ) )
     {   /* write to bank register only if different -- don't bother even checking it, will take too much time. */
         offset = (uint8_t) REG_LOCATION_OFFSET_GET( IDI_BANK );
         address = idi_dataset.base_address + offset;
         idi_dataset.bank_previous = bank;
         if ( !idi_dataset.io_simulate )
         {
 #if defined( __MSDOS__ )
         outportb( address, bank );
 #endif
         }
         if ( ( idi_dataset.io_report ) || ( idi_dataset.io_simulate ) )
         {
         printf( "IO_Write_U8: %s, address = 0x%04X, bank = %s\n", IO_Get_Symbol_Name( IDI_BANK ), address, IDI_Symbol_Name_Bank( bank ) );
         }
     }
     offset = (uint8_t) REG_LOCATION_OFFSET_GET(location);
     address = idi_dataset.base_address + offset;
     if ( !idi_dataset.io_simulate )
     {
 #if defined( __MSDOS__ )
     outportb( address, value );
 #endif
     }
     if ( ( idi_dataset.io_report ) || ( idi_dataset.io_simulate ) )
     {
     printf( "IO_Write_U8: %s, address = 0x%04X, value = 0x%02X\n", IO_Get_Symbol_Name( location ), address, value );
     }
     return SUCCESS;
 }
int main (int argc, char * argv[])
Processes and dispatches the top level of the command and passes the remaining string list onto specialized functions to further process arguments. If no command is specified then a help output is produced.
Parameters
[in] argc number of arguments including the executable file name
[in] argv list of string arguments lex'd from the command line
Returns
SUCCESS (0) if no errors encountered, otherwise errors are reported as a negative value.
Definition at line 3871 of file idi.c.
References Character_Get(), EC_Code_To_Human_Readable(), IDI_Command_Line_Main(), IDI_Help(), IDI_Initialization(), IDI_Termination(), and strcmpi.
 {
     //int index;
     //int count;
     int     error_code;
     int     index;
     int     argc_new;
     char ** argv_new;
 /* used only for Win7 debugging sessions with cygwin */
 #if(1)
     setvbuf(stdout, NULL, _IONBF, 0);
     setvbuf(stderr, NULL, _IONBF, 0);
 #endif
     error_code = IDI_Initialization();
     if ( error_code ) goto Main_Termination;
 //      printf( "Hello\n");
 //      return SUCCESS;
 #if(0)
     count = argc;
     index = 0;     /* OK, zero value is name of executable file  */
     while ( count > 0 )
     {
         printf( "index = %d, str = <%s>\n", index, argv[index] );
         index++;
         count--;
     }
 #endif
     index = 1;
     if ( argc > 1 )
     {
         if      ( 0 == strcmpi( "help", argv[index]) )
         {
             IDI_Help( stdout );
         }
         else if ( 0 == strcmpi( "loop", argv[index]) )
         { /* loop until key is pressed */
             if ( argc > 2 )
             {
                 index++;
                 while ( !Character_Get(NULL) )
                 { /* assumes that all functions utilize arguments in read only fashion */
                     argv_new = &(argv[index]);
                     argc_new = argc - index;
                     error_code = IDI_Command_Line_Main( argc_new, argv_new );
                     if ( error_code ) goto Main_Termination_Error_Codes;
                 }
             }
         }
         else
         {
             argv_new = &(argv[index]);
             argc_new = argc - index;
             error_code = IDI_Command_Line_Main( argc_new, argv_new );
             if ( error_code ) goto Main_Termination_Error_Codes;
         }
     }
     else
     { /* produce help */
         IDI_Help( stdout );
     }
 Main_Termination:
     IDI_Termination();
     return error_code;
 Main_Termination_Error_Codes:
     IDI_Termination();
     printf( "ERROR: %d, %s\n",  error_code, EC_Code_To_Human_Readable( error_code ) );
     return error_code;
 }
int SPI_Calculate_Clock (double clock_request_hz, double * clock_actual_hz, double * error, uint16_t * hci)
Computes the SPI clock half clock register value given a requested SPI clock frequency. It will also produce a 'report' indicating the actual value (due to integer resolution) as well as a computed error between requested and actual. The eror can be used to determine whether timing constraints are met.
Parameters
[in] clock_request_hz Request clock frequency in Hertz. Example: 1.0e6 is 1MHz.
[in] clock_actual_hz Actual computed frequency. If this pointer is NULL, then it is not output.
[out] error Error between requested and actual. If this pointer is NULL, then it is not output.
[out] hci Half clock register value computed. If this pointer is NULL, then it is not output.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1121 of file idi.c.
References SPI_Calculate_Half_Clock().
Referenced by IDI_CMD__SPI_Config_Clock_Hz(), and SPI_Configuration_Set().
 {
     int      error_code;
     double   half_clock_request_sec;
     double   half_clock_actual_sec;
     double   error_internal;
     double   scratch;
     uint16_t hci_internal;
     half_clock_request_sec = 1.0 / ( 2.0 * clock_request_hz );
     error_code = SPI_Calculate_Half_Clock( half_clock_request_sec,
                                            &half_clock_actual_sec,
                                            &error_internal,
                                            &hci_internal
                                           );
     if ( error_code ) return error_code;
     /* compute actual frequency */
     scratch = 1.0 / ( 2.0 * half_clock_actual_sec );
     if ( NULL != error           ) *error           = ( scratch - clock_request_hz ) / clock_request_hz;
     if ( NULL != clock_actual_hz ) *clock_actual_hz = scratch;
     if ( NULL != hci             ) *hci             = (uint16_t) hci_internal;
     return SUCCESS;
 }
int SPI_Calculate_End_Cycle_Delay (double spi_half_clock_interval_sec, double delay_request_sec, double * delay_actual_sec, double * error, uint8_t * ecd)
Computes the time delay at the end of each byte transmitted. It will only output the parameters whose pointers are not NULL.
Parameters
[in] spi_half_clock_interval_sec Computed half clock interval in seconds
[in] delay_request_sec Requested time delay in seconds
[out] delay_actual_sec Pointer to actual time delay computed, if not NULL.
[out] error Pointer to error value computed, if not NULL.
[out] ecd Pointer to the computed end-cycle-delay, if not NULL.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1178 of file idi.c.
References CLOCK_PERIOD_SEC.
Referenced by IDI_CMD__SPI_Config_End_Cycle_Delay_Sec(), and SPI_Configuration_Set().
 {
     //double        delay_between_words_sec;
     double      scratch;
     int         ecd_temp;
     /* delay_sec = CLOCK_PERIOD_SEC * 4 + ECD * spi_half_clock_interval_sec  */
     scratch = ( delay_request_sec - 4.0 * CLOCK_PERIOD_SEC ) / spi_half_clock_interval_sec;
     ecd_temp = (int) scratch;
     if ( ( ecd_temp > 255 ) || ( ecd_temp < 0 ) ) return -EC_SPI_ECD_OUT_OF_RANGE;
     /* compute actual */
     scratch = CLOCK_PERIOD_SEC * 4.0 + ((double) ecd_temp) * spi_half_clock_interval_sec;
     if ( NULL != error            ) *error            = ( scratch - delay_request_sec ) / delay_request_sec;
     if ( NULL != delay_actual_sec ) *delay_actual_sec = scratch;
     if ( NULL != ecd              ) *ecd              = (uint8_t) ecd_temp;
     return SUCCESS;
 }
int SPI_Calculate_Half_Clock (double half_clock_request_sec, double * half_clock_actual_sec, double * error, uint16_t * hci)
Computes the half clock register value given a requested time interval. It will also produce a 'report' indicating the actual value (due to integer resolution) as well as a computed error between requested and actual. The error can be used to determine whether timing constraints are met.
Parameters
[in] half_clock_request_sec Request time interval in seconds. Example: 20.0e-6 is 20uS.
[in] half_clock_actual_sec Actual computed time. If this pointer is NULL, then it is not output.
[out] error Error between requested and actual. If this pointer is NULL, then it is not output.
[out] hci Half clock register value computed. If this pointer is NULL, then it is not output.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1084 of file idi.c.
References CLOCK_PERIOD_SEC.
Referenced by SPI_Calculate_Clock().
 {
     double      scratch;
     int         hci_temp;
     /* spi_half_clock_interval_sec = CLOCK_PERIOD_SEC * ( 4.0 + ( (double) hci ) ) */
     scratch = ( half_clock_request_sec / CLOCK_PERIOD_SEC ) - 4.0;
     hci_temp = (int) scratch;
     if ( ( hci_temp > 4095 ) || ( hci_temp < 0 ) ) return -EC_SPI_HALF_CLOCK_OUT_OF_RANGE;
     /* compute actual */
     scratch = CLOCK_PERIOD_SEC * ( 4.0 + ((double) hci_temp) );
     if ( NULL != error                 ) *error                 = ( scratch - half_clock_request_sec ) / half_clock_request_sec;
     if ( NULL != half_clock_actual_sec ) *half_clock_actual_sec = scratch;
     if ( NULL != hci                   ) *hci                   = (uint16_t) hci_temp;
     return SUCCESS;
 }
double SPI_Calculate_Half_Clock_Interval_Sec (uint16_t half_clock_interval)
Computes the half clock interval in seconds given the value from the half clock interval register.
Parameters
[in] half_clock_interval Half clock interval register value
Returns
The time value as a double in units of seconds.
Definition at line 1158 of file idi.c.
References CLOCK_PERIOD_SEC.
Referenced by IDI_CMD__SPI_Config_End_Cycle_Delay_Sec(), and SPI_Configuration_Set().
 {
     double half_clock_interval_sec;
     half_clock_interval_sec = CLOCK_PERIOD_SEC * ( 4.0 + ((double) half_clock_interval ) );
     return half_clock_interval_sec;
 }
int SPI_Commit (uint8_t chip_select)
Sets/Clears the chip select or used to commit the transmit/write FIFO to the spi interface. The mode of operation is dependent on the chip_select_behavior.
Parameters
[in] chip_select Used to write to the SCS_COMMIT bit. Its behavior is dependent on the chip_select_behavior.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1606 of file idi.c.
References IO_Write_U8(), and SPI_IsNotPresent().
Referenced by FRAM__Memory_Read(), FRAM__Memory_Write(), IDI_CMD__SPI_Commit(), IDI_CMD__SPI_FIFO(), and SPI_Data_Write_Read_Helper().
 {
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     IO_Write_U8( SPI_COMMIT, chip_select );
     return SUCCESS;
 }
int SPI_Configuration_Chip_Select_Behavior_Get (SPI_CSB_ENUM * chip_select_behavior)
Extracts the chip select behavior from the SPI configuration register.
Parameters
[out] chip_select_behavior pointer to the destination of the value obtained.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1211 of file idi.c.
References IO_Read_U8(), and SPI_IsNotPresent().
Referenced by SPI_Data_Write_Read().
 {
     uint8_t     scratch;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     IO_Read_U8( SPI_CONFIG, &scratch );
     *chip_select_behavior = (SPI_CSB_ENUM) ( scratch >> 4 ) & 0x07;
     return SUCCESS;
 }
int SPI_Configuration_Chip_Select_Behavior_Set (SPI_CSB_ENUM chip_select_behavior)
Sets the chip select behavior to the SPI configuration register.
Parameters
[in] chip_select_behavior enumerated value to be written to the register.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1231 of file idi.c.
References IO_Read_U8(), IO_Write_U8(), and SPI_IsNotPresent().
Referenced by FRAM__Memory_Read(), FRAM__Memory_Write(), FRAM__Read_ID(), FRAM__Read_Status_Register(), FRAM__Write_Disable(), FRAM__Write_Enable_Latch_Set(), FRAM__Write_Status_Register(), and SPI_Data_Write_Read().
 {
     uint8_t     scratch;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     IO_Read_U8( SPI_CONFIG, &scratch );
     scratch &= 0x70;
     scratch |= (uint8_t) ( ( chip_select_behavior & 0x07 ) << 4 );
     IO_Write_U8( SPI_CONFIG, scratch );
     return SUCCESS;
 }
int SPI_Configuration_Get (struct spi_cfg * cfg)
Obtains the SPI configuration from the hardware.
Parameters
[out] cfg SPI configuration data structure or data set
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1309 of file idi.c.
References spi_cfg::chip_select_behavior, spi_cfg::clock_hz, CLOCK_PERIOD_SEC, spi_cfg::end_cycle_delay, spi_cfg::end_delay_ns, spi_cfg::half_clock_interval, IO_Read_U8(), spi_cfg::sclk_phase, spi_cfg::sclk_polarity, spi_cfg::sdi_polarity, spi_cfg::sdio_wrap, spi_cfg::sdo_polarity, idi_dataset::spi_cfg, and SPI_IsNotPresent().
Referenced by IDI_CMD__SPI_Config_Chip_Select_Behavior(), IDI_CMD__SPI_Config_Clock_Hz(), IDI_CMD__SPI_Config_End_Cycle_Delay_Sec(), IDI_CMD__SPI_Config_Get(), IDI_CMD__SPI_Config_Mode(), IDI_CMD__SPI_Config_SDI_Polarity(), IDI_CMD__SPI_Config_SDIO_Wrap(), and IDI_CMD__SPI_Config_SDO_Polarity().
 {
     uint8_t     scratch;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     IO_Read_U8( SPI_CONFIG, &scratch );
     cfg->chip_select_behavior   = (SPI_CSB_ENUM) ( scratch >> 4 ) & 0x07;
     cfg->sclk_polarity          = (BOOL) ( scratch & 0x01 );
     cfg->sclk_phase             = (BOOL) ( scratch & 0x02 );
     cfg->sdi_polarity           = (BOOL) ( scratch & 0x04 );
     cfg->sdo_polarity           = (BOOL) ( scratch & 0x08 );
     cfg->sdio_wrap              = (BOOL) ( scratch & 0x80 );
     IO_Read_U8( SPI_HCI_LSB, &scratch );
     cfg->half_clock_interval = (uint16_t) scratch;
     IO_Read_U8( SPI_HCI_MSB, &scratch );
     cfg->half_clock_interval |= ( (uint16_t) scratch) << 8;
     IO_Read_U8( SPI_ECD, &(cfg->end_cycle_delay) );
     cfg->clock_hz = 1.0 / ( 2.0 * CLOCK_PERIOD_SEC * ( 4.0 + ((double) cfg->half_clock_interval) ) );
     cfg->end_delay_ns = 1.0e9 * CLOCK_PERIOD_SEC * 4.0 + 0.5 * ((double) cfg->end_cycle_delay) / cfg->clock_hz;
     memcpy( &(idi_dataset.spi_cfg), &cfg, sizeof( struct spi_cfg ) );
     return SUCCESS;
 }
int SPI_Configuration_Initialize (struct spi_cfg * cfg)
Initializes the SPI configuration data structure.
[in] cfg Pointer to the SPI configuration data structure to be initialized
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1408 of file idi.c.
References spi_cfg::chip_select_behavior, spi_cfg::clock_hz, spi_cfg::end_cycle_delay, spi_cfg::end_delay_ns, spi_cfg::half_clock_interval, spi_cfg::sclk_phase, spi_cfg::sclk_polarity, spi_cfg::sdi_polarity, spi_cfg::sdio_wrap, and spi_cfg::sdo_polarity.
 {
     cfg->sdio_wrap              = false;
     cfg->sdo_polarity           = false;
     cfg->sdi_polarity           = false;
     /*  Mode    CPOL    CPHA
      *   0       0       0
      *   1       0       1
      *   2       1       0
      *   3       1       1
      */
     cfg->sclk_phase             = false;   /* the FRAM uses SPI Mode 0 or 3 */
     cfg->sclk_polarity          = false;
     cfg->chip_select_behavior   = false;
     cfg->end_cycle_delay        = 0;        /* shortest delay possible      */
     cfg->half_clock_interval    = 0;        /* shortest interval possible   */
     cfg->clock_hz               = 0.0;
     cfg->end_delay_ns           = 0.0;
     return SUCCESS;
 }
int SPI_Configuration_Set (struct spi_cfg * cfg)
Commits the configuration data structure to the hardware.
Parameters
[in] cfg The software configuration data structure to be committed to hardware
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1254 of file idi.c.
References spi_cfg::chip_select_behavior, spi_cfg::clock_hz, spi_cfg::end_cycle_delay, spi_cfg::end_delay_ns, spi_cfg::half_clock_interval, IO_Write_U8(), spi_cfg::sclk_phase, spi_cfg::sclk_polarity, spi_cfg::sdi_polarity, spi_cfg::sdio_wrap, spi_cfg::sdo_polarity, SPI_Calculate_Clock(), SPI_Calculate_End_Cycle_Delay(), SPI_Calculate_Half_Clock_Interval_Sec(), idi_dataset::spi_cfg, and SPI_IsNotPresent().
Referenced by IDI_CMD__SPI_Config_Chip_Select_Behavior(), IDI_CMD__SPI_Config_Clock_Hz(), IDI_CMD__SPI_Config_End_Cycle_Delay_Sec(), IDI_CMD__SPI_Config_Mode(), IDI_CMD__SPI_Config_SDI_Polarity(), IDI_CMD__SPI_Config_SDIO_Wrap(), and IDI_CMD__SPI_Config_SDO_Polarity().
 {
     int         error_code;
     double      scratch;
     double      hci_sec;     /* half clock interval in seconds */
     uint8_t     config;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     config = (uint8_t) ( ( cfg->chip_select_behavior & 0x07 ) << 4 );
     if ( cfg->sclk_polarity ) config |= 0x01;
     if ( cfg->sclk_phase    ) config |= 0x02;
     if ( cfg->sdi_polarity  ) config |= 0x04;
     if ( cfg->sdo_polarity  ) config |= 0x08;
     if ( cfg->sdio_wrap     ) config |= 0x80;
     IO_Write_U8( SPI_CONFIG, config );
     if ( cfg->clock_hz > 0 )
     { /* compute half_clock_interval */
         //scratch = ( 1.0 - ( 8.0 * CLOCK_PERIOD_SEC * cfg->clock_hz ) ) / (  2.0 * CLOCK_PERIOD_SEC * cfg->clock_hz );
         error_code = SPI_Calculate_Clock( cfg->clock_hz, NULL, NULL, &(cfg->half_clock_interval) );
         if ( error_code ) return error_code;
     }
     hci_sec = SPI_Calculate_Half_Clock_Interval_Sec( cfg->half_clock_interval );
     if ( cfg->end_delay_ns > 0 )
     {
         scratch    = cfg->end_delay_ns * 1.0e-9;
         error_code = SPI_Calculate_End_Cycle_Delay( hci_sec,                /* calculated half-clock interval     */
                                                     scratch,                /* requested end-delay interval       */
                                                     NULL,                   /*  computed actual delay             */
                                                     NULL,                   /* error between actual and desired   */
                                                     &(cfg->end_cycle_delay) /* computed count                     */
                                                    );
         if ( error_code ) return error_code;
     }
     IO_Write_U8( SPI_HCI_LSB, (uint8_t)( cfg->half_clock_interval & 0xFF ) );
     IO_Write_U8( SPI_HCI_MSB, (uint8_t)( cfg->half_clock_interval >> 8   ) );
     IO_Write_U8( SPI_ECD, cfg->end_cycle_delay );
     memcpy( &(idi_dataset.spi_cfg), &cfg, sizeof( struct spi_cfg ) );
     return SUCCESS;
 }
int SPI_Data_Read (const void * rx_buffer, size_t size, size_t rx_size, FILE * fd_log)
Special case of Write/Read that has a function signature same as fread() or fwrite().
Parameters
[in] cfg pass in the configuration to be written to hardware.
Returns
a nonzero if successful, else return zero.
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Parameters
size object size
rx_size object count
fd_log set to NULL if no file logging
Definition at line 2023 of file idi.c.
References SPI_Data_Write_Read().
 {
     int error_code;
     error_code = SPI_Data_Write_Read(   size,
                                         0,      /* nothing to transmit */
                                         NULL,   /* nothing to transmit */
                                         rx_size,
                                         rx_buffer
                                     );
     if ( error_code ) return error_code;
     if ( NULL != fd_log )
     {
         error_code = fwrite( rx_buffer, size, rx_size, fd_log );
     }
     return error_code;
 }
int SPI_Data_Write (const void * tx_buffer, size_t size, size_t tx_count, FILE * fd_log)
Special case of Write/Read that has a function signature same as fread() or fwrite().
Parameters
[in] cfg pass in the configuration to be written to hardware.
Returns
a nonzero if successful, else return zero.
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Parameters
size object size
tx_count object count
fd_log set to NULL if no file logging
Definition at line 1987 of file idi.c.
References SPI_Data_Write_Read().
 {
     int error_code;
     error_code = SPI_Data_Write_Read(   size,
                                         tx_count,
                                         tx_buffer,
                                         0,          /* nothing to receive */
                                         NULL        /* nothing to receive */
                                     );
     if ( error_code ) return error_code;
     if ( NULL != fd_log )
     {
         error_code = fwrite( tx_buffer, size, tx_count, fd_log );
     }
     return error_code;
 }
int SPI_Data_Write_Read (size_t size, size_t tx_count, const void * tx_buffer, size_t rx_size, const void * rx_buffer)
This function will write/read virtually any kind of data with almost any kind of chips select wrapping surrounding the data.
Returns
a zero if successful, else return an error code.
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Parameters
size object size: 1=u8, 2=u16, 4=u16, 8=u64, 16=u128=SPI_FIFO_SIZE
tx_count object count
rx_size object count
Definition at line 1856 of file idi.c.
References IDI_CSB_BUFFER, IDI_CSB_SOFTWARE, IDI_CSB_UINT16, IDI_CSB_UINT8, SPI_Configuration_Chip_Select_Behavior_Get(), SPI_Configuration_Chip_Select_Behavior_Set(), SPI_Data_Write_Read_Helper(), SPI_FIFO_SIZE, and SPI_IsNotPresent().
Referenced by FRAM__Memory_Read(), FRAM__Memory_Write(), FRAM__Read_ID(), FRAM__Read_Status_Register(), FRAM__Write_Disable(), FRAM__Write_Enable_Latch_Set(), FRAM__Write_Status_Register(), IDI_CMD__SPI_Data(), SPI_Data_Read(), and SPI_Data_Write().
 {
     int                 error_code;
     int                 index;
     BOOL                active_tx;
     BOOL                active_rx;
     SPI_CSB_ENUM        csb_copy;
     SPI_CSB_ENUM        csb;
     BOOL                csb_buffer_mode_override;
 /* TEST FOR VALIDITY OF PARAMETERS */
     /* see if there is anything to do */
     if ( ( NULL == tx_buffer ) && ( NULL == rx_buffer ) ) return SUCCESS;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     /* initialize parameters */
     error_code = SPI_Configuration_Chip_Select_Behavior_Get( &csb );
     if ( error_code ) return error_code;
     //error_code = SPI_Status_Write( &status_tx );
     //if ( error_code ) return error_code;
     //error_code = SPI_Status_Read( &status_rx );
     //if ( error_code ) return error_code;
     active_rx = false; /* assume that we toss any data to be read out */
     active_tx = false; /* assume that we have no valid data to write  */
     if ( NULL != tx_buffer ) active_tx = true;
     else                     tx_count  = rx_size;
     if ( NULL != rx_buffer ) active_rx = true;
     else                     rx_size   = tx_count;
     if ( IDI_CSB_UINT16 == csb )
     { /* test for even quantity of bytes to transceive */
         if ( ( tx_count & 0x01 ) || ( rx_size & 0x01 ) )
         { /* odd number of bytes detected for buffers */
             return -EC_SPI_BUFFER_SIZE_ODD;
         }
     }
     csb_buffer_mode_override = false;
     if ( IDI_CSB_BUFFER == csb )
     { /* test for object size */
         if ( size > SPI_FIFO_SIZE ) return -EC_SPI_OBJECT_SIZE;
     }
     else
     {
         /* test object sizes */
         index = SPI_FIFO_SIZE;  /* assumed to be a 2^N number */
         while ( index > sizeof( uint16_t ) )
         {
             if ( size == ( size & index ) )
             {
                 csb_buffer_mode_override = true;
                 break;
             }
             index = index >> 1;
         }
         if ( ( size > 2 ) && ( false == csb_buffer_mode_override ) )
         {
             return -EC_SPI_OBJECT_SIZE; /* not a power of 2 */
         }
         else if ( true == csb_buffer_mode_override )
         { /* OK, go ahead and change to buffer mode */
             csb_copy   = csb;
             csb        = IDI_CSB_BUFFER;
             error_code = SPI_Configuration_Chip_Select_Behavior_Set( csb );
         }
     }
 /* PERFORM TRANSACTIONS */
     switch( csb )
     {
         case IDI_CSB_SOFTWARE:
         case IDI_CSB_UINT8:
         case IDI_CSB_UINT16:
             error_code = SPI_Data_Write_Read_Helper( size,
                                                      tx_count,
                                                      tx_buffer,
                                                      rx_size,
                                                      rx_buffer,
                                                      active_tx,
                                                      active_rx,
                                                      csb
                                                    );
             break;
         case IDI_CSB_BUFFER:
             for ( index = 0; index < tx_count; index++ )
             {
                 error_code = SPI_Data_Write_Read_Helper( size,
                                                          1,
                                                          active_tx ? &(((uint8_t *) tx_buffer)[index*size]) : NULL,
                                                          1,
                                                          active_rx ? &(((uint8_t *) rx_buffer)[index*size]) : NULL,
                                                          active_tx,
                                                          active_rx,
                                                          csb
                                                        );
             }
             if ( csb_buffer_mode_override )
             { /* restore to original csb */
                 error_code = SPI_Configuration_Chip_Select_Behavior_Set( csb_copy );
             }
             break;
         default:
             return -EC_SPI_CSB_OUT_OF_RANGE;
             break;
     }
     return SUCCESS;
 }
static int SPI_Data_Write_Read_Helper (size_t size, size_t tx_count, const void * tx_buffer, size_t rx_size, const void * rx_buffer, BOOL active_tx, BOOL active_rx, SPI_CSB_ENUM csb) static
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Parameters
size object size: u8 = 1, u16 = 2
tx_count object count
rx_size object count
Definition at line 1716 of file idi.c.
References IDI_CSB_SOFTWARE, IO_Read_U8(), IO_Write_U8(), SPI_Commit(), SPI_Status_Read_FIFO_Status(), and SPI_Status_Write_FIFO_Status().
Referenced by SPI_Data_Write_Read().
 {
     size_t  rx_bytes_available;
     BOOL    rx_empty;
     BOOL    tx_full;
     BOOL    tx_empty;
     size_t  tx_bytes_available;
     size_t  tx_index;
     size_t  rx_index;
     size_t  index;
     BOOL    commit_valid;
     uint8_t bit_bucket; /* tossed */
     /* verify size information */
     switch ( size )
     {
         case sizeof( uint8_t  ):
         case sizeof( uint16_t ):
             break; /* these sizes are OK */
         default:
             return -EC_SPI_OBJECT_SIZE;
             break;
     }
     /* initially need to make sure that both TX and RX are empty */
     do
     { //TODO: need a time out of some sort here and then return an error code.
         SPI_Status_Write_FIFO_Status( &tx_full, &tx_empty, &tx_bytes_available );
         if ( false == tx_empty ) SPI_Commit( 0xFF );
     } while ( false == tx_empty );
     do
     { //TODO: need a time out of some sort here and then return an error code.
         SPI_Status_Read_FIFO_Status( &rx_empty, &rx_bytes_available );
         if ( false == rx_empty ) IO_Read_U8( SPI_DATA, &bit_bucket  ); /* toss */
     } while ( false == rx_empty );
     tx_index     = 0;
     rx_index     = 0;
     commit_valid = false;
     while ( tx_index < tx_count )
     {
         /* get status simultaneously */
         SPI_Status_Write_FIFO_Status( &tx_full, &tx_empty, &tx_bytes_available );
         if ( (true == tx_full) && (false == commit_valid) )
         {
             if ( IDI_CSB_SOFTWARE != csb ) SPI_Commit( 0xFF ); /* does not matter what is written */
             commit_valid = true;
         }
         if ( (true == tx_empty) && (true == commit_valid) )
         {
             commit_valid = false; /* will need to restart the buffer transmission */
         }
         /* Write Data
          *
          */
         if ( tx_bytes_available > size )
         {   /* write data */
             if ( active_tx )
             {
             for ( index = 0; index < size; index++ ) IO_Write_U8( SPI_DATA, ((uint8_t *) tx_buffer)[tx_index] );
             }
             else
             {
             for ( index = 0; index < size; index++ ) IO_Write_U8( SPI_DATA, 0x00 ); /* send anything */
             }
             tx_index = tx_index + size;
         }
         /* Read Data
          *  This function will play catch up with respect to the transmit side.
          */
         /* get status simultaneously */
         SPI_Status_Read_FIFO_Status( &rx_empty, &rx_bytes_available );
         if ( rx_bytes_available >= size )
         { /* read data */
             if ( active_rx )
             {
             for ( index = 0; index < size; index++ ) IO_Read_U8( SPI_DATA, &(((uint8_t *) rx_buffer)[rx_index]) );
             }
             else
             {
             for ( index = 0; index < size; index++ ) IO_Read_U8( SPI_DATA, &bit_bucket ); /* toss */
             }
             rx_index = rx_index + size;
         }
     }
     SPI_Status_Write_FIFO_Status( &tx_full, &tx_empty, &tx_bytes_available );
     if ( (false == commit_valid) && (false == tx_empty) )
     { /* data has not been transmitted yet */
         if ( IDI_CSB_SOFTWARE != csb ) SPI_Commit( 0xFF ); /* does not matter what is written */
         /* wait for the buffer to empty */
         do
         { //TODO: need a timeout and return error code if timeout exceeded.
             SPI_Status_Write_FIFO_Status( &tx_full, &tx_empty, &tx_bytes_available );
         } while ( false == tx_empty );
     }
     /* retrieve the remaining read data and don't return until we are done */
     while ( rx_index != tx_index )
     { //TODO: timeout mechanism????
         SPI_Status_Read_FIFO_Status( &rx_empty, &rx_bytes_available );
         if ( rx_bytes_available >= size )
         { /* read data */
             if ( active_rx )
             {
             for ( index = 0; index < size; index++ ) IO_Read_U8( SPI_DATA, &(((uint8_t *) rx_buffer)[rx_index]) );
             }
             else
             {
             for ( index = 0; index < size; index++ ) IO_Read_U8( SPI_DATA, &bit_bucket ); /* toss */
             }
             rx_index = rx_index + size;
         }
     }
     return SUCCESS;
 }
int SPI_FIFO_Read (const void * buffer, size_t size, size_t count, FILE * fd_log)
Reads from the SPI receive/read data FIFO. It does not attempt to correlate the number of transmit bytes with receive bytes. Its purpose is more for low level hardware testing. Note that this function has a signature identical to the fread() function (i.e. make use of function pointers to guide sourcing of data).
Parameters
[in] buffer Buffer for the data destination.
[in] size Size of objects in bytes.
[in] count Number of objects to be read
[out] fd_log Optional log file to write the buffer too. If NULL, then no logging.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned indicating an error. In addition, a positive value is returned indicating the number of actual objects written.
Definition at line 1677 of file idi.c.
References IO_Read_U8(), SPI_FIFO_SIZE, SPI_IsNotPresent(), and SPI_Status_Read_FIFO_Status().
Referenced by IDI_CMD__SPI_FIFO().
 {
     int     error_code;       /* used primarily for debug purposes */
     size_t  bytes_available;
     BOOL    empty;
     BOOL    full;
     size_t  index;
     size_t  qty_objects;
     size_t  qty_bytes;
     error_code = SUCCESS;
     if ( (size * count) > SPI_FIFO_SIZE ) return -EC_PARAMETER;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     SPI_Status_Read_FIFO_Status( &empty, &bytes_available );
     qty_objects =  bytes_available / size; /* max number of objects that can be processed */
     if ( count > qty_objects ) count = qty_objects;
     qty_bytes = count * size;
     for ( index = 0; index < qty_bytes; index++ ) IO_Read_U8( SPI_DATA, &(((uint8_t *) buffer)[index]) );
     if ( NULL != fd_log )
     {
         error_code = fwrite( buffer, size, qty_objects, fd_log );
     }
     if ( SUCCESS == error_code ) error_code = ( (int) qty_objects );
     return error_code;
 }
int SPI_FIFO_Write (const void * buffer, size_t size, size_t count, FILE * fd_log)
Writes specifically to the SPI transmit/write data FIFO. It does not attempt to correlate the number of transmit bytes with receive bytes. Its purpose is more for low level hardware testing. Note that this function has a signature identical to the fwrite() function (i.e. make use of function pointers to guide destination of data).
Parameters
[in] buffer Buffer containing the data to be written.
[in] size Size of objects in bytes.
[in] count Number of objects to be written
[out] fd_log Optional log file to write the buffer too. If NULL, then no logging.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned indicating an error. In addition, a positive value is returned indicating the number of actual objects written.
Definition at line 1628 of file idi.c.
References IO_Write_U8(), SPI_FIFO_SIZE, SPI_IsNotPresent(), and SPI_Status_Write_FIFO_Status().
Referenced by IDI_CMD__SPI_FIFO().
 {
     int     error_code;       /* used primarily for debug purposes */
     size_t  bytes_in_fifo;
     BOOL    empty;
     BOOL    full;
     size_t  index;
     size_t  qty_objects;
     size_t  qty_bytes;
     error_code = SUCCESS;
     if ( (size * count) > SPI_FIFO_SIZE ) return -EC_PARAMETER;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     SPI_Status_Write_FIFO_Status( &full, &empty, &bytes_in_fifo );
     qty_objects =  (SPI_FIFO_SIZE - bytes_in_fifo) / size; /* max number of objects that can be processed */
     if ( count > qty_objects ) count = qty_objects;
     qty_bytes = count * size;
     for ( index = 0; index < qty_bytes; index++ ) IO_Write_U8( SPI_DATA, ((uint8_t *) buffer)[index] );
     if ( NULL != fd_log )
     {
         error_code = fwrite( buffer, size, qty_objects, fd_log );
     }
     if ( SUCCESS == error_code ) error_code = ( (int) qty_objects );
     return error_code;
 }
int SPI_ID_Get (uint16_t * id)
Retrieves the SPI ID register value.
Parameters
[out] id The SPI component ID value.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1041 of file idi.c.
References ID_SPI, and IO_Read_U8().
Referenced by IDI_CMD__SPI_ID(), and SPI_IsNotPresent().
 {
     uint8_t     lsb, msb;
     IO_Read_U8( SPI_ID_LSB, &lsb );
     IO_Read_U8( SPI_ID_MSB, &msb );
     *id = ( ((uint16_t) msb) << 8 ) | ((uint16_t) lsb);
 #if defined( ID_ALWAYS_REPORT_AS_GOOD )
     *id = ID_SPI;
 #endif
     return SUCCESS;
 }
int SPI_IsNotPresent (void)
Reports if the SPI component is available within the register space by matching a known ID. The SPI register map is only enabled within the hardware if the hardware mode is not zero (i.e. M1 and M0 jumpers on the board provide a nonzero value).
Returns
A zero is returned if the SPI component ID is not found within the register space.
Definition at line 1062 of file idi.c.
References ID_SPI, and SPI_ID_Get().
Referenced by SPI_Commit(), SPI_Configuration_Chip_Select_Behavior_Get(), SPI_Configuration_Chip_Select_Behavior_Set(), SPI_Configuration_Get(), SPI_Configuration_Set(), SPI_Data_Write_Read(), SPI_FIFO_Read(), SPI_FIFO_Write(), SPI_Status_Read(), and SPI_Status_Write().
 {
     uint16_t id;
     SPI_ID_Get( &id );
     if (ID_SPI == id ) return 0;
     return 1;
 }
int SPI_Report_Configuration_Text (struct spi_cfg * cfg, FILE * out)
Creates a human readable report of the SPI configuration data structure.
Parameters
[in] cfg SPI configuration data structure pointer [out] out File destination descriptor
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1346 of file idi.c.
References spi_cfg::chip_select_behavior, spi_cfg::clock_hz, spi_cfg::end_cycle_delay, spi_cfg::end_delay_ns, spi_cfg::half_clock_interval, IDI_CSB_BUFFER, IDI_CSB_SOFTWARE, IDI_CSB_UINT16, IDI_CSB_UINT8, spi_cfg::sclk_phase, spi_cfg::sclk_polarity, and spi_cfg::sdi_polarity.
Referenced by IDI_CMD__SPI_Config_Get().
 {
     fprintf( out, "################################### SPI Configuration:\n" );
     fprintf( out, "sdio_wrap             = %s\n", cfg->sclk_polarity    ? "true" : "false" );
     fprintf( out, "sdo_polarity          = %s\n", cfg->sclk_polarity    ? "true" : "false" );
     fprintf( out, "sdi_polarity          = %s\n", cfg->sdi_polarity     ? "true" : "false" );
     fprintf( out, "sclk_phase            = %s\n", cfg->sclk_phase       ? "true" : "false" );
     fprintf( out, "sclk_polarity         = %s\n", cfg->sclk_polarity    ? "true" : "false" );
     fprintf( out, "chip_select_behavior  = " );
     switch( cfg->chip_select_behavior )
     {
         case IDI_CSB_SOFTWARE:      fprintf( out, "IDI_CSB_SOFTWARE" );         break;
         case IDI_CSB_BUFFER:        fprintf( out, "IDI_CSB_BUFFER" );           break;
         case IDI_CSB_UINT8:         fprintf( out, "IDI_CSB_UINT8" );            break;
         case IDI_CSB_UINT16:        fprintf( out, "IDI_CSB_UINT16" );           break;
         default:                    fprintf( out, "undefined" );                break;
     }
     fprintf( out, "\n" );
     fprintf( out, "end_cycle_delay       = 0x%02X  (%d)\n", cfg->end_cycle_delay,     cfg->end_cycle_delay     );
     fprintf( out, "half_clock_interval   = 0x%04X  (%d)\n", cfg->half_clock_interval, cfg->half_clock_interval );
     fprintf( out, "clock_hz              = %f Hz\n", cfg->clock_hz );
     fprintf( out, "end_delay_ns          = %f ns\n", cfg->end_delay_ns );
     fprintf( out, "\n" );
     return SUCCESS;
 }
int SPI_Report_Status_Text (struct spi_status * status, FILE * out)
Produces a human readable report of the SPI status data structure.
Parameters
[in] status SPI status data structure pointer [out] out File destination descriptor
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1384 of file idi.c.
References spi_status::empty, spi_status::fifo_count, spi_status::fifo_size, spi_status::full, and spi_status::tx_status.
Referenced by IDI_CMD__SPI_Status().
 {
     fprintf( out, "################################### SPI " );
     if ( status->tx_status ) fprintf( out, "TX" );
     else                     fprintf( out, "RX" );
     fprintf( out, " Status:\n" );
     fprintf( out, "full       = %s\n", status->full  ? "true" : "false" );
     fprintf( out, "empty      = %s\n", status->empty ? "true" : "false" );
     fprintf( out, "fifo size  = %d\n", status->fifo_size                );
     fprintf( out, "fifo count = %d\n", status->fifo_count               );
     return SUCCESS;
 }
int SPI_Status_Read (struct spi_status * status)
Builds a detailed status data structure of the receive/read incoming SPI data FIFO. Reports the quantity of bytes currently in the receive FIFO, full flag, empty flag, the total size of the FIFO in bytes, and sets tx_status to false indicating that this is status specific to the receive FIFO.
The status register has the following format: status[7] full status[6] empty status[5] not used (future size expansion) status[4:0] number of bytes currently in the FIFO
Parameters
[out] status Pointer to status data structure to be updated.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1550 of file idi.c.
References spi_status::empty, spi_status::fifo_count, spi_status::fifo_size, spi_status::full, IO_Read_U8(), SPI_FIFO_SIZE, SPI_IsNotPresent(), and spi_status::tx_status.
Referenced by IDI_CMD__SPI_Status().
 {
     uint8_t reg_value;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     IO_Read_U8( SPI_RX_STATUS, &reg_value );
     status->fifo_count = (int)( reg_value & 0x1F );
     status->full       = (BOOL)( reg_value & 0x80 );
     status->fifo_size  = (int) SPI_FIFO_SIZE;
     status->empty      = (BOOL)( reg_value & 0x40 );
     status->tx_status  = false;
     return SUCCESS;
 }
BOOL SPI_Status_Read_FIFO_Is_Not_Empty (void)
Returns the receive/read FIFO empty status flag. This function is typically used to determine if the FIFO is empty.
Returns
Returns true if the receive/read FIFO is not empty.
Definition at line 1587 of file idi.c.
References IO_Read_U8().
Referenced by IDI_CMD__SPI_FIFO().
 {
     uint8_t reg_value;
     IO_Read_U8( SPI_RX_STATUS, &reg_value );
     if ( reg_value & 0x40 ) return false;
     return true;
 }
void SPI_Status_Read_FIFO_Status (BOOL * empty, size_t * bytes_available)
Returns the complete read/receive FIFO status.
The status register has the following format: status[7] full status[6] empty status[5] not used (future size expansion) status[4:0] number of bytes currently in the FIFO
Parameters
[out] empty FIFO empty flag
[out] bytes_available a count of the number of bytes in the FIFO
Returns
nothing
Definition at line 1524 of file idi.c.
References IO_Read_U8().
Referenced by SPI_Data_Write_Read_Helper(), and SPI_FIFO_Read().
 {
     uint8_t reg_value;
     IO_Read_U8( SPI_RX_STATUS, &reg_value );
     *bytes_available = (size_t)( reg_value & 0x1F );
     *empty           = (BOOL)( reg_value & 0x40 );
 }
int SPI_Status_Write (struct spi_status * status)
Builds a detailed status data structure of the transmit/write outgoing SPI data FIFO. Reports the quantity of bytes currently in the transmit FIFO, full flag, empty flag, the total size of the FIFO in bytes, and sets tx_status to true indicating that this is status specific to the transmit FIFO.
The status register has the following format: status[7] full status[6] empty status[5] not used (future size expansion) status[4:0] number of bytes currently in the FIFO
Parameters
[out] status Pointer to status data structure to be updated.
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 1449 of file idi.c.
References spi_status::empty, spi_status::fifo_count, spi_status::fifo_size, spi_status::full, IO_Read_U8(), SPI_FIFO_SIZE, SPI_IsNotPresent(), and spi_status::tx_status.
Referenced by IDI_CMD__SPI_Status().
 {
     uint8_t reg_value;
     if ( SPI_IsNotPresent() ) return -EC_SPI_NOT_FOUND;
     IO_Read_U8( SPI_TX_STATUS, &reg_value );
     status->fifo_count = (int)( reg_value & 0x1F );
     status->full       = (BOOL)( reg_value & 0x80 );
     status->fifo_size  = (int) SPI_FIFO_SIZE;
     status->empty      = (BOOL)( reg_value & 0x40 );
     status->tx_status  = true;
     return SUCCESS;
 }
BOOL SPI_Status_Write_FIFO_Is_Full (void)
Returns the transmit/write FIFO full status flag. It is preferable to use the SPI_Status_Write() or SPI_Status_Write_FIFO_Status() because all status is retrieved at one time.
Returns
Returns true if the transmit/write FIFO is full.
Definition at line 1501 of file idi.c.
References IO_Read_U8().
 {
     uint8_t reg_value;
     IO_Read_U8( SPI_TX_STATUS, &reg_value );
     if ( reg_value & 0x80 ) return true;
     return false;
 }
BOOL SPI_Status_Write_FIFO_Is_Not_Empty (void)
Returns the transmit/write FIFO empty status flag. This function is typically used to wait for the transmit/write FIFO to become empty.
Returns
Returns true if the transmit/write FIFO is not empty.
Definition at line 1572 of file idi.c.
References IO_Read_U8().
Referenced by FRAM__Memory_Read(), FRAM__Memory_Write(), and IDI_CMD__SPI_FIFO().
 {
     uint8_t reg_value;
     IO_Read_U8( SPI_TX_STATUS, &reg_value );
     if ( reg_value & 0x40 ) return false;
     return true;
 }
void SPI_Status_Write_FIFO_Status (BOOL * full, BOOL * empty, size_t * bytes_in_fifo)
Returns the complete write/transmit FIFO status.
The status register has the following format: status[7] full status[6] empty status[5] not used (future size expansion) status[4:0] number of bytes currently in the FIFO
Parameters
[out] full FIFO full flag
[out] empty FIFO empty flag
[out] bytes_in_fifo a count of the number of bytes in the FIFO
Returns
nothing
Definition at line 1480 of file idi.c.
References IO_Read_U8(), and SPI_FIFO_SIZE.
Referenced by SPI_Data_Write_Read_Helper(), and SPI_FIFO_Write().
 {
     uint8_t reg_value;
     IO_Read_U8( SPI_TX_STATUS, &reg_value );
     switch( reg_value & 0xC0 )
     {
         case 0x00: *full = false;   *empty = false;     break;
         case 0x40: *full = false;   *empty = true;      break;
         case 0x80: *full = true;    *empty = false;     break;
         case 0xC0: *full = true;    *empty = true;      break;
     }
     *bytes_in_fifo = (size_t) SPI_FIFO_SIZE - (size_t)( reg_value & 0x1F );
 }
BOOL String_To_Bool (const char * str)
General function used to convert a string into a boolean equivalent value.
Parameters
[in] str string input for conversion.
Returns
a BOOL is returned. The default value returned is false.
Definition at line 541 of file idi.c.
Referenced by IDI_CMD__Main_IO_Behavior(), IDI_CMD__SPI_Commit(), IDI_CMD__SPI_Config_SDI_Polarity(), IDI_CMD__SPI_Config_SDIO_Wrap(), IDI_CMD__SPI_Config_SDO_Polarity(), and IDI_CMD__SPI_FIFO().
 {
     switch( str[0] )
     {
     case '0':
     case 'f':
     case 'F':
         return false;
     case '1':
     case 't':
     case 'T':
         return true;
     }
     return false;
 }
Variable Documentation
const struct reg_definition definitions[] static
Initial value:
=
{
}
Definition at line 433 of file idi.c.
const struct ec_human_readable ec_human_readable[]
Initial value:
=
{
        EC_HUMAN_READABLE_TERMINATE
}
Definition at line 411 of file idi.c.
const char ec_unknown[] = "unknown error code" static
Translates an error code into a human readable message.
Parameters
[in] error_code The error code to be translated into a human readable message
Returns
a human readable string representing a very brief description of the error code.
Definition at line 624 of file idi.c.
Referenced by EC_Code_To_Human_Readable().
const char* idi_bank_symbol_names[] static
Initial value:
=
{
    "IDI_BANK_0",
    "IDI_BANK_1",
    "IDI_BANK_2",
    "IDI_BANK_3",
    "IDI_BANK_4",
    "IDI_BANK_5",
    "IDI_BANK_6",
    "IDI_BANK_7",
    "IDI_BANK_NONE",
    "IDI_BANK_UNDEFINED"
}
Definition at line 418 of file idi.c.
Referenced by IDI_Symbol_Name_Bank().
struct command_line idi_cmd_din[] static
Initial value:
=
{
    {   IDI_CMD__DIN_ID,        "id",       "params: none.  Reports the DIN board/component ID."    },
    {   IDI_CMD__DIN_Channel,   "chan",     "params: <channel>"                                     },
    {   IDI_CMD__DIN_Group,     "group",    "params: [<group_channel | all>]"                       },
    {   IDI_CMD__DIN_All,       "all",      "reports all digital inputs in binary and hex"          },
    {   NULL,                   NULL,       NULL                                                    },
}
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3411 of file idi.c.
struct command_line idi_cmd_fram[] static
Initial value:
=
{
    {   IDI_CMD__FRAM_Dump,     "dump",     "params: <address> <length>"                            },
    {   IDI_CMD__FRAM_Save,     "save"      "params: <address> <length> <binary destination file>"  },
    {   IDI_CMD__FRAM_Load,     "load"      "params: <address> <binary source file name"            },
    {   IDI_CMD__FRAM_Init,     "init"      "params: [byte/character] [byte/character] ..."         },
    {   IDI_CMD__FRAM_WREN,     "wren"      "WRite Enable Latch Set"                                },
    {   IDI_CMD__FRAM_WRDI,     "wrdi"      "WRite DIsable"                                         },
    {   IDI_CMD__FRAM_RDSR,     "rdsr"      "ReaD Status Register"                                  },
    {   IDI_CMD__FRAM_WRSR,     "wrsr"      "WRite Status Register.  Params: <status>"              },
    {   IDI_CMD__FRAM_RDID,     "rdid"      "ReaD ID Register"                                      },
    {   NULL,                   NULL,       NULL                                                    },
}
Definition at line 3213 of file idi.c.
struct command_line idi_cmd_main[] static
Initial value:
=
{
    {   IDI_CMD__Main_Base,             "base",     "params: [<address>]"                                   },
    {   IDI_CMD__Main_IO_Behavior,      "io",       "params: [<simulate>/<report>]"                         },
    {   NULL,                           NULL,       NULL                                                    },
}
Returns
A zero (SUCCESS) is returned if successful, otherwise a negative error code is returned.
Definition at line 3604 of file idi.c.
struct command_line idi_cmd_spi[] static
Initial value:
=
{
    {   IDI_CMD__SPI_ID,                            "id",       "wishbone id: params: none"                             },
    {   IDI_CMD__SPI_Config_Get,                    "cfg",      "config dump: params: none"                             },
    {   IDI_CMD__SPI_Config_Clock_Hz,               "clk",      "clk:         params: [<clock freq in hertz>]"          },
    {   IDI_CMD__SPI_Config_End_Cycle_Delay_Sec,    "ecd",      "end delay:   params: [<time in seconds>]"              },
    {   IDI_CMD__SPI_Config_Mode,                   "mode",     "mode:        params: [<0/1/2/3>]"                      },
    {   IDI_CMD__SPI_Config_SDI_Polarity,           "sdi",      "sdi pol:     params: [<true/1/false/0>]"               },
    {   IDI_CMD__SPI_Config_SDO_Polarity,           "sdo",      "sdo pol:     params: [<true/1/false/0>]"               },
    {   IDI_CMD__SPI_Config_SDIO_Wrap,              "wrap",     "sdo-->sdi:   params: [<true/1/false/0>]"               },
    {   IDI_CMD__SPI_Config_Chip_Select_Behavior,   "csb",      "chip select behavior: params: [0/1/2/3/software/buffer/uint8/uint16]"  },
    {   IDI_CMD__SPI_Status,                        "status",   "status of both TX and RX buffers"                      },
    {   IDI_CMD__SPI_Data,                          "data",     "read/write:  params: [one or more bytes/characters]"   },
    {   IDI_CMD__SPI_FIFO,                          "fifo",     "fifo r/w:    params: [one or more bytes/characters]"   },
    {   IDI_CMD__SPI_Commit,                        "commit"    "causes spi transactions to start"                      },
    {   NULL,                                   NULL,       NULL                                                    }
}
Definition at line 2994 of file idi.c.
struct idi_dataset idi_dataset
Definition at line 441 of file idi.c.
const char idi_svn_revision_string[] = { IDI_REV } static
Global variables.
Definition at line 408 of file idi.c.
Referenced by IDI_Initialization().