Library Reporting: lib_report.c File Reference
lib_report.c File Reference
#include <stdio.h>
#include "../aul_tree/aul/aul_public.h"
Macros
#define LIB_REPORT_REV "$Date: 2014-05-06 11:47:33 -0500 (Tue, 06 May 2014) $"
Functions
int main (int argc, char *argv[], char *envp[])
Detailed Description
Reports all parameters of library/driver
Definition in file lib_report.c.
Macro Definition Documentation
#define LIB_REPORT_REV "$Date: 2014-05-06 11:47:33 -0500 (Tue, 06 May 2014) $"
Subversion time stamp.
Definition at line 87 of file lib_report.c.
Function Documentation
int main (int argc, char * argv[], char * envp[])
main()
Demonstrates simple interactions with the library and driver.
ASSUMPTIONS:
The library (aul_tree) has been previously compiled to a static library. Run make in "/aul_eclipse/aul_tree/_Out_Library_Shared_Application_Debug").
AUL driver has been successfully compiled and installed. Please refer to the readme.txt file in either "/aul_eclipse/drv_aul_x86" or "/aul_eclipse/drv_aul_sim".
DESCRIPTION:
This demonstration various reporting and auto-code generation mechanisms supported by the AES Library. The code generated by this demo can be used with user applications.
Main Variables
int error_code
Variable used to report error codes from the library function calls.
unsigned long revision
Variable used to hold the library revision.
All other variables are not used.
AUL_Library_Name()
DESCRIPTION:
Report the AUL library name. This is a library function call.
AUL_Initialization()
DESCRIPTION:
We need to do this so that all of the underlying modules can populate their complete names and/or provide the proper serialized date/time summary stamps.
POSSIBLE ERRORS:
If an error reported is "No such file or directory", this indicates that the mod_auldrv kernel driver has not been installed properly.
ACGR_Report_CSV_Module()
DESCRIPTION:
Produces a human readable summary list of all modules within the library space. Format is a comma delimited file which can be opened in any text editor, Calc or Excel.
USAGE:
For informational purposes at this time.
ACGR_Report_CSV_Command()
DESCRIPTION:
Produces a human readable summary list of all the error codes within the library and driver space. Format is a comma delimited file which can be opened in any text editor, Calc or Excel.
USAGE:
For informational purposes at this time. Can be used used by other applications where needed at run-time should dynamic modules be inserted into the library.
ACGR_Report_CSV_Status()
DESCRIPTION:
Produces a human readable summary list of all the error codes within the library and driver space. Format is a comma delimited file which can be opened in any text editor, Calc or Excel.
USAGE:
For informational purposes at this time. Can be used used by other applications where needed at run-time should dynamic modules be inserted into the library.
ACGR_Source_File_Command_Enumeration()
DESCRIPTION:
Produces an enumeration of all IOCTL commands that are used in the library and driver space. In this case we are producing a text file that is a header file which can be used within a user application; the only down side to using this is that it ought to be produced each time the library is updated (just to be sure). This enumeration is really best used as a reference to get a feel for all of the possible commands.
USAGE:
For informational purposes and/or embedded into user applications.
ACGR_Source_File_Status_Enumeration()
DESCRIPTION:
Produces an enumeration of all error/status codes that are used in the library and driver space. In this case we are producing a text file that is a header file which can be used within a user application; the only down side to using this is that it ought to be produced each time the library is updated (just to be sure). This enumeration is really best used as a reference to get a feel for all of the possible commands.
USAGE:
For informational purposes and/or embedded into user applications.
ACGR_Source_File_Status_Enumeration()
DESCRIPTION:
Produces an enumeration of all the logical device types that are available. In this case we are producing a text file that is a header file which can be used within a user application; the only down side to using this is that it ought to be produced each time the library is updated (just to be sure). This enumeration can be used to configure application code specific to the target device.
Using the library function AUL_Device_Logical_Get() and the device acronym name (usually defined using insmod) one can obtain the logical_id of the device. This can then be matched up against the DEVICE_LOGICAL_ENUMeration to determine exactly what kind of device it is.
USAGE:
For informational purposes and/or embedded into user applications.
ACGR_Source_File_Status_Enumeration()
DESCRIPTION:
Produces a summary data structure of the serialized date codes of the modules used within the library, The purpose is for both reporting and verification of application with library. In other words, an application may require certain library release (or release range) of either all or particular modules. You can think of this as a finger print of a particular library release and your application may have been written for that release. Now, say, a much newer release comes along and there have been major changes to status codes, well, that will show itself here and your application can warn users (or perhaps stop the application) indicating that there is a library revision conflict with the application. This avoids problems down the road when everyone forgets all the details about the system.
Note that this integrity test is in its early stages of development.
USAGE:
For informational purposes and/or embedded into user applications. The current intent is that one would compare a previously created "aul_integrity.c" with a new one generated. Why? This provides a way to verify that all library and driver revision information matches a well tested and accepted set of code. It offers a way to detect mix-ups in software updates and provides a mechanism to root out which revision is out of sync. with the qualified set of revisions that have been accepted for production release.
AUL_Termination()
DESCRIPTION:
Terminates the driver. This 'closes' the controller portion of the driver. In other words, we are closing the /dev/auldrv from the kernel perspective.
Definition at line 108 of file lib_report.c.
References AUL_Error_String(), AUL_Initialization(), AUL_Library_Name(), AUL_Library_Revision(), and AUL_Termination().
 {
         /*********************************************************************/
         int error_code;
         unsigned long revision;
         (void) argc;
         (void) argv;
         (void) envp;
         /*********************************************************************/
         printf( "Library name = %s\n", AUL_Library_Name() );
         error_code = AUL_Library_Revision( &revision );
         if ( error_code ) goto Main_Error;
         printf( "Library:  Rev_Hex = 0x%08X,  Rev_Dec = %lu\n", (unsigned int) revision, revision );
         /*********************************************************************/
         AUL_Initialization( NULL );
         /*********************************************************************/
         error_code = ACGR_Report_CSV_Module( TRUE, "aul_module_list.csv" );
         if ( error_code ) goto Main_Error;
         /*********************************************************************/
         error_code = ACGR_Report_CSV_Command( TRUE, "aul_command_list.csv" );
         if ( error_code ) goto Main_Error;
         /*********************************************************************/
         error_code = ACGR_Report_CSV_Status( TRUE, "aul_status_list.csv" );
         if ( error_code ) goto Main_Error;
         /*********************************************************************/
         error_code = ACGR_Source_File_Command_Enumeration( "aul_command_enum.h" );
         if ( error_code ) goto Main_Error;
         /*********************************************************************/
         error_code = ACGR_Source_File_Status_Enumeration( "aul_status_enum.h" );
         if ( error_code ) goto Main_Error;
         /*********************************************************************/
         error_code = ACGR_Source_File_Device_Logical_Enumeration( "aul_device_logical_enum.h" );
         if ( error_code ) goto Main_Error;
         /*********************************************************************/
         error_code = ACGR_Source_File_Integrity( "aul_integrity.c" );
         if ( error_code ) goto Main_Error;
         /*********************************************************************/
         AUL_Termination();
         /***************************************************************************/
         printf( "library reports completed successfully\n" );
         return SUCCESS;
 Main_Error:
         printf( "library reports error: error_code = %d, %s\n", error_code, AUL_Error_String( error_code ) );
         return error_code;
 }