#!/bin/bash

# Apex Universal Library Kernel Module Loader  
# Apex Embedded Systems
#
# 
# "$Date: 2015-01-14 17:25:35 -0600 (Wed, 14 Jan 2015) $"

#
# Make sure we are root
#
if [[ $EUID -ne 0 ]]; then
	echo "NOTICE: this script must be run as root" 1>&2
	exit 1
fi

#
#find the root group
#
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

####################################################################################
#
# install the module
#
# NOTE: This is just an example, and your exact implementation will be dictated 
#       by the boards you are using.
sudo insmod mod_auldrv.ko offset=0x300,0x310 bytes=0x10,0x10 acronym="stx104","tracere" type="stx104","tracere"

#allows parameters to be sent via text file.
#insmod mod_auldrv.ko "$(< aul_hw.txt)"

# all of this is now performed via udev rule.  See the readme.txt file for more information.
#chgrp $group /dev/auldrv
#chmod 666 /dev/auldrv
#chgrp $group /dev/stx104
#chmod 666 /dev/stx104
