#!/bin/bash

####################################################################################
# Kernel Module Installer
# Apex Embedded Systems
#
# "$Date: 2015-01-14 17:25:35 -0600 (Wed, 14 Jan 2015) $"
####################################################################################

MOD="mod_auldrv"

####################################################################################
# Make sure we use sudo if necessary
#

if ! [ $(id -u) = 0 ]; then
   DOIT_AS_SUDO=1
else
   DOIT_AS_SUDO=0
fi

####################################################################################
#find the root group
#
if grep '^staff:' /etc/group > /dev/null; then
	echo root is staff group
    group="staff"
else
	echo root is wheel group
    group="wheel"
fi

####################################################################################
# install library for installation just after boot-up

if [ $DOIT_AS_SUDO -eq 1 ]; then
  	echo Manually loading kernel module requesting sudo password
	sudo mkdir -p /lib/modules/$(uname -r)/extra
	sudo cp mod_auldrv.ko /lib/modules/$(uname -r)/extra
	sudo chown root:root /lib/modules/$(uname -r)/extra/mod_auldrv.ko
	sudo depmod -a 
else
  	echo Manually loading kernel module as we are already root
	mkdir -p /lib/modules/$(uname -r)/extra
	cp mod_auldrv.ko /lib/modules/$(uname -r)/extra
	chown root:root /lib/modules/$(uname -r)/extra/mod_auldrv.ko
	depmod -a  
fi

