#!/bin/bash

####################################################################################
# Kernel Module Manual Loader  
# Apex Embedded Systems
#
# "$Date: 2015-01-14 17:25:35 -0600 (Wed, 14 Jan 2015) $"
####################################################################################

echo "variables passed in:   $1, $2"

####################################################################################
# Make sure we use sudo if necessary
#

if ! [ $(id -u) = 0 ]; then
   DOIT_AS_SUDO=1
else
   DOIT_AS_SUDO=0
fi

####################################################################################
#find the root group
#
if grep '^staff:' /etc/group > /dev/null; then
	echo root is staff group
    group="staff"
else
	echo root is wheel group
    group="wheel"
fi

####################################################################################
# install the module
#
# NOTE: This is just an example, and your exact implementation will be dictated 
#       by the boards you are using.

CMD='insmod mod_auldrv.ko offset=0x300,0x310 bytes=0x10,0x10 acronym=stx104,tracere type=stx104,tracere'
echo $CMD

if [ $DOIT_AS_SUDO -eq 1 ]; then
  	echo Manually loading kernel module and may request sudo password
  	sudo $CMD
else
	echo Manually loading kernel module as we are already root
  $CMD
fi

####################################################################################
# Notes
#

#allows parameters to be sent via text file.
#insmod mod_auldrv.ko "$(< aul_hw.txt)"

#all of this is now performed via udev rule.  See the readme.txt file for more information.
#chgrp $group /dev/auldrv
#chmod 666 /dev/auldrv
#chgrp $group /dev/stx104
#chmod 666 /dev/stx104
