Demo Multiple Boards: /home/mike/aes_eclipse/aul_tree/aul/aul.h File Reference
aul.h File Reference
#include "../shared/callconv.h"
#include "../shared/device_list.h"
#include "../devices/dev_avail.h"
Macros
#define MODULE_AUL 13 /* module ID number */
#define MODULE_AUL_NAME "aul"
#define MODULE_AUL_REV "$Date: 2015-01-12 14:07:46 -0600 (Mon, 12 Jan 2015) $"
Functions
AUL_DLL_API int AULCALLCONV AUL_Device_Open (const char *device_acronym_name, int *board)
AUL_DLL_API int AULCALLCONV AUL_Device_Close (int board)
AUL_DLL_API int AULCALLCONV AUL_Device_List_Get (device_list_type *device_list)
AUL_DLL_API int AULCALLCONV AUL_Device_Logical_Get (const char *device_acronym_name, DEVICE_LOGICAL_ENUM *logical_id)
AUL_DLL_API int AULCALLCONV AUL_Ioctl (int board, unsigned int command, unsigned long argument)
AUL_DLL_API int AULCALLCONV AUL_Initialization (const char *hardware_definition_file_name)
AUL_DLL_API int AULCALLCONV AUL_Termination (void)
AUL_DLL_API const char *AULCALLCONV AUL_Last_Error_Get (void)
AUL_DLL_API const char *AULCALLCONV AUL_Error_Last_Get (void)
AUL_DLL_API const char *AULCALLCONV AUL_Error_String (int error_code)
AUL_DLL_API int AULCALLCONV AUL_Library_Revision (unsigned long *revision)
AUL_DLL_API const char *AULCALLCONV AUL_Library_Name (void)
AUL_DLL_API const char *AULCALLCONV AUL_Driver_Name (void)
AUL_DLL_API int AULCALLCONV AUL_Driver_Is_Debug_Active (int *debug_is_active)
AUL_DLL_API int AULCALLCONV AUL_Library_Is_Debug_Active (int *debug_is_active)
AUL_DLL_API int AULCALLCONV AUL_Library_Process_Id_Get (unsigned long *pid)
AUL_DLL_API int AULCALLCONV AUL_Revision_Sys_File (unsigned long *revision)
AUL_DLL_API int AULCALLCONV AUL_Driver_Revision (unsigned long *revision)
Macro Definition Documentation
#define MODULE_AUL 13 /* module ID number */
Definition at line 2 of file aul.h.
#define MODULE_AUL_NAME "aul"
Definition at line 3 of file aul.h.
#define MODULE_AUL_REV "$Date: 2015-01-12 14:07:46 -0600 (Mon, 12 Jan 2015) $"
Definition at line 40 of file aul.h.
Function Documentation
AUL_DLL_API int AULCALLCONV AUL_Device_Close (int board)
Referenced by main().
AUL_DLL_API int AULCALLCONV AUL_Device_List_Get (device_list_type * device_list)
AUL_DLL_API int AULCALLCONV AUL_Device_Logical_Get (const char * device_acronym_name, DEVICE_LOGICAL_ENUM * logical_id)
AUL_DLL_API int AULCALLCONV AUL_Device_Open (const char * device_acronym_name, int * board)
Referenced by main().
AUL_DLL_API int AULCALLCONV AUL_Driver_Is_Debug_Active (int * debug_is_active)
AUL_DLL_API const char* AULCALLCONV AUL_Driver_Name (void)
Referenced by main().
AUL_DLL_API int AULCALLCONV AUL_Driver_Revision (unsigned long * revision)
AUL_DLL_API const char* AULCALLCONV AUL_Error_Last_Get (void)
AUL_DLL_API const char* AULCALLCONV AUL_Error_String (int error_code)
Referenced by main().
AUL_DLL_API int AULCALLCONV AUL_Initialization (const char * hardware_definition_file_name)
Referenced by main().
AUL_DLL_API int AULCALLCONV AUL_Ioctl (int board, unsigned int command, unsigned long argument)
AUL_DLL_API const char* AULCALLCONV AUL_Last_Error_Get (void)
AUL_DLL_API int AULCALLCONV AUL_Library_Is_Debug_Active (int * debug_is_active)
AUL_DLL_API const char* AULCALLCONV AUL_Library_Name (void)
Referenced by main().
AUL_DLL_API int AULCALLCONV AUL_Library_Process_Id_Get (unsigned long * pid)
AUL_DLL_API int AULCALLCONV AUL_Library_Revision (unsigned long * revision)
AUL_DLL_API int AULCALLCONV AUL_Revision_Sys_File (unsigned long * revision)
AUL_DLL_API int AULCALLCONV AUL_Termination (void)
Referenced by main().