Demo Multiple Boards: demo_multiple_boards.c File Reference
demo_multiple_boards.c File Reference
#include <stdio.h>
#include "../aul_tree/aul/aul_public.h"
Macros
#define DEMO_BASIC_REV "$Date: 2014-05-08 22:52:12 -0500 (Thu, 08 May 2014) $"
Functions
int main (int argc, char *argv[])
Detailed Description
Demonstrates opening two devices at the same time application example.
Definition in file demo_multiple_boards.c.
Macro Definition Documentation
#define DEMO_BASIC_REV "$Date: 2014-05-08 22:52:12 -0500 (Thu, 08 May 2014) $"
Definition at line 50 of file demo_multiple_boards.c.
Function Documentation
int main (int argc, char * argv[])
main()
Demonstrates simple interactions with the library and driver.
ASSUMPTTIONS:
The library (aul_tree) has been previously compiled to a static library. Run make in "/aul_eclipse/aul_tree/_Out_Library_Shared_Application_Debug").
AUL driver has been successfully compiled and installed. Please refer to the readme.txt file in either "/aul_eclipse/drv_aul_x86" or "/aul_eclipse/drv_aul_sim".
Assumes that two devices with acronym names of "stx104" and "tracere" were provided during insmod.
DESCRIPTION: This demonstration illustrates library initialization, multiple device open, multiple device close and library termination. It also illustrates how to print out the name of the library and driver.
Main Variables
int error_code
Variable used to report error codes from the library function calls.
int board[2]
Variable array used to hold the device descriptors. These are used for subsequent device related library function calls.
AUL_Library_Name()
DESCRIPTION:
Report the AUL library name. This is a library function call.
How does this application know which library to use? It is defined in Eclipse under "Project-->Properties-->C/C++ Build-->Settings-->GCC Linker-->Libraries". Left click on the project in the Eclipse Project Explorer and then right-click and go down to "Properties...". Note that the library will be different between Debug and Release builds.
This application uses the statically built library. So, either "auldebug.a" or "aul.a" will be reported by the AUL_Library_Name() function. The "auldebug.a" is the library that contains additional debug features. The library (in this case the application) will append debug information to a "dmesg.txt" file located in the same folder as the application.
The "dmesg.txt" file contains very detailed information regarding library behavior. If at any time you run into an issue, please be prepared to send the dmesg.txt file to Apex for further analysis. The dmesg.txt file can be deleted at any time; debug features within the library will automatically create the file and continue to append to the file.
In terms of the kernel driver, the kernel driver appends its debug information to the kernel debug ring buffer. Retrieve the information by using the Linux command "dmesg".
USAGE:
Optional. Not required to be used in any application. Its purpose is more to support debug.
AUL_Initialization()
DESCRIPTION:
Initialize the driver. This 'opens' the controller portion of the driver. In other words, we are opening the /dev/auldrv from the kernel perspective. In addition, this is an opportunity for the driver and library to exchange house keeping information.
This function is a library function call that will open the /dev/auldrv kernel device. The "/dev/auldrv" device is made available upon completion of the driver installation; in other words, successful insmod command.
PARAMETERS
Hardware is completely defined during installation of the Linux driver and therefore we simply pass a NULL.
USAGE:
Required. This is required by all applications which use the AUL library.
POSSIBLE ERRORS:
If an error reported is "No such file or directory", this indicates that the mod_auldrv kernel driver has not been installed properly.
AUL_Driver_Name()
DESCRIPTION:
Report the AUL driver name. This is a library function call.
The actual string name is received from the driver itself. Within the driver this string is hard-coded. The suffix portion of the driver name originates from the Makefile of the driver (NAME := auldrv). In other words, the name of the driver will always be "mod_"<suffix name>="">. The name of the driver can also be found using the lsmod Linux command.
USAGE:
Optional. Not required to be used in any application. Its purpose is more to support debug.
AUL_Device_Open()
DESCRIPTION:
Open the device, in this case "stx104". The string name must match the Linux driver (kernel module) insmod acronym="stx104". If the insmod acronym was for example: acronym="mystx104", then we would open using a string called "mystx104" rather than "stx104".
Since we are opening two devices, during insmod we need:
insmod acronym="stx104","tracere".
This function is a library call which eventually opens the device /dev/stx104. In addition there is a whole bunch of housekeeping operations that are performed within this library call. This function helps to keep application code short and concise. The 'board' parameter is a descriptor that must be passed to other library functions so that it knows which board you are referring to.
USAGE:
Required only if you want to communicate with a hardware device (board). It is possible to make library function calls to non-related device function calls without opening a device.
AUL_Device_Close()
DESCRIPTION:
Close the device. In this specific case the previously opened "tracere" device is closed.
This function is a library call that is made which eventually closes the /dev/tracere. In addition, this function does a variety of house keeping operations.
USAGE
Strongly suggested that it be paired with a previously successful AUL_Device_Open(). Note: AUL_Termination() will also force the closure of any opened devices.
AUL_Device_Close()
DESCRIPTION:
Close the device. In this specific case the previously opened "stx104" device is closed.
This function is a library call that is made which eventually closes the /dev/stx104. In addition, this function does a variety of house keeping operations.
USAGE
Strongly suggested that it be paired with a previously successful AUL_Device_Open(). Note: AUL_Termination() will also force the closure of any opened devices.
AUL_Termination()
DESCRIPTION:
Terminates the driver. This 'closes' the controller portion of the driver. In other words, we are closing the /dev/auldrv from the kernel perspective.
There are other house keeping activities that occur during this call as it works its way through the library and driver.
This function is a library call.
USAGE:
Required in that it must be paired with a previously successful AUL_Initialization(). If the previous AUL_Initialization() failed, then this function need not be called.
Definition at line 72 of file demo_multiple_boards.c.
References AUL_Device_Close(), AUL_Device_Open(), AUL_Driver_Name(), AUL_Error_String(), AUL_Initialization(), AUL_Library_Name(), and AUL_Termination().
 {
   /*********************************************************************/
   int error_code;
   int board[2];
   /*********************************************************************/
   printf( "Library name = %s\n", AUL_Library_Name() );
   /*********************************************************************/
   error_code = AUL_Initialization( NULL );
   if ( error_code )
   { /* Library failed to initialize, report the error and exit application. */
     printf( "AUL_Initialization error: %s\n", AUL_Error_String( error_code ) );
     return -error_code;
   }
   printf( "AUL_Initialization successful\n" );
   /*********************************************************************/
   printf( "Driver name = %s\n", AUL_Driver_Name() );
   /*********************************************************************/
   error_code = AUL_Device_Open( "stx104", &(board[0]) );
   if ( error_code )
   {
     printf( "STX104: AUL_Device_Open error: %s\n", AUL_Error_String( error_code ) );
     AUL_Termination();
     return -error_code;
   }
   printf( "STX104: AUL_Device_Open successful\n" );
   /*************************************************************************
    * Second device to be opened.
    **/
   error_code = AUL_Device_Open( "tracere", &(board[1]) );
   if ( error_code )
   {
     printf( "TRACERE: AUL_Device_Open error: %s\n", AUL_Error_String( error_code ) );
     AUL_Termination();
     return -error_code;
   }
   printf( "TRACERE: AUL_Device_Open successful\n" );
   /*************************************************************************
    * Uncomment this line to skip device closures.  What this demonstrates
    * is that if for any reason a device is open and the AUL_Termination()
    * is called, all open devices will automatically be closed.
    */
   goto Main_Terminate;
   /*********************************************************************/
   error_code = AUL_Device_Close( board[1] );
   printf( "TRACERE: AUL_Device_Close successful\n" );
   /*********************************************************************/
   error_code = AUL_Device_Close( board[0] );
   printf( "STX104: AUL_Device_Close successful\n" );
   /*********************************************************************/
 Main_Terminate:
   error_code = AUL_Termination();
   if ( error_code )
   {
     printf( "AUL_Termination error %s\n", AUL_Error_String( error_code ) );
     return -error_code;
   }
   printf( "AUL_Termination successful\n" );
   return error_code;
 }