#!/bin/bash

# Apex Universal Library Kernel Module Loader  
# Apex Embedded Systems
#
# 
# "$Date: 2014-05-06 17:08:32 -0500 (Tue, 06 May 2014) $"

#
# Make sure we are root
#
if [[ $EUID -ne 0 ]]; then
	echo "NOTICE: this script must be run as root" 1>&2
	exit 1
fi

#
#find the root group
#
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

#
# install the module
#
# NOTE: this is temporary, but gives an example of all parameters.
sudo insmod mod_auldrv.ko offset=0x300,0x310 bytes=0x10,0x10 acronym="stx104","tracere" type="stx104","tracere"
#allows parameters to be sent via text file.
#insmod mod_auldrv.ko "$(< aul_hw.txt)"
#chgrp $group /dev/auldrv
#chmod 666 /dev/auldrv
#chgrp $group /dev/stx104
#chmod 666 /dev/stx104
